### ISSUE TITLE
Quest: How to Break into the Arcatraz

### ISSUE THREAD

**Issue by Rickyb12** [elysium-project/tbc-bug-tracker#1003]
**Summary:** 
When i attempt to turn in the quest and select my reward it tells me my inventory is full.

**Steps to Reproduce:** 
none
**Expected Results:** 
Receive Sha'tari Vindicator's Waistguard and Key to Arcatraz
**Actual Result:**
Error message saying inventory is full
**Additional Information:**
Bags have 20 free slots and 3 free on keyring

![image](https://user-images.githubusercontent.com/55565718/65291363-6c61c680-db29-11e9-99e6-d2c82de61f9b.png)

**Comment by buckshaq** [comment]
this actually works. you need to move the quest items to your 16 slot main bag though

**Comment by Rickyb12** [comment]
I moved an item out of my backpack and it now works. Thanks!
