### ISSUE TITLE
The Cipher of Damnation

### ISSUE THREAD

**Issue by thk88** [elysium-project/tbc-bug-tracker#1007]
**Summary** 
I did all the prequests for the Tempest Keep attunement questline while leveling (68-69), and finished the quests all the way up to "The Cipher of Damnation". I wasn't able to get "The Cipher of Damnation" since it requires level 70, which is as intended.
Problem is that I still cannot take the quest, now at level 70.

Here's a link to the wiki of the quest line:
https://wowwiki.fandom.com/wiki/The_Tempest_Key

**Steps to Reproduce:** 
Complete all the quests prior to level 70 and then try to take "The Cipher of Damnation".

**Expected Results:** 
The quest should be available.

**Actual Result:**
The quest isn't available.

**Additional Information:**
I was the fourth to get 70 on the server, so it's been a while since I completed the quests and haven't thought more about the quest line since then. So it might be an older issue that isn't relevant any longer.

**Comment by HamonTim** [comment]
To make sure, you tried to take the quest from "Oronok Torn-heart" in his farm and not in the Gul'dan Hand?

**Comment by thk88** [comment]
Yes, I tried to take it from his farm.
