### ISSUE TITLE
[Quest] Teleport This!

### ISSUE THREAD

**Issue by andersleet** [elysium-project/tbc-bug-tracker#1027]
**Summary:** 

Quest states to go to Forge Base: Gehenna, use the provided item to mind control Mo'args around the base and use their ability to destroy the three teleporters.

**Steps to Reproduce:**

Accept quest. Go to location. Mind control mob. Cast mob's spell to detonate the teleporter. 

**Expected Results:** 

Teleporter detonates, giving quest credit.

**Actual Result:**

Nothing happens when you use the controlled mob's detonate ability.

**Additional Information:**

Item works, but spell does not detonate the teleporter; and many times if you get close to the teleporter the mind control will break, even if you (your character, not the controlled mob) are in plenty of range of the controlled mob.

**Comment by HamonTim** [comment]
I confirm I had the same issue and I will add I got "Evade" result when I launch the detonate spell close to the teleporter.
I also tried after a server crash to see if it can be done at least once, but no still getting "Evade".
