### ISSUE TITLE
Quest: The attack!

### ISSUE THREAD

**Issue by Mountainweed** [elysium-project/tbc-bug-tracker#1029]
**Summary:** 
Quest "[the attack](https://tbcdb.com/?quest=434)(quest=434)" does not activate properly.

**Steps to Reproduce:** 
Accept quest "the attack" from "Tyrion(npc=7766)".

**Expected Results:** 
Tyrion's Spybot (npc=8856) disguises itself as Priestess Tyriona (npc=7779). 
Priestess Tyriona goes into the library to fetch Lord Gregor Lescovar (npc=1754) who goes back to the garden. He then dismisses all the nearby guards and Marzon the Silent Blade (npc=1755)  shows up. They have a conversation and then become hostile to the player.

**Actual Result:**
After a while the quest tracker dings off "Overhear Lescovar and Marzon's Conversation". Nothing else happens.

**Additional Information:**
Pretty important quest to fix as it is part of a questline for "Seal of Wrynn(item=2933)". It is a questline that you put a lot of time into before you get stuck with this bug, so it is very frustrating for players.

**Comment by MisaHack** [comment]
Yes, I have the same issue with this quest. It does not work correctly.
![WoWScrnShot_101119_180137](https://user-images.githubusercontent.com/38266502/66760869-38b55a80-eea3-11e9-8233-d6fd88f0d86a.jpg)

**Comment by MisaHack** [comment]
Quest still not working! graa
