### ISSUE TITLE
[Hunter] Distracting Shot Broken

### ISSUE THREAD

**Issue by generalwrex** [elysium-project/tbc-bug-tracker#1034]
**Summary:** 
  Hunters Distracting Shot doesn't do anything.
**Steps to Reproduce:** 
  Pet has aggro, shoot distracting shot to taunt from pet, nothing happens at all.
**Expected Results:** 
 Mob should be focused on me.
**Actual Result:**
 Mob is not focused on me
**Additional Information:**
It's a very useful ability to pull mobs off healers, however it doesn't function at all.

**Comment by Ziggy-QA** [comment]
Was your pet taunting the target?

**Comment by buckshaq** [comment]
distracting shot is not a taunt btw....

**Comment by ArisTheGod2** [comment]
This is correct. The ability only give you additional aggro but it is not an actual taunt. This comes in WOTLK.

**Comment by generalwrex** [comment]
Yeah sorry, It's fine then.  I haven't played pre-wotlk in a very long time ;)
