### ISSUE TITLE
[BUG] Finding the Keymaster

### ISSUE THREAD

**Issue by andersleet** [elysium-project/tbc-bug-tracker#1035]
**Summary:** 
Group quest to kill an elite giant Apex.

**Steps to Reproduce:** 
Have quest, kill mob (west of Manaforge Duo) and his spawns.

**Expected Results:** 
Loot quest item (Apex's Crystal Focus) from Apex's corpse.

**Actual Result:**
The quest item does not drop.

**Additional Information:**
Attempted this a few times now and have not had the item drop.

**Comment by buckshaq** [comment]
I know this has worked for many. were you in a raid?

**Comment by andersleet** [comment]
Nope. Almost solo'd it, then asked for another player's help.

**Comment by andersleet** [comment]
Found a solution: if it does not drop, abandon the quest and re-accept it,
