### ISSUE TITLE
Medallion of the Alliance costs wrong amount of honor

### ISSUE THREAD

**Issue by Rorau** [elysium-project/tbc-bug-tracker#1039]
**Summary:** 
It's all explained in this screenshot: 
https://i.imgur.com/p8X9VNJ.png

Basically the vendor show that the medallion costs 16983 honor. 
I have 17025 honor, so that should be enough. 
When I try to buy it, I get red error essage that says I don't have enough honor points. And yellow text appears in the chat window that says the item costs 24975 honor. 

**Steps to Reproduce:** 
Acquire sufficient honor to buy the medallion (>16983 honor), then try to buy it. 

**Expected Results:** 
Able to buy it. 

**Actual Result:**
I get error message says I don't have enough honor. Yellow message says it costs 24975. So either the vendor shows wrong, or the item has some sort of internal cost issue in the database. 

**Additional Information:**
I don't know what it's _supposed_ to cost, I've just been going for the honor the vendor says. I can't find any (official) information on what it used to cost back in 2.4.3 or earlier.

**Comment by HamonTim** [comment]
I found this source of 29th June 2007 (2.1.2)
https://wowwiki.fandom.com/wiki/Medallion_of_the_Alliance_(rare)?oldid=725521

This item is a PvP reward, and can be purchased for 16983 honor from Master Sergeant Biggins <Officer Accessories Quartermaster> in Champions' Hall.

**Comment by Ziggy-QA** [comment]
Thats correct. You can try clearing your WDB and it might display the correct amount of honor. Especially if your client came with an already populated WDB, or you played on other TBC servers previously.
