### ISSUE TITLE
Kroshius' Infernal core quest Warlock

### ISSUE THREAD

**Issue by Nodeiros** [elysium-project/tbc-bug-tracker#1041]
**Summary:** 
https://classic.wowhead.com/quest=7603/kroshius-infernal-core
**Steps to Reproduce:** 
https://i.gyazo.com/thumb/1200/f656945258639a7cd4e5727ee4e4979c-jpg.jpg
**Expected Results:** 
When you click at the Fel Fire you reanime the kroshuis for slay it and loot the infernal core
**Actual Result:**
nothing when you active the fel fire
**Additional Information:**
thx

**Comment by Dodez1** [comment]
Same Here pls Fix

**Comment by Firak55** [comment]
Yep big problem on TBC server. Please fix.

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
