### ISSUE TITLE
[The Second Trial] Still broken

### ISSUE THREAD

**Issue by andersleet** [elysium-project/tbc-bug-tracker#1045]
**Summary:** 
Completed The First Trial (resurrection spell). Accepted The Second Trial and went to mob (Master Kelerun Bloodmourn) but cannot interact with him. Also attempting to link quest in chat (world channel and say confirmed, probably all) crashes or disconnects client.

**Steps to Reproduce:** 
Be paladin, accept The Second Trial. Go to NPC listed in quest log. Attempt to link quest in chat.

**Expected Results:** 
NPC being intractable to continue quest line. Link quest just like any other quest I've linked and seen linked so far.

**Actual Result:**
No interaction with NPC, game crashes or disconnects when linking the quest in chat.

**Additional Information:**
I accepted both The First Trial and The Second Trial at the same time. I completed the entire The First Trial quest line before going to do The Second Trial. Not sure if that matters or not. Also I am currently a level 30 paladin, Horde side.

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
