### ISSUE TITLE
[Quest] [Broken] Gordunni Cobalt

### ISSUE THREAD

**Issue by generalwrex** [elysium-project/tbc-bug-tracker#1047]
**Summary:** You're supposed to dig at the glowing blue spots on the ground, Nothing comes from digging in those spots

**Steps to Reproduce:** Try to dig with the provided shovel.

**Expected Results:** Get some Cobalt!

**Actual Result:** Get thin air!

**Additional Information:** its this quest https://tbcdb.com/?quest=2987

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
