### ISSUE TITLE
Script Bug: One Shot. One Kill. (Darkshore)

### ISSUE THREAD

**Issue by Ennello** [elysium-project/tbc-bug-tracker#1048]
Summary: After accepting the quest, nothing happens.

Steps to Reproduce: Go to the southeastern corner of Darkshore. Brace the eastern hills and you'll find Sentinel Aynasha, with a quest marker above her head. Accept the quest.

Expected Results: Aynasha says that she hears something coming from the west. A first wave of 3 mobs appears. Two more waves follow.

Actual Result: Nothing happens. The quest can't be finished.

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
