### ISSUE TITLE
Mining nodes either don't exist or don't respawn

### ISSUE THREAD

**Issue by TheBozzer** [elysium-project/tbc-bug-tracker#1049]
Summary:
Mining nodes across the WHOLE of Azeroth (not sure on the outlands, to low lvl to tell) are either extremely rare or just never re-spawn.  It's knocking on to the auction house as the cost for just copper ore or bar is one gold (which is ludicrous), so the in game economy is all to pot, with less and less crafted items to buy.

Steps to Reproduce:
Can be witnessed by anyone, in any zone. Look round for nodes and you won't find any.

Expected Results:
Lots of nodes to mine to skill up Engineering, Blacksmithing and Jewelcrafting.

Actual Result:
No nodes to mine.

Additional Information:
Welcome to tag this to #658 as it's near enough the same issue, but it's old and un-loved so might as well give it a proper bump.

**Comment by generalwrex** [comment]
From the discord: 
**Rain** _Today at 4:27 PM_
For those asking about mining nodes - they are set a bit low
We’re pushing some revisions with new data we received
