### ISSUE TITLE
"Kroshius' Infernal Core

### ISSUE THREAD

**Issue by Nodeiros** [elysium-project/tbc-bug-tracker#1053]
**Summary:** 
"Kroshius' Infernal Core quest bugged
**Steps to Reproduce:** 
you have to use the fel fire to wake up kroshius but nothing happens
**Expected Results:** 
summon kroshius with the fel fire but nothing
**Actual Result:**
nothing
**Additional Information:**
https://gyazo.com/24fe9d253c24de007722b34cc9c3c703 thx

**Comment by Dodez1** [comment]
Same Here pls Fix
