### ISSUE TITLE
Voidreaver in Tempest Keep, The eye. Does not cast Arcane Orb

### ISSUE THREAD

**Issue by jsprn** [elysium-project/tbc-bug-tracker#1059]
**Summary:** 
The boss is currently very flawed when it comes to a crucial mechanic since Voidreaver doesnt cast Arcane orbs on the raid. 

According to https://wowwiki.fandom.com/wiki/Void_Reaver
Arcane Orb: 7000+ AoE with 6 sec silence, (resistible, binary), and 3 sec cooldown. Arcane Orb is fired at a random raid member at least 18 yards away from the Void Reaver and takes a few seconds to reach the place where the player was standing. Orbs may be fired at people below the minimum range if there are no other valid targets.

**Steps to Reproduce:** 
Have raid members within targeting range of Arcane Orb (atleast 18 yards from boss)

**Expected Results:** 
People outside of 18 yard range should be targeted with Arcane Orbs

**Actual Result:**
No Arcane Orbs casted from Voidreaver during the entire bossfight.

**Additional Information:**
Lootreaver is real

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
