### ISSUE TITLE
Unable to learn Repair Bot Schematic From BRD

### ISSUE THREAD

**Issue by snekey386** [elysium-project/tbc-bug-tracker#1061]
**Summary:** (Sorry posted this in Classic tracker two weeks ago) Hi, Went into BRD with friends on Rogue (Char Name "Snekey") with 372 Engineering and was unable to learn the schematic for the field repair bot, comes up with you can't comprehend as if I don't have engineering.

Please see attached pic (sorry for it's length, I have dual monitor setup)

![bugged repair bot](https://user-images.githubusercontent.com/56773326/67869790-d3f63300-fb25-11e9-8cb8-40cb538e53dc.jpg)

**Steps to Reproduce:** Try and learn The schematic

**Expected Results:**  Learn The Schematic

**Actual Result:** Just keep getting the same result as if I don't have the engineering Skill.

**Additional Information:** I am now Max level (was 61) and max level engineering 375, I have run the instance well over 20 times, tried relogging inside and always get the same result.

KoKs is having the same issue, reported on discord

Your assistance would be greatly appreciated, Thank You
emely

**Comment by snekey386** [comment]
Hi, While awaiting a response/fix or confirmation it is not just certain factors stopping me learning the schematic I have leveled a new char and chose Goblin engineering.
I tried again with both my original Char and the new one and both got the same "you are unable to understand the giberish".

Please Please could you advise/help I really want this schematic on at least one of the characters so it can at least build them for the other if needed and am out of ideas and don't want to invest anymore wasted time if it is just unlearn-able/ bugged.

Any advise or help would be gratefully recieved.

**Comment by snekey386** [comment]
Just noticed you are investigating this, Thank you so much Ziggy you are my hero :)

**Comment by Ziggy-QA** [comment]
@snekey386 Fix is live on PTR, should be fine. Expect the live fix to be on monday.

**Comment by snekey386** [comment]
@Ziggy-QA  Thank you, It is appreciated, It was sending my Schematic OCD crazy :)

**Comment by snekey386** [comment]
Confirmed working as goblin and gnomish engineer, got it on both chars, thank you
