### ISSUE TITLE
 https://tbcdb.com/?quest=10679 Bugged quest forged illidari-bane Blade

### ISSUE THREAD

**Issue by Nodeiros** [elysium-project/tbc-bug-tracker#1062]
**Summary:** 
https://tbcdb.com/?quest=10679
When using the quest item "forged illidari-bane Blade" we have the right to an escapee
https://gyazo.com/1fa5c6231704e798b0640f0ebd9b700f

**Steps to Reproduce:** 
accept the quest after the long quest suit and go on top the montain use item in bag on lava at the hand of guldan 

**Expected Results:** 
https://gyazo.com/47491611a35e1cfc1650419f89cb3ed8 

**Actual Result:**

after throwing the sword in the lava we should be able to pick it up or we can not object is not collectable
https://gyazo.com/33e0f81c258de5e7e48cb5bbdd9b60de
**Additional Information:**
https://www.youtube.com/watch?v=2FfuH0x0DwQ

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
