### ISSUE TITLE
Arena Ranked Team Creation is Bugged

### ISSUE THREAD

**Issue by ArisTheGod2** [elysium-project/tbc-bug-tracker#1063]
**Summary:** New Arena teams that are formed do not start with the correct rating points. They start with 300 instead of 1500.

**Steps to Reproduce:** Create arena team.

**Expected Results:** 1500 rating upon creation.

**Actual Result:** 300 rating upon creation.

**Additional Information:**

**Comment by IvanDanshin** [comment]
Fixed.
Thanks for report.
