### ISSUE TITLE
[Broken] Venom Bottles

### ISSUE THREAD

**Issue by andersleet** [elysium-project/tbc-bug-tracker#1066]
**Summary:** 
Cannot pick up venom bottle quest in Hinterlands.

**Steps to Reproduce:** 
Go to Hiri'watha, attempt to pick up bottle from table.

**Expected Results:** 
Item gets added to inventory, can then accept quest.

**Actual Result:**
Interacting with bottle does not loot the (starting) quest item.

**Additional Information:**
Normally a pickup that fails results in "empty slot" loot.

**Comment by IvanDanshin** [comment]
Fixed.
Thanks for report.
