### ISSUE TITLE
Windy Clouds not spawning in nagrand

### ISSUE THREAD

**Issue by vladimyrr** [elysium-project/tbc-bug-tracker#1067]
I've done a few patrols of Nagrand for Windy Clouds to use with my Zapthrottle Mote Extractor and have used a map which references the spawn locations. However none of the Windy Clouds generate.

**Comment by buckshaq** [comment]
I have yet to see one in Nagrand also. have patted through there many times

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
