### ISSUE TITLE
[Broken] Stranglethorn Fever

### ISSUE THREAD

**Issue by andersleet** [elysium-project/tbc-bug-tracker#1068]
**Summary:** 
The third gorilla (Mokk the Savage) either spawns and then despawns and/or despawns immediately after killing him.

**Steps to Reproduce:** 
Get a gorilla fang, go to the Spirit Den in STV, turn in to Witch Doctor Unbagwa to start quest. When the second gorilla (Konda) spawns, Mokk SOMETIMES will spawn before it dies. and then he will despawn.

**Expected Results:** 
Three gorillas spawn, one at a time, third is Mokk. He should drop his heart as a quest item.

**Actual Result:**
Cannot loot Mokk; he despawns randomly but if you do manage to slay him he despawns immediately.

**Additional Information:**
Why so broken :(

**Comment by andersleet** [comment]
Was able to complete it ONLY if you allow all three gorillas to spawn and kill Mokk first. So definitely bugged somehow.

**Comment by IvanDanshin** [comment]
Fixed.
Thanks for report.
