### ISSUE TITLE
[broken] Mountain Giant Muisek

### ISSUE THREAD

**Issue by andersleet** [elysium-project/tbc-bug-tracker#1070]
**Summary:** 
Supposed to kill giants in Feralas and get their souls (?)

**Steps to Reproduce:** 
Have the quest, go to north west Feralas where the giants are.

**Expected Results:** 
Use the item to gather the souls.

**Actual Result:**
Invalid target on the giants slain; using the item to shrink them from elites to normal.

**Additional Information:**
They turn into Zapped Wave Striders when using the quest item.

**Comment by IvanDanshin** [comment]
Fixed and pushed to PTR. Soon will be updated on live server. :)
Thanks for report.
