### ISSUE TITLE
SSC: Hydross Resistance Bugs

### ISSUE THREAD

**Issue by Nunku** [elysium-project/tbc-bug-tracker#1078]
**Summary:** Hydross is suddenly doing around 2 times more damage than the week before.

**Steps to Reproduce:** Regardless of whether the Main tanks have their full resistance and defense cap met, the boss is doing untankable damage now.

**Expected Results:** The boss should be possible to tank up to the 4th mark, or more precisely to the end of the 3rd mark before the transition to the other phase is forced. 

**Actual Result:** Starting in mark 1 the boss is able to hit a full resist and defense capped warrior for up to 14k damage (with partial resist), which makes the boss untankable in 2nd, and specially the 3rd mark, unless the luck draws during those seconds allow the tank to survive it fully.

**Additional Information:** Following are some screenshots showing the difference from last week (7/11) to this week (14/11).

This is my set with full defense and frost resist cap
![Sem Título](https://user-images.githubusercontent.com/57720388/68779741-13944300-062d-11ea-8025-c3f42556e5a7.png)

And below is the damage from last week(above) and this week (below). The first was our best try with around 4min and the second is our best try this week with around 8min - one tank was one-shotted at mark 3. As you can see the damage taken per sec almost doubled in both the main tanks and the off tanks.
![1](https://user-images.githubusercontent.com/57720388/68779820-2eff4e00-062d-11ea-837f-b5c28379c087.JPG)
![4](https://user-images.githubusercontent.com/57720388/68779823-30307b00-062d-11ea-82ec-c0ea73079197.JPG)

Below is the damage I took in the 4 min try last week and the 8 min one this week. The gear, raid setup was exactly the same in both tries. As you can see, even in mark 1 the boss was hitting as if it was on mark 3 or 4 from the previous week. And even without getting a single crit (defense cap) the damage in mark 3 is nearly one-shotting me.
![2](https://user-images.githubusercontent.com/57720388/68780100-a46b1e80-062d-11ea-8519-403c179e816c.JPG)
![5](https://user-images.githubusercontent.com/57720388/68780101-a59c4b80-062d-11ea-8473-feeebdacb643.JPG)

And here is our nature resist tank that is not crit immune. As you can see the crits are even higher from last week to this week.
![3](https://user-images.githubusercontent.com/57720388/68780421-2f4c1900-062e-11ea-852a-63721bdd46e1.JPG)
![6](https://user-images.githubusercontent.com/57720388/68780424-3115dc80-062e-11ea-8099-87d675b98148.JPG)

This is a death log from a bad pull. This is mark one damage resisted partially for around 11k, and even so I got hits for 8k.
![7](https://user-images.githubusercontent.com/57720388/68780713-9669cd80-062e-11ea-91b4-6c9396a47368.jpg)

The logs from last week and this week raid.
https://legacyplayers.com/Raids/Viewer/Default.aspx?id=9334&exp=1&upl=14185
https://legacyplayers.com/Raids/Viewer/Default.aspx?id=9397&exp=1&upl=14305

**Comment by Ziggy-QA** [comment]
@Nunku Can you please post the links to the logs in question?

**Comment by Nunku** [comment]
There you have it.

**Comment by Ziggy-QA** [comment]
@Nunku We're going to push a massive rebalance of base stats of all npcs in preparation for 2.1 This will reduce the damage of Hydross, among other things. As a result I will mark this as fixed.

**Comment by Nunku** [comment]
@Ziggy-QA I remember that 2.1 brought big nerfs in SSC and TK bosses, some reworks as well.

Even so, I think you should investigate the way that resistances are working now in the game for NPC. Last night on our Hydross kill, even when I was resistance capped I was getting many 25% and 50% resists, and very few 75% ones, which is not in any way normal. It should be around 80% hits with 75% resists.

Another finding is that the boss is now ignoring defense stats altogether. 
I was defense capped this week and the week before, but this week I was getting around 5% crits, while I got 0% the week before. I have the screenshots below with the findings.

![1](https://user-images.githubusercontent.com/57720388/68934999-b2d14b80-078f-11ea-8ace-8cc0da07461b.JPG)
![2](https://user-images.githubusercontent.com/57720388/68935000-b369e200-078f-11ea-8a5b-75238441b710.JPG)

Also, I don't know if it is normal for the resist to be applied to the normal hit and then the crit multiplier be calculated after that. 

I know that the boss will be way easier to kill in the next patch but the way it is working is not very correct.

**Comment by Ziggy-QA** [comment]
@Nunku Your defensive stats dont matter here. His attacks count as a spell. You can only hard resist them. This is the reason why hydross does not do crushing blows. 

As for how often a respective resist takes place, your gonna have to provide hard data.

Either way, the original issue of Hydross doing more damage than intended will be fixed in the upcoming update.

**Comment by Nunku** [comment]
@Ziggy-QA That was not the way that elemental bosses worked back in TBC from what I remember. The swing is still a melee attack, and that is the reason why you can still dodge, parry or make him miss you (unlike spells that you can only resist). The crit should be included in this list along with the other melee defensive stats, but since the swing is elemental it is counted as a yellow melee attack (just like a cleave), so the crushing is not possible as the yellow hits normally couldn't crush on bosses. So, overall the hit table should still the same as every boss hit table for melee attacks, it's only the damage type that should change.

There are many sources on the web mentioning the importance of trying to go for defense cap if possible, although not a must (and especially not over resist cap) because the crits are healable if the boss is hitting "normally". This was only a problem with the "Mythic" version of Hydross this week :)

The 2 screenshots show the crit multiplier and the % resisted, and apparently the crit is only applied after the resist happened... I just don't know if this is normal or not, as most crit multipliers usually happen after the reductions been applied.

Regarding the %resisted I will need to dig on the combat logs to search for it, as the logs on the website don't have that information, but that was what I was checking live on our kill. 

Anyways, most of this won't be a problem when he gets a rework on damage later, just trying to help here.
