### ISSUE TITLE
Unable To Craft "Dimensional Ripper Area 52" due to missing Schematic

### ISSUE THREAD

**Issue by snekey386** [elysium-project/tbc-bug-tracker#1079]
Unable To Craft "Dimensional Ripper Area 52" due to missing Schematic from Trainer for "the bigger One" which is used as a regent to make the above Trinket.

Try to make one

Being able to make one

Unable to make one as I am missing a part which I can't create

With the bugged Schematic from BRD, Reported ages ago by myself and several other people so far and the fact you basically can't create anything at the moment of any use, the profession is well and truly broken.

If anyone reads this please help

**Comment by Zylph** [comment]
Have you tried going to the goblin engineering trainer in Tanaris? you MUST have an active goblin membership card. if it is in your bank withdraw it, it will most likely dissapear after being withdrawn. then get new one from trainer.

**Comment by snekey386** [comment]
@Zylph , thank you for the reply. I originally tried gadget, ironforge, hellfire and zanger etc (listed on wowhead) but wasn't being offered anything from the trainers, had membership in bag etc.

Just retried again and walla i have the schematic, thank you so much, I wouldn't of bothered retrying without your reply.  Thanks again Zylph, it is appreciated.
