### ISSUE TITLE
Earthwarden

### ISSUE THREAD

**Issue by frshbnthg** [elysium-project/tbc-bug-tracker#1081]
**Summary:** 
I dont know if its just me or everyone, but when im wearing Earthwarden, the bonus def. rating given by the item is 12 instead of 27
**Steps to Reproduce:** 

**Expected Results:** 
+27 Def. rating

**Actual Result:**
Only +12 Def. rating 
**Additional Information:**

**Comment by HamonTim** [comment]
Yes it's you, 27 Defense gives 11.41 of def for a drood
![image](https://user-images.githubusercontent.com/38241815/69010483-933d4d00-0960-11ea-880c-b47b5a1efdf5.png)
