### ISSUE TITLE
Quest "curse of the tides" not working

### ISSUE THREAD

**Issue by nyhotep** [elysium-project/tbc-bug-tracker#1083]
Quest #611 curse of the tides not working

dive into the ocean in STV and use Catelyn's blade  (#4027) on the murloc altar

Gazban (NPC #2624) spawns and drops stone of the tides (#4034)

Gazban doesn't spawn

Quest chain starts with Ansirem's Key #603

**Comment by IvanDanshin** [comment]
Fixed and pushed to PTR. Soon will be updated on live server. :)
Thanks for report.
