### ISSUE TITLE
[Bugged] The Videre Elixir

### ISSUE THREAD

**Issue by andersleet** [elysium-project/tbc-bug-tracker#1086]
**Summary:** 
Find Gregan Brewspewer in north west of Feralas. Buy his bait item. Go farther north and present it to the non-hostile mob (Miblan Snarltooth) in front of the ruins. He is supposed to interact with it an open the gate behind him to allow you to gather an Evoroot.

**Steps to Reproduce:** 
Find the NPC, buy the bait, go north, place bait by Miblan.

**Expected Results:** 
Miblan should go after the bait, and the gate opens allowing you to gather an Evoroot.

**Actual Result:**
Nothing happens. Miblan just sits there.

**Additional Information:**
I was able to use Noggenfogger Elixir and 60% mount (with ret pally +15% movement speed talent) to slow fall into a corner of the area to get the Evoroot.

**Comment by AngryLarry** [comment]
If I remember correctly, and it didn't change in the last 3 months, the wall behind Miblan can be walked through without the bait or jump the walls.  you just simply walk past the NPC.

**Comment by andersleet** [comment]
I just verified that you CANNOT walk through the barrier.

**Comment by IvanDanshin** [comment]
Fixed and pushed to PTR. Soon will be updated on live server. :)
Thanks for report.
