### ISSUE TITLE
UBRS Key

### ISSUE THREAD

**Issue by Mittzy** [elysium-project/tbc-bug-tracker#1088]
**Summary:** 
The NPC in LBRS does not become friendly to give the UBRS key chain quest.
**Steps to Reproduce:** 
Obtain Unadorned Key of Ascension, get all 3 gems. Find the NPC on the ledge in LBRS.
**Expected Results:** 
The NPC is supposed to turn friendly (Vaelan) who should then give you the quest to continue the key quest chain.
**Actual Result:**
The NPC doesn't change and remains attackable. Vaelan does not appear.
**Additional Information:**
Me and others tried doing this a variety of ways with no luck, some with just the Unadorned Seal in the bags, myself with the Unadorned key and the gems, all with the same results.  Also tried throwing out the Unadorned key and getting another but still the NPC stays unfriendly.

**Comment by IvanDanshin** [comment]
Fixed and pushed to PTR. Soon will be updated on live server. :)
Thanks for report.
