### ISSUE TITLE
[Broken] Deadwood Ritual Totem

### ISSUE THREAD

**Issue by andersleet** [elysium-project/tbc-bug-tracker#1091]
**Summary:** 
Find item from Deadwood mobs, get neutral/friendly with the Timbermaw, take item to Kernda in the tunnel and turn it in.

**Steps to Reproduce:** 
See Summary

**Expected Results:** 
Able to turn quest in.

**Actual Result:**
Even though friendly you attack Kernda, and as a result unable to turn in the quest.

**Additional Information:**
Currently friendly, not neutral with Timbermaw.

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
