### ISSUE TITLE
Quest "Emberstrife" (Onyxia attunement) --> Not working

### ISSUE THREAD

**Issue by frinesi** [elysium-project/tbc-bug-tracker#1092]
**Summary:** Hi, when your use the neck "Amulet of draconic subversion" and you disguise as a member of the Black Dragonflight, the dragon Emberstrife theoretically speaks with you but im doing that and not having any dialogue option.

**Steps to Reproduce:** See summary.

**Expected Results:** Able to talk with the dragon Emberstrife

**Actual Result:** Emberstrife appears Friendly but you can't talk with him.

**Additional Information:**
![emberstrife bug](https://user-images.githubusercontent.com/58507272/70134909-3e504500-1689-11ea-810b-bea5e6b4178a.jpg)

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.

**Comment by frinesi** [comment]
Thanks and good job :)
