### ISSUE TITLE
quest #2930 Data rescue bug

### ISSUE THREAD

**Issue by nyhotep** [elysium-project/tbc-bug-tracker#1095]
Gnomeregan quest with punch card not working

Kill mobs outside instance to get white punch card item #9279.
Use Matrix punchograph 3005-A machine outside instance (Train depot)

**Expected Results:** 
get yellow punch card to continue quest inside instance

**Actual Result:**
Nothing happens, no yellow card.

https://tbcdb.com/?item=9279
https://tbcdb.com/?spell=11512 (creates yellow card)
https://tbcdb.com/?quest=2930

**Comment by IvanDanshin** [comment]
Fixed. Thanks for report!
