### ISSUE TITLE
Missing NPC for quest "Field Duty" in Silithus

### ISSUE THREAD

**Issue by NregitneK** [elysium-project/tbc-bug-tracker#1096]
**Summary:** 
NPC Captain Blackanvil for Alliance quest Field Duty in Silithus isn't implemented

**Steps to Reproduce:** 
- Talk to Windcaller Kaldon at Cenarion Hold in Silithus and accept quest "Field Duty"
- Fill the "Unsigned field duty papers"
- Head to Hive'Zora alliance camp

**Expected Results:** 
Blackanvil should be there to sign your papers

**Actual Result:**
NPC is missing

**Additional Information:**
This block Cenarion Circle rep farming, and a bunch of reward quests

**Comment by IvanDanshin** [comment]
Fixed. Thanks for report!
