### ISSUE TITLE
Wind stones not working in the Twilight camp in Silithus

### ISSUE THREAD

**Issue by NregitneK** [elysium-project/tbc-bug-tracker#1097]
**Summary:** 
The Lesser Wind Stones in the Twilight camp in Silithus don't work

**Steps to Reproduce:** 
- Acquire Twilight Cultist Mantle, Twilight Cultist Cowl and Twilight Cultiste Robe from the hostile NPC in the camp
- Equip all of those item
- Interact with a Lesser Wind Stone

**Expected Results:** 
- One of the following mob should spawn : Azure templar, Crimson Templar, Earthen Templar, Hoary Templar

**Actual Result:**
- Nothing happens

**Additional Information:**
It is possible that the Wind Stones and Greater Wind Stones also don't work but those require items provided once you have farmed a bit on Lesser Wind Stones (Twilight Cultist Medallion of Station and Twilight Cultist Ring of Lordship)

**Comment by IvanDanshin** [comment]
Fixed. Thanks for report!
