### ISSUE TITLE
Escort Quest 'Wandering Shay' broken #2845

### ISSUE THREAD

**Issue by nyhotep** [elysium-project/tbc-bug-tracker#1099]
**Summary:** 
Escort quest - the character does not move
**Steps to Reproduce:** 
Find shay leafrunner in north west feralas (near the harpies (38.2, 10.3)). Take the bell from the chest and use it to summon her if she wanders off.
**Expected Results:** 
Escort shay to safety, using the bell if she wanders off (like the sleepy druid quest in darkshore)
**Actual Result:**
shay doesn't move
**Additional Information:**
https://tbcdb.com/?npc=7774
https://tbcdb.com/?quest=2845

**Comment by IvanDanshin** [comment]
Fixed. Thanks for report!
