### ISSUE TITLE
Cannot shoot wand while rooted

### ISSUE THREAD

**Issue by noblecrumpet** [elysium-project/tbc-bug-tracker#1103]
**Summary:** Cannot use the shoot action to fire wand while rooted by ice or netting.

**Steps to Reproduce:** get rooted by a mob, attempt to shoot.

**Expected Results:** Be able to autoattack with a wand.

**Actual Result:** Character moves into shooting animation, then it cancels immediately.

**Additional Information:** Not sure if this applies to bows or thrown weapons; only experienced on mage.

**Comment by IvanDanshin** [comment]
Fixed. Thanks for report!
