### ISSUE TITLE
rescue  from Jaedenar

### ISSUE THREAD

**Issue by nyhotep** [elysium-project/tbc-bug-tracker#1104]
Quest from a strange red key. Escort Arko'narin around cave in felwood to safety

obtain blood red key drop

long escort quest

Arko'narin stays in her cage. She actually runs out to attack nearby mobs, then runs back to the cage.
*Update:*Quest is actually counted as finished. even though you havn't done anything, so the next part can be started.

https://tbcdb.com/?quest=5202 A strange red key
https://tbcdb.com/?item=13140 Blood red key
https://tbcdb.com/?npc=11016 captured Arko'narin

**Comment by IvanDanshin** [comment]
Fixed. Thanks for report!
