### ISSUE TITLE
Bonfire in Bonechewer Ruins gets you out of stealth.

### ISSUE THREAD

**Issue by nastyxx** [elysium-project/tbc-bug-tracker#127]
The Bonfire in Terokkar Forest gets you out of stealth if you come near it without taking any damage of it.

http://db.hellfire-tbc.com/?object=183126

https://imgur.com/a/keC2Bxz

**Comment by nastyxx** [comment]
![2018-06-13_15-04-16](https://user-images.githubusercontent.com/40110640/41352979-36f89f3a-6f1b-11e8-8738-5b754e00e30a.gif)
its probably every Bonfire or Campfire with that problem.

**Comment by polynumerous** [comment]
^^ i have found this problem also,
