### ISSUE TITLE
Solid adamantite chest

### ISSUE THREAD

**Issue by Zizzal** [elysium-project/tbc-bug-tracker#131]
We opened a Solid adamantite chest in The Steamvault which contained a bit too many green items.

https://i.imgur.com/cWLHONZ.png

**Comment by evolve2** [comment]
Please provide more information as to what it should actually be. Just saying 'yo dawg, this is bugged' doesn't help much if the developers need to dig for 2h just to find proper source to justify rewriting the bugged code.
Chest ID: http://db.hellfire-tbc.com/?object=184937 and http://db.hellfire-tbc.com/?object=184941

From what I could find, Solid Adamantite Chests generally contain:
1) Gold
2) 1 Green item or 1 Blue item
3) A buff scroll/HP or MANA potions
4) (OPTIONAL) 1 Green or Blue gem

Proof for such loot table:
(gold, 1 green, scroll, 1 blue gem)  https://youtu.be/L8J3buRz6ZI?t=1m40s
(gold, 1 green, scroll) https://youtu.be/kRBRbxVU4Z8?t=4m17s
(gold, 1 green, scroll) https://youtu.be/VzsoH1-dzIA?t=2m18s
(gold, 1 blue, 5 mana potions, 1 green gem) https://youtu.be/gLTl32lG9sk?t=2m14s
(gold, 1 green, scroll) https://youtu.be/wcshoUOW5VA?t=3m39s
(gold, 1 green, scroll) https://youtu.be/K-t1TlwsRqI?t=2m30s
(gold, 1 blue, scroll, 1 green gem) https://youtu.be/eKcmBEbtFU8?t=1m50s

**Comment by Zizzal** [comment]
Alright I'll try to do better.
