### ISSUE TITLE
Node bug : overlapping nodes

### ISSUE THREAD

**Issue by plastexd** [elysium-project/tbc-bug-tracker#148]
Seen a few times over the zones, overlapping nodes

![wowscrnshot_061418_001227](https://user-images.githubusercontent.com/40170274/41381329-b74a37ec-6f67-11e8-8484-90f53228f4d0.jpg)

**Comment by evolve2** [comment]
Anyone know if they both share a spawn point (can either spawn as 1 or the other) or if they shouldn't have a same spawn point at all?
