### ISSUE TITLE
Vendor: Drake Dealer Hurlunk

### ISSUE THREAD

**Issue by Vathios** [elysium-project/tbc-bug-tracker#171]
Name: Drake Dealer Hurlunk
ID: 23849
Location:  Shadowmoon Valley - Netherwing Ledge

This vendor currently sells no items, Even when Exalted with Netherwing faction.

Items sold should be:

32857
32858
32859
32860
32861
32862

**Comment by Zizzal** [comment]
The faction is not added until patch 2.1.
