### ISSUE TITLE
TBC

### ISSUE THREAD

**Issue by Inart** [elysium-project/tbc-bug-tracker#184]
Path of Defense    def stance,   drop 2%

when you try to climb the Elevator in the thunder bluff crashes game, the character falls and breaks

climb the Elevator in the thunder bluff is not possible, at the end of the rise of the game crashes. 5 times

Horde Trauma it is impossible to pass the quest.   first aid 225 Hord

**Comment by RainElysium** [comment]
Hi there. Can you please resubmit these issues in separate bug reports? We need to be able to assign and label each one properly.
