### ISSUE TITLE
Shadow Labyrinth Doors

### ISSUE THREAD

**Issue by Dragomil** [elysium-project/tbc-bug-tracker#186]
Players can ghost run through the Shadow Labyrinth Doors. It's not meant to be like this.

**Comment by Ziggy-QA** [comment]
**comfirmed**

Able to replicate on current beta build

**Comment by McMittens** [comment]
I couldn't find any information to confirm this. Is this confirmed not blizzlike? How are players getting back into the dungeon if they can't pass through the doors?
It's more likely that the doors are passable while dead, just like the Stratholme back entrance.

**Comment by Ziggy-QA** [comment]
I found information contradicting this

![image](https://user-images.githubusercontent.com/45450044/50451038-c57c3100-08ee-11e9-9e01-8369ea163397.png)
https://wow.gamepedia.com/index.php?title=Shadow_Labyrinth&oldid=1096221
Article Date: 22:48, 31 December 2007

As a result this will be closed.
