### ISSUE TITLE
Dismount Issues

### ISSUE THREAD

**Issue by harropian** [elysium-project/tbc-bug-tracker#189]
Dismounting from a flying mount seems to cause disconnect issues.

 Any action that dismounts you causes you to disconnect. Whether in combat or not, seems if you are not touching the world floor you will dc if you cause an action to dismount.

Normally you should be able to use an action to disconnect and the action would occur and fall damage taken if relevant.

**Comment by ndgallucci32** [comment]
This is for sure an issue. It is not 100% repeatable though. Moving forward at a high distance seems to disconnect right after dismount in the air. About a 20% repeatable situation for me.
