### ISSUE TITLE
Elevator causing disconnect

### ISSUE THREAD

**Issue by ExodusTer** [elysium-project/tbc-bug-tracker#190]
Using the elevator in Thunder Bluff causes you to DC if you move whilst on it. This happened consistently - 7 times in a row in 2 minutes, with no other DCs in an hour.

**Comment by ndgallucci32** [comment]
This may be more of a global evelvator issue. The elevator in Shat to the Aldor section causes a disconnect every time. I am unable to make it to the top of the elevator. Sometimes when I DC and log back on my character is dead.
