### ISSUE TITLE
Server crashes when engaging specific rare-spawn

### ISSUE THREAD

**Issue by Dragomil** [elysium-project/tbc-bug-tracker#194]
3 testers myself included attempted to kill Kraator (http://db.hellfire-tbc.com/?npc=18696) and around 20-30% of his HP left, the server crashed. We tried again and the same problem occured. The server had been stable for many hours before we did the first pull. 

The mob is found in Shadowmoon Valley between Legion Hold & Illidari Point. 

Except for the sudden crashes, the rare-spawn is working as inteded and requires minimum of 3 players.

**Comment by Ziggy-QA** [comment]
I can confirm that this NPC is unstable. All I did was spawn him, and the server crashed.

**Comment by Ziggy-QA** [comment]
Upon checking the crash logs, it seems it was just a very unlikely coincidence.
