### ISSUE TITLE
First Aid quest "Horde Trauma" bugged

### ISSUE THREAD

**Issue by marios75** [elysium-project/tbc-bug-tracker#202]
I can't turn in the quest "Horde Trauma" to the NPC "Doctor Grecory Victor" <Trauma surgeon>

**Comment by marios75** [comment]
> I can't turn in the quest "Horde Trauma" to the NPC "Doctor Grecory Victor"

still the same issue with the quest ''Horde Trauma'' , the NPC does not respond

**Comment by Ziggy-QA** [comment]
This seems to be fixed by the latest hotfix.
