### ISSUE TITLE
Healing item

### ISSUE THREAD

**Issue by HamonTim** [elysium-project/tbc-bug-tracker#204]
All healing items are post 2.3 patch (with 1/3 of the healing power as spell power).
If this server aim to have item progression, the items should be reverted to previous state (will make some boss fight and leveling/questing as healer harder)

Source: http://wowwiki.wikia.com/wiki/Patch_2.3

Healing: Almost all items and enchantments that provide bonus healing now also provide a smaller number (approximately 1/3) of bonus spell damage. There are a few items and enchantments where this was not possible, such as random-stat items and Zul'Gurub enchantments, but this is now the case on virtually all other items.

**Comment by RainElysium** [comment]
Hi there. This is intended as we are running in the final patch of TBC for testing purposes.

**Comment by HamonTim** [comment]
Thanks for the reply.
Is it possible to implement it when all the test are done?
Also if you plan to test some boss (Leotheras come first in my mind), you should also try without the spell dmg on item.
During this fight, 5 players have to kill an npc (that append multiple times) and the spell dmg on healing item made it easier.
