### ISSUE TITLE
Expertise

### ISSUE THREAD

**Issue by HamonTim** [elysium-project/tbc-bug-tracker#205]
Prior to patch 2.3, expertise shouldn't exist. I don't know if it's possible to "removed it" and to have "weapon skill enhancement" like vanilla.

Source: http://wowwiki.wikia.com/wiki/Patch_2.3

All items have had their bonuses to Weapon Skill Rating converted to a new stat called Weapon Expertise Rating. Each point of Weapon Expertise reduces the chance for your attacks to be dodged or parried by .25%.

Weapon Skill: All items and abilities that granted weapon skill have been changed. In most cases, they were converted to expertise or expertise rating. Ranged attacks do not benefit from expertise, so ranged weapon skill has generally been replaced by critical strike bonuses or hit bonuses. In a few cases, talents have been changed to other effects to avoid granting players excessive amounts of expertise.

**Comment by RainElysium** [comment]
Hi there. Server is running in the final state of TBC for the purpose of testing.
