### ISSUE TITLE
Redemption [quest:9600]

### ISSUE THREAD

**Issue by csblizzard93** [elysium-project/tbc-bug-tracker#207]
Cant use [item:9600] on [npc=17542] it keeps telling me out of range. no matter how close or far im away from the body
![wowscrnshot_071118_184925](https://user-images.githubusercontent.com/9687621/42605000-2fc4c03c-853b-11e8-96a5-d86c47d66fb8.jpg)

**Comment by RogueArc** [comment]
Confirmed this also

**Comment by Ziggy-QA** [comment]
Confirmed on PTR

**Comment by Ziggy-QA** [comment]
Fixed
