### ISSUE TITLE
Mongoose not procing in cat form

### ISSUE THREAD

**Issue by milint33w** [elysium-project/tbc-bug-tracker#209]
According to forum posts from 2008, mongoose should proc while shapeshifted, but it does not.

**Comment by RainElysium** [comment]
Confirmed. 

Tested using daggers in cat form - No Mongoose proc
Tested using daggers in non-shapeshift form - Multiple Mongoose proc

**Comment by milint33w** [comment]
I just did more research. According to the release date of wotlk prepatch, and the forum post dates below, it looks like mongoose actually did not work while shapeshifted until the very end of TBC:
https://www.mmo-champion.com/threads/615797-Feral-Druid-Mongoose-Executioner
https://www.mmo-champion.com/threads/618155-Mongoose-proccs-for-Feral-Druids
https://www.mmo-champion.com/threads/638333-Is-mongoose-still-good-for-druid-tanking

Looks like I was wrong again.
