### ISSUE TITLE
Quest The Rune of Summoning (ID: 9619) broken

### ISSUE THREAD

**Issue by CostiAlex** [elysium-project/tbc-bug-tracker#219]
The object **Voidstone** (ID: 181698) in the **Ghostlands** around GPS: 42.8, 19.3 should drop item **Voidstone** (ID: 23732) to begin the quest, but it doesn't.

Source: http://db.hellfire-tbc.com/?quest=9619

**Comment by RainElysium** [comment]
Fixed. However keep in mind its not quest 9619 that was fixed, but 9529's quest reward,
