### ISSUE TITLE
The Lightning Capacitor

### ISSUE THREAD

**Issue by D3viousDom** [elysium-project/tbc-bug-tracker#220]
Reported by Zeo (TBC General-Bugs)

Zeo Today at 4:41 PM
1: Brief summary of what is happening: The Lightning Capacitor is not benefitting from Shaman Talents relating to Lightning Bolt (as it did in 2007)

2: quest/raid mob/item: The Lightning Capacitor

3: Quest/item id if applicable: 28785

4: Steps to reproduce: Use lightning capacitor against a target dummy with no talents, then again against a target dummy with the lightning bolt related talents, and compare results. (Note, damage meters aren't as useful here, as the values will be lumped in with your normal lightning bolt casts since the spell names are identical. It simply has to be watched and noted manually per proc.)

**Comment by McMittens** [comment]
![33](https://user-images.githubusercontent.com/46020700/50525572-94615380-0adc-11e9-9d13-75d8bf2284f3.PNG)
It is not suppossed to profit from shaman talents. If there's any other problem with this trinket feel free to make a new issue.
