### ISSUE TITLE
Netherspite -Netherburn & Void Zones

### ISSUE THREAD

**Issue by D3viousDom** [elysium-project/tbc-bug-tracker#221]
Zeo Today at 7:42 PM
1: Brief summary of what is happening: Not sure if this was already reported, but when I was in the test run, Netherspite was using Nether Burn and Void Zones during his banish phase, which should only happen during his portals phase.

2: quest/raid mob/item: Netherspite

3: Quest/item id if applicable: Netherspite (15689) Nether Burn (30523) Void Zone (unknown ID, multiple matches found and not listed under his abilities in DB)

4: Steps to reproduce: Engage Netherspite and live until he banishes himself for his transition phase (phase 2, 4, 6, etc.) and note the ticking damage that continues to strike all raid members within ~150 yd of the boss, as well as void zones being spawned on players, although these mechanics are supposed to only occur during the portal phase (phase 1, 3, 5, etc.)

**Comment by Ziggy-QA** [comment]
Unable to replicate.
