### ISSUE TITLE
Quest Redeeming the Dead (ID: 9685) broken

### ISSUE THREAD

**Issue by CostiAlex** [elysium-project/tbc-bug-tracker#222]
The quest consists in using **Filled Shimmering Vessel** (ID: 24184) item to resurrect **Blood Knight Stillblade** (ID: 17768) in **Silvermoon** at GPS: 80.1, 59.6 uper floor of the tavern.

After casting the Vessel to the dead body of the Blood Knight nothing happens and the Vessel disapears. I tryed abandoning the quest, but it happens the same thing. It's a paladin quest given by **Knight-Lord Bloodvalor** (ID: 17717).

**Comment by Ziggy-QA** [comment]
Fixed
