### ISSUE TITLE
Heroic Hellfire Ramparts Nazan 

### ISSUE THREAD

**Issue by D3viousDom** [elysium-project/tbc-bug-tracker#226]
Brief summary of what is happening:  Boss Nazan in heroic Hellfire Ramparts' fireball and blaze damages are swapped. 
>Fire damage is up to 4,000-5,000 per fireball and breath attacks. Pools of flame do 1,000-2,000 damage per tick
https://wow.gamepedia.com/Vazruden#Strategy_.28Heroic.29

fireball is doing 1-2k damage and blaze is ticking for 4-5k

2: quest/raid mob/item
Nazan[17536], Fireball[34653]

4: Steps to reproduce
enter heroic Ramparts pull the boss and watch  the combat log.
![nazan](https://user-images.githubusercontent.com/41243405/43613635-ba60957c-9675-11e8-97ab-30d0901d565d.png)

**Comment by IvanDanshin** [comment]
Fixed.
