### ISSUE TITLE
ZA- Doors Behind Hex Lord Malacrass

### ISSUE THREAD

**Issue by D3viousDom** [elysium-project/tbc-bug-tracker#227]
When you go to encounter Hex Lord Malacrass the doors behind him are facing the wrong way. Pictures attached. They are supposed to open only when Hex Lord Malacrass has been defeated. 

![wowscrnshot_080218_165911](https://user-images.githubusercontent.com/41243405/43613704-10ffde60-9676-11e8-810f-2fbf8abbd3d6.jpg)
![wowscrnshot_080218_165947](https://user-images.githubusercontent.com/41243405/43613705-131791fc-9676-11e8-92a1-42163dacc23c.jpg)

**Comment by RainElysium** [comment]
Fixed.
