### ISSUE TITLE
ZA - Lynx Temple Entrance Doors

### ISSUE THREAD

**Issue by D3viousDom** [elysium-project/tbc-bug-tracker#228]
Going to the Lynx Boss the Doors are facing the wrong way exactly like the other ones. 

Screenshot attached. 
![wowscrnshot_080218_171012](https://user-images.githubusercontent.com/41243405/43613982-3ce80cae-9677-11e8-8d70-e0d389eac0f8.jpg)
![wowscrnshot_080218_171128](https://user-images.githubusercontent.com/41243405/43613988-3e51a474-9677-11e8-8a47-14b83fc52e2b.jpg)

**Comment by RainElysium** [comment]
Fixed.
