### ISSUE TITLE
Cursed Talisman quest

### ISSUE THREAD

**Issue by D3viousDom** [elysium-project/tbc-bug-tracker#229]
Pl4ythingToday at 1:09 PM
1: Brief summary of what is happening
Cursed Talisman drop rate is far too low on the quest Cursed Talismans / Ill Omens. Should be 80% drop rate according to Hellfire DB and Twinstar.

2: quest/raid mob/item
Ill Omens [?quest=10483], Cursed Talismasn [?quest=10484]. 

Bleeding Hollow Grunt [?npc=16871]
Bleeding Hollow Dark Shaman  [?npc=16873]
Bleeding Hollow Peon [?npc=16907]
Bleeding Hollow NEcrolyte [?npc=19422]
Bleeding Hollow Tormentor [?npc=19424]

3: Quest/item id if applicable
Cursed Talisman [?item=30157]

4: Steps to reproduce
Kill enemies listed above and be saddened by the drops that don't happen.

**Comment by evolve2** [comment]
Can confirm. 16 kills, 4 drops. Only counted the correct mobs.

**Comment by RainElysium** [comment]
Fixed.
