### ISSUE TITLE
NPC Defias Drone

### ISSUE THREAD

**Issue by Sinidra22** [elysium-project/tbc-bug-tracker#232]
Since this bug involves patrol path bugs for mobs of the same subzone, I will clump the bugs together into 1 report. Mobs can be found in Westfall at around XYZ (-11100.640; 540.534;33.225) (defias drones are nearby on the pier and malformed drone just behind the tower).

Current behaviour - Mobs "Defias Drone" (ID 7050); "Venture Co. Drone (ID 7067) and "Malformed Defias Drone" (ID 7051) do not have a patrol path. 

Correct behaviour - They should patrol around the tower in pairs (defias drone, venture co. drone and malformed defias drone all in a separate group).

Source - Old wowhead databases seem to all share the same static XY coordinates, which is why I did not manage to get an authentic patrol path BUT I did find some descriptions from an old blog and mmo-champion post from 2008 and 2009:

1) Blog - "There are a pair of Defias Drones and two Venture Co. Drones who path around the tower. You will want to do your best to avoid these mobs, as they are apparently quite good at seeing through stealth. They have fairly long paths, so this shouldn't be a huge issue." /.../ "First, you will want to Sap and then Pickpocket the Malformed Defias Drone. He classes as "Humanoid" and not "Undead" despite his looks so Sap works just fine. The [Malformed Defias...] Drone paths around the tower on his own, and catching the other two patrols away from him is just a question of timing. "
(source - https://www.engadget.com/2007/08/02/encrypted-text-the-poison-quest-primer/?guccounter=1 )

2) mmochampion - "She then gives me a quest, Klaven's Tower, which stats to get a key from a patrolling "abomination" by pick pocketing him".
(source - https://www.mmo-champion.com/threads/683164-Need-some-help-with-a-rogue-quest-Not-making-any-sense )
--------------

!BONUS BUG! (Nearby tower from the previous patrol path bug)

Current behaviour - One of the mobs "Defias Tower Patroller" (ID 7052) is not patrolling in the tower, while the other one is patrolling just fine.

Correct behaviour - This can be divided into 2 parts:
1) Patrol path - The bottom patroller is standing still, which is likely incorrect as the other patroller IS patrolling on the upper part of the stairs but the bottom part of the stairs is unguarded.
2) Dialogue - The two Defias Tower Patrollers should speak to each other once their patrol paths link up. From wowwiki it would seem that the bottom patroller is named in the dialogue as "Raven" and the upper patroller  is named "Jill". Dialogue text: http://wowwiki.wikia.com/wiki/Defias_Tower_Patroller

A comment from 2008 claims that once the patrollers paths link up, the lower patroller forces the upper patroller to come near her:
"J: Hey, Raven...
(Other patroller comes running to stand in front of the speaker)"
(source: http://www.wowhead.com/npc=7052/defias-tower-patroller#comments )

**Comment by IvanDanshin** [comment]
Fixed.
