### ISSUE TITLE
Gruul's Lair - High King Maulgar

### ISSUE THREAD

**Issue by D3viousDom** [elysium-project/tbc-bug-tracker#235]
I checked his drops about 10 times. I am pretty sure High King Maulgar should be dropping 2 pieces of T4 and 1 non-Tier Item. 

npc=18831

Loot: Only drops 1 piece of T4 and 1 non-Tier Item from loot table. Should be 2 pieces of T4 and 1 non-Tier Item.

Go into Gruuls Lair and Kill High King Maulgar a few times. Always only drops 1 T4 and 1 non T4.

**Comment by McMittens** [comment]
![24](https://user-images.githubusercontent.com/46020700/50453495-3e0bdd80-0941-11e9-9dd8-8919acfddbff.PNG)
I think it's safe to say he should drop 2 tokens in 2.0.x

**Comment by McMittens** [comment]
I deleted my previous comment since I found it was incorrect.
![24](https://user-images.githubusercontent.com/46020700/50511414-d1eac000-0a8d-11e9-9bde-842c2f67e4fd.PNG)
From the WoWHead comment section of Gruul. Gruul and Maulgar only dropped 1 Token before 2.1
