### ISSUE TITLE
Serpentshrine Cavern- Hydross the Unstable

### ISSUE THREAD

**Issue by D3viousDom** [elysium-project/tbc-bug-tracker#236]
Hydross is performing crushing blows with melee in both water form and poison form.

npc=21932

http://wowwiki.wikia.com/wiki/Hydross_the_Unstable

Screenshot attached. 
![wowscrnshot_080418_162634](https://user-images.githubusercontent.com/41243405/43680576-9786003e-9803-11e8-89f4-21a233ae1bc4.jpg)

**Comment by D3viousDom** [comment]
![wowscrnshot_080418_162506](https://user-images.githubusercontent.com/41243405/43680603-c4728842-9803-11e8-9b29-9f121491045f.jpg)

**Comment by McMittens** [comment]
Confrimed that he crushes, while he shouldnt.
![24](https://user-images.githubusercontent.com/46020700/50537574-ac2eeb00-0b61-11e9-857f-e746c5abc9c4.PNG)

Also the adds do physical damage and he stacks his buff up to 500%. He's only suppossed to go up to 250% before 2.1
His other ability (water tomb and poison dot) need to be checked during intense SSC testing.

**Comment by IvanDanshin** [comment]
Fixed.
