### ISSUE TITLE
Quest "Besieged!"

### ISSUE THREAD

**Issue by Sinidra22** [elysium-project/tbc-bug-tracker#238]
Quest ID - 10562 (Alliance) / 10595 (Horde)

Current behaviour - The objective of this quest is to kill 10 Infernal Attackers but getting the kill counts is kind of awkward due to the kill credit mechanics. In order to get a kill count on Infernal Attackers, you need to do a certain amount of damage (50%+ HP or so). When a quest is specifically designed to make NPC vs NPC fights, the kill credit is quite bothersome to achieve. 
This "bug"/"feature" matters, because currently about half of the Infernals are completely useless and in order to do this quest you need to first kill the weakened Infernals and wait for a fresh respawn to have any hope of getting the kill counted. This is wasteful in both server resources and players' use of time.

Correct behaviour - When I observe retail WoW videos and when looking back to my own WoW retail experience, it does not seem to matter how much damage you deal to mobs who are stuck in NPC vs NPC combat. Rather you just need to do 1-2 hits on mobs and they can already award you with a kill count (I'm not talking about mob tagging for XP).

Source - Both videos are from later expansions but give a good indication of how the kill count mechanic works for this quest.

At :35 a paladin can be seen hitting a low HP mob and still getting the kill count.https://youtu.be/IGmdZQ1F0m4?t=32s

At :06 a DK can be seen AoEing 2 low HP mobs and still getting both kill counts.
https://youtu.be/TFjlm5tsLcA?t=4s

**Comment by Igraina** [comment]
Infernal NPC: http://db.hellfire-tbc.com/?npc=21419
Horde NPC: http://db.hellfire-tbc.com/?npc=21749
Alliance NPC: http://db.hellfire-tbc.com/?npc=21736

**Comment by IvanDanshin** [comment]
Fixed.
