### ISSUE TITLE
Quest "The Summoning Chamber"

### ISSUE THREAD

**Issue by Sinidra22** [elysium-project/tbc-bug-tracker#240]
Quest ID - 10585 (Alliance)

Current behaviour - After player uses the quest item Elemental Displacer (item ID 30672) near the lava pit summoning ritual XYZ (-3350.586, 2118.500, 0.316), an invisible explosion takes place that should kill all of the summoners nearby (the 3 Deathforge Summoners). Currently the explosion does not do any damage to nearby summoners.

Correct behaviour - Explosion should kill any summoners in the area.

Source - https://youtu.be/51qoZJGNayA?t=59s

**Comment by IvanDanshin** [comment]
Fixed.
