### ISSUE TITLE
Quest "Invasion Point: Cataclysm"

### ISSUE THREAD

**Issue by Sinidra22** [elysium-project/tbc-bug-tracker#241]
Quest ID - 10766 (Alliance)
Note - the teleporter mentioned here only works if you have the quest. Otherwise it will not activate.

Current behaviour - When going up to the teleporter XYZ (-3278.766, 2830.013, 123.020) you should be teleported to another spot on the map but the teleporter almost always refuses to work. This is due to the teleporter wanting to use the teleport trigger on me as soon as I move up the stairs of the teleporter. But then, while I'm still moving, it displays an error "Can't do that while moving".

Correct behaviour - Teleport should work regardless of the player moving or not.

Source - Video showing how the teleporter should act. https://youtu.be/Ax_rnCOknQo?t=1m19s

**Comment by IvanDanshin** [comment]
Fixed.
