### ISSUE TITLE
Quest "Teron Gorefiend, I am ..."

### ISSUE THREAD

**Issue by evolve2** [elysium-project/tbc-bug-tracker#245]
Quest ID - 10645 (Alliance)

Small typo in the NPC text "Let the oy:girl go and submit"
Should be according to the player gender "Let the girl go and submit!". 

Picture from in-game https://ibb.co/dzJjWK

Source - quote taken from http://warcraft.blizzplanet.com/blog/comments/world_of_warcraft_burning_crusade___teron_gorefiend

**Comment by RainElysium** [comment]
Fixed.
