### ISSUE TITLE
Druid Epic Flight Form Questline

### ISSUE THREAD

**Issue by evolve2** [elysium-project/tbc-bug-tracker#246]
Starting NPC - 12042
Starting quest - 10955

I am unable to accept the initial quest (10955). The prequisites for this quest are:
- lvl 70 character
- 300 riding

Making a fresh druid did not fix it.
Picture of me trying to find the quest at XYZ (7867.130, -2593.730, 486.920)
https://ibb.co/dDi4Fe

**Comment by Ziggy-QA** [comment]
Came to realize that this quest line is intended for 2.1.0 and as a result this has been marked blizzlike.
