### ISSUE TITLE
SSC- Boss Lady Vashj

### ISSUE THREAD

**Issue by D3viousDom** [elysium-project/tbc-bug-tracker#251]
Pretty sure her HP is incorrect. Posting this to start the thread. We are going to need to check all bosses. 

npc=21212

Health
![wowscrnshot_080818_204009](https://user-images.githubusercontent.com/41243405/44006119-44d05884-9e44-11e8-9bd2-c87880e57cd3.jpg)

**Comment by Ziggy-QA** [comment]
https://tbc-twinhead.twinstar.cz/?npc=21212

According to this her health is 6,737,000

My mobinfo 3.61 addon calculates 7,142,
![image](https://user-images.githubusercontent.com/45450044/49694478-fff07a80-fb47-11e8-8a6e-04d8f05806dd.png)
857

**Comment by Ziggy-QA** [comment]
More boss inconsistancies (Will edit as I find more.

High King Maulgar (Gruuls Lair) Current HP: 758,800 Twinhead HP: 1,264,700

**Comment by Sifern** [comment]
By going to the wow gamepedia wiki, and look into the editing history for 2007/2008 you can find that lady Vashj's health was actually 4,700,000 and not either of the values mentioned above. We can use this method to find the relevant blizzlike HP pool for every boss in TBC.

**Comment by Sifern** [comment]
Using the same method shows that Gruul had ~3,415,000 hp pre 2.43 and about 3,375,000 hitpoints post 2.43. Which means our current HP for Gruul is actually blizzlike.

**Comment by Ziggy-QA** [comment]
@Sifern Smart method, will use from now on.
