### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by Wafhien2** [elysium-project/tbc-bug-tracker#255]
There definitively an issue with mining, i tried to mine many vein(for exemple copper :2055 )  but each time i got the same pattern, i start mining i got one ore, then each time i try to mine again i got this 
![wowscrnshot_082418_162032](https://user-images.githubusercontent.com/35670554/44590177-c8d5a380-a7ba-11e8-8d6e-e6555d392f7a.jpg).

nb; Seems like the rich thorium vein work fine.
nb2: only vanilla vein seems to malfunction

**Comment by McMittens** [comment]
Same issue with herbs https://github.com/elysium-project/tbc-bug-tracker/issues/513

**Comment by TheGreyMouser** [comment]
Same issue, still exist, copper ore, fargodeep mine, probably others as well.
