### ISSUE TITLE
Cenarion war hippogryph (item) (33999)

### ISSUE THREAD

**Issue by Lunastarmaster** [elysium-project/tbc-bug-tracker#264]
This item does not show up on npc (17904) fedreyn swiftspear 
![wowscrnshot_091418_190411](https://user-images.githubusercontent.com/43284098/45579891-0fb23880-b851-11e8-9d0d-65af50b0f774.jpg)
![wowscrnshot_091418_190416](https://user-images.githubusercontent.com/43284098/45579892-117bfc00-b851-11e8-98e5-d214df4fa669.jpg)
![wowscrnshot_091418_190420](https://user-images.githubusercontent.com/43284098/45579893-1345bf80-b851-11e8-82bb-523825152d7b.jpg)
![wowscrnshot_091418_190424](https://user-images.githubusercontent.com/43284098/45579895-1476ec80-b851-11e8-8dc0-cdc864b463e4.jpg)

**Comment by GM-Xavros** [comment]
This item was not added to TBC until 2.3
