### ISSUE TITLE
random cenarion storm crow. npc (22122)

### ISSUE THREAD

**Issue by Lunastarmaster** [elysium-project/tbc-bug-tracker#265]
This guy is just flying above a mushroom randomly.
![wowscrnshot_091418_190729](https://user-images.githubusercontent.com/43284098/45580016-f1007180-b851-11e8-9c90-b930f601f691.jpg)

**Comment by evolve2** [comment]
So post proof that it wasn't doing it on retail. I can write random stuff all day long but if I can't prove it, it's kind of pointless.
