### ISSUE TITLE
missing tabard (npc=18382) (item=31775)

### ISSUE THREAD

**Issue by Lunastarmaster** [elysium-project/tbc-bug-tracker#266]
Sporeggar tabard isn't showing up.
![wowscrnshot_091418_191755](https://user-images.githubusercontent.com/43284098/45580113-0d50de00-b853-11e8-93f1-61e2674d6c02.jpg)

**Comment by McMittens** [comment]
![23](https://user-images.githubusercontent.com/46020700/50525736-ab547580-0add-11e9-8b45-4087131c367e.PNG)
2.1 content.
