### ISSUE TITLE
Unlearning Armorsmithing

### ISSUE THREAD

**Issue by skoo10** [elysium-project/tbc-bug-tracker#271]
Tried to unlearn armorsmithing  from armorsmith trainer in Ironforge. Told it is not available right now. Is this suppose to work? Or To switch to weaponsmith, do I need to drop all of blacksmithing and reskill?

**Comment by Ziggy-QA** [comment]
According to this post https://us.battle.net/forums/en/wow/topic/1020823703 the option became available sometime in 1.11 but was never mentioned in specific patch notes. Fee-based specialization switching only became available in TBC.

**Comment by Ziggy-QA** [comment]
Can confirm this is the case. Tested on PTR 12/2/2018 15:30 GMT

![image](https://user-images.githubusercontent.com/45450044/49406762-ba7d1900-f713-11e8-9950-55adc6d9499e.png)

Seems the quest was updated sometime in 2.0 + to say auberdine, and it's description was mistakenly used.

**Comment by skoo10** [comment]
So pretty much I need to unlearn Blacksmithing entirely and reskill it up correct? If so I take it its best to do this after patch 1.12 drops this week?
"Patch 1.10 (Storms of Azeroth, 28-Mar-2006) introduced the ability for engineers and leatherworkers to switch specializations. The method required was extreme -- unlearn the complete profession and start over from scratch -- but the capability was nevertheless appreciated. A bit later, the same option became available to blacksmiths, though this was never mentioned in any official Blizzard patch notes."
