### ISSUE TITLE
[Quest 10211] City of Light

### ISSUE THREAD

**Issue by ImmortalityDK** [elysium-project/tbc-bug-tracker#274]
When starting the first quest in Shattrah, called City of Light, the servent of Khadgar is suppose to go around explaining about the city and so on, but instead he just follows you around.

**Comment by Thakzi92** [comment]
Crust Buster mob in Hellfire Peninsula is bugged, its not burrowing, just wandering above ground all the time.

**Comment by ImmortalityDK** [comment]
What are you talking about?

I am writing about the quest in Shattrah city, where the servant is suppose to show you around and after the quest, you get the quest to pick Scryer or Aldor side.

Fra: Thakzi92 <notifications@github.com>
Sendt: 9. december 2018 22:36
Til: elysium-project/tbc-bug-tracker <tbc-bug-tracker@noreply.github.com>
Cc: ImmortalityDK <brian.stokholm@outlook.com>; Author <author@noreply.github.com>
Emne: Re: [elysium-project/tbc-bug-tracker] City of Light (#274)


Crust Buster mob in Hellfire Peninsula is bugged, its not burrowing, just wandering above ground all the time.
