### ISSUE TITLE
[Quest - Azuremyst Isle] Red Snapper - Very Tasty! ID 9452 - No Red Snapper

### ISSUE THREAD

**Issue by NoobTaco** [elysium-project/tbc-bug-tracker#276]
**Expected Result** When over one of the pools of bubbling water and clicking the net you should catch a red snapper  and on occasion spawn a murlock that attacks you.

**Actual Results** The net is cast but nothing is looted or spawned.

**Steps**

1. Pick up the quest from the NPC near the river
2. Run to the river and put your character ontop of one of the bubbling pools
3. Click the item in your bag: Item 23654
4. Nothing happens.

I tried 4 pools up and down the river with no luck

**Comment by RogueArc** [comment]
Confirmed this also
(unable to attach screenshot)
