### ISSUE TITLE
[Quest - Azuremyst Isle] Coming of Age (ID 9623) - NPC Dialog

### ISSUE THREAD

**Issue by NoobTaco** [elysium-project/tbc-bug-tracker#278]
**Expected Results** When speaking to Exarch Menelaous and choosing "Where can I find more infected nightstalker runts, Exach?" he should give a little information on where they are found.

**Actual Results** Clicking on the dialog option does not do anything

**Steps**

1. Accept the quest Coming of Age
2. Talk to Exarch Menelous again and chose the dialog option on where can I find more . . .

**Comment by Igraina** [comment]
Exarch: http://db.hellfire-tbc.com/?npc=17116
