### ISSUE TITLE
Fear speed seems faster than it should be

### ISSUE THREAD

**Issue by Sifern** [elysium-project/tbc-bug-tracker#288]
When getting feared by umbrafen mobs in zangarmarsh it felt like my speed got increased by a very large amount(500%ish) fear should increase your speed by a bit, but it's probably not intentional for it to be this fast.

**Comment by Ziggy-QA** [comment]
Comfirmed. Fear speed is not blizzlike

**Comment by Ziggy-QA** [comment]
@Sifern can you tell me the exact mob this happens with? Thanks!

**Comment by Drunkruptor** [comment]
I had a Collapsing Voidwalker in Hellfire do this to me as well.

**Comment by Igraina** [comment]
The fear in Umbrafen comes from Totems (http://db.hellfire-tbc.com/?npc=20455) placed by vitchdoctors (http://db.hellfire-tbc.com/?npc=20115)
Spell: http://db.hellfire-tbc.com/?spell=35198

The voidwalkers (http://db.hellfire-tbc.com/?npc=17014) use a different fear spell (http://db.hellfire-tbc.com/?spell=34259).
