### ISSUE TITLE
[Spell 12536] Mage blizzard spell

### ISSUE THREAD

**Issue by Hunts123** [elysium-project/tbc-bug-tracker#289]
When using the spell Blizzard I get multiple Clear casting proccs when I believe it should only give 1 by chance

**Comment by sanielion** [comment]
Clearcasting procs after any damage spell, meaning its counting every tick for blizzard as different spells, i would say try with arcane missiles  as well to confirm.

**Comment by Ziggy-QA** [comment]
Confirmed. Clearclasting is proccing off of every damage tick of blizzard. This is not blizzlike.

**Comment by Igraina** [comment]
highest rank blizzard: http://db.hellfire-tbc.com/?spell=27085
Clearcast: http://db.hellfire-tbc.com/?spell=12536 (value in the DB is wrong, it's minus 100% mana cost, not 1000)

**Comment by Ziggy-QA** [comment]
Should be fixed
