### ISSUE TITLE
Jewelcrafting: Prospecting doesn't exist.

### ISSUE THREAD

**Issue by ApertureBear** [elysium-project/tbc-bug-tracker#296]
Prospecting should show up as an ability on the General tab of the Spellbook. It's not there.

**Comment by Saltygunner** [comment]
![image](https://user-images.githubusercontent.com/6853303/50046065-c5647180-0062-11e9-8510-7112ef4e35e5.png)

Confirmed

**Comment by Ziggy-QA** [comment]
![image](https://user-images.githubusercontent.com/45450044/50135494-919b6e80-0251-11e9-8b28-6b3542ed3f31.png)

**Comment by Ziggy-QA** [comment]
@ApertureBear Yeah, I have to apologize. Only now getting to the more minor bugs. :P
