### ISSUE TITLE
Protect Kanati Greycloud

### ISSUE THREAD

**Issue by ApertureBear** [elysium-project/tbc-bug-tracker#300]
No mobs spawn for this quest. However, you can turn it in immediately by talking to Kanati Greycloud.

**Comment by ApertureBear** [comment]
Quest is in Thousand Needles, Whitereach Post. Questgiber is Kanati Greycloud, and it's the second part of the Assassination Plot chain started by finding the Assassination Note off the Galak Messenger.

**Comment by Ziggy-QA** [comment]
Should be fixed with today's hotfix.
