### ISSUE TITLE
Mob spawn is too close

### ISSUE THREAD

**Issue by xergio** [elysium-project/tbc-bug-tracker#302]
When we run with a fast mount, the mobs spawn right over you, even the grass have more visual range than the mobs, we should be able to see the mobs at >60y, not at 10. This probably is only a server setting, or a way to maintain the PTR in low load, but it's not right in production.

**Comment by Ziggy-QA** [comment]
Are you talking about the distance that NPC's show up when you walk near their location? You say its too short?

Please respond

**Comment by xergio** [comment]
Yes.

**Comment by xergio** [comment]
One more example: https://streamable.com/0vmjn

Today seems like they spawn at 20y, yesterday was a bit closer

**Comment by Ziggy-QA** [comment]
The visibility distance of NPCs currently coincide with what they are set as (which is 1 yard). Because this is working as intended, I am closing this issue.
