### ISSUE TITLE
A Dip in the Moonwell

### ISSUE THREAD

**Issue by ApertureBear** [elysium-project/tbc-bug-tracker#303]
Using the Robotron Control Unit does not cause the Robotron 3000 to spawn. You still get a channeling bar, but can move freely without interrupting the channel. Quest cannot be completed.  
  
Quest is in Thousand Needles. Questgiver is Wizlo Bearingshiner at Whitereach Post.

**Comment by Ziggy-QA** [comment]
Should be fixed with today's hotfix.

**Comment by Ziggy-QA** [comment]
Not fixed
