### ISSUE TITLE
Quest: The prophecy of Akida

### ISSUE THREAD

**Issue by allerit** [elysium-project/tbc-bug-tracker#308]
Cages with prisoners don't reset and stay open for a long time.

**Comment by McMittens** [comment]
Cages take too much time to close again, captives don't run away and are missing their emotes and voice.

ID's for the cages are 181714 and 181720-181733.
Keys: http://db.hellfire-tbc.com/?item=23801
Video ref: https://www.youtube.com/watch?v=SWvGHgqHNrc

Emotes:
Stillpine Captive growls at its captors.
Stillpine Captive gnaws at the bars of its cage.
Stillpine Captive gnaws rattles its cage.
Stillpine Captive calls for help.
Stillpine Captive whimpers.

/s:
Stillpine Captive says: [Furbolg] Thank you, <name>!
Stillpine Captive says: [Furbolg] The prophecy is true!
Stillpine Captive says: [Furbolg] The Stillpine furbolgs will not soon forget your bravery!
Stillpine Captive says: [Furbolg] Those remaining at Stillpine Hold will welcome you as a hero!
