### ISSUE TITLE
While outdoors i am Still getting Rested XP In Terokkar Forest

### ISSUE THREAD

**Issue by Nacee** [elysium-project/tbc-bug-tracker#310]
While Questing in Terokkar I noticed that my Rested Exp Bar was filling up again after every mob i Killed.

Here's a Screenshot: https://gyazo.com/96a5338015982d744e1781c664894ecc

**Comment by tmpacct** [comment]
This happened to me in Zagramash. When this happened I was also not able to cast my talent-set instant casts while moving. Dont know specific pattern to reproduce it but what I did was to HS -> Elwyn > SW > Class Trainer > Little Chill in SW > Shattrath > Fly to Zangramash

**Comment by Ziggy-QA** [comment]
This is due to a bigger issue regarding rested EXP still applying outside of rested zones until logout.
