### ISSUE TITLE
Ghostlands: mobs not spawning

### ISSUE THREAD

**Issue by Drunkruptor** [elysium-project/tbc-bug-tracker#311]
In Ghostlands to the Southwest of Sanctum of the Sun, South of the road and East of the fork in the road, no mobs are spawning. I think it should be the greater spindlewebs and ghostclaw ravagers, but it definitely shouldn’t be nothing. 

Coordinates around 50,60.  This area has no mob spawns.  Quest mods seem to think at least spiders should be here.

**Comment by Ziggy-QA** [comment]
@Drunkruptor Are you able to provide evidence to this?

Please respond

**Comment by Drunkruptor** [comment]
https://www.wowhead.com/npc=16352/greater-spindleweb is the best I can do for now, which I know isn't TBC specific.  It's possible the mobs were added in this area in a later expansion, which is why quest addons tell you to go there.  It is weird that no mobs spawn in the area, but may be a blizzlike mistake.
