### ISSUE TITLE
Server crashes right after Eye of Kilrogg spell cast.

### ISSUE THREAD

**Issue by tmpacct** [elysium-project/tbc-bug-tracker#312]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
When you cast Eye of Kilrogg, after a few seconds server crashes.

**How to reproduce it (as minimally and precisely as possible)**:
Use Eye of Kilrogg spell (Warlock ability - SpellID: 126)

**Attachment**:
[Video](https://imgur.com/a/DNzpT80)

**Comment by GM-Xavros** [comment]
I was not able to replicate it on cast, but when I dismissed the eye and went back to my body I crashed.
