### ISSUE TITLE
Netherwing questline doesn't work after Hated - Neutral

### ISSUE THREAD

**Issue by tmpacct** [elysium-project/tbc-bug-tracker#313]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
I have completed Netherwing long questline which normally lets us to get through hated to neutral. After that nothing happens. What should happen is; (I have artisan riding skill)

> After completing the Kindness quest chain, Mordenai will be sure you have acquired 300  Artisan Riding skill and have you swear fealty to the Netherwing. This will grant you a Dragonmaw Fel Orc disguise when you enter Netherwing Ledge and allow you to communicate and work for the Dragonmaw stationed there. Mordenai will initially send you to Overlord Mor'ghor with a set of fake papers. Completing this quest will unlock the beginning Dragonmaw quests that you'll be working on to increase your Netherwing reputation. Or, you can try to find as many Netherwing Egg as possible.

Starting quest: Kindness (10804)

Hated to Neutral chain; (works ok)

1. Kindness 
2. Seek Out Neltharaku
3. Neltharaku’s tale 
4. Infiltrating Dragonmaw Fortress 
5. To Netherwing ledge! 
6. The Force of Netharaku 
7. Karynaku 
8. Zuluhed the whacked 
9. Ally of the Netherwing 

After that the following should come; https://www.wowhead.com/guide=658/flying-on-wings-of-nether#netherwing-neutral-to-friendly

**Comment by Ziggy-QA** [comment]
This questline was added in 2.2 As a result this cannot be tested and this issue will be closed.
