### ISSUE TITLE
I work... For the horde!

### ISSUE THREAD

**Issue by OyvindBentaas** [elysium-project/tbc-bug-tracker#335]
When picking up the salvaged wood and metal, i can't pick up any more metal after reaching 8/8 wood.

**Comment by Drunkruptor** [comment]
I was able to complete this quest with no issue on 2 different characters.

**Comment by OyvindBentaas** [comment]
Okay, i had to relog twice before i was able to finish it. 
If you can't reproduce it, I'm sorry for the inconvenience :)

**Comment by ZicoQA** [comment]
I tried reproducing in 2 different chars and the quest went well.

**Comment by Ziggy-QA** [comment]
I'm gonna close this issue because I think this is client side.
