### ISSUE TITLE
Stratholme Issues

### ISSUE THREAD

**Issue by Kzardas** [elysium-project/tbc-bug-tracker#337]
http://db.hellfire-tbc.com/?npc=10390
http://db.hellfire-tbc.com/?object=181085

When you try to click a "supply box" in Stratholme instance for opening it, no action happens, the box seems to be clickable, but does no action on the actual clicking.

What should happen: When you click those boxes either it brokes instantly, and random bugs/rats appear that gives u debuff OR you they don't break and you can loot them for some potions, food, and holy water.

Also the non-elite mobs @Stratholme undead side (the skeletons) are running away in fear when they get to low HP.

What should happen: These mobs are just not running away, they keep attacking until they die.

**Comment by Ziggy-QA** [comment]
This was shown to me by the reporting tester. Confirm 100%

**Comment by ZicoQA** [comment]
- The Unforgiven [NPC 10516] is missing

**Comment by ZicoQA** [comment]
Thuzadin Alcolyte does not attack player and remains paralysed while being attacked.

**Comment by ZicoQA** [comment]
Mindless undead [NPC 11030] and Black Guard Sentry [NPC 10394] only attacked after the reach a waypoint. If player reaches them first he can kill the mobs and the skeletons continue pathing.

**Comment by ZicoQA** [comment]
Ysida Harmon is missing [NPC 16031]

**Comment by IvanDanshin** [comment]
Fixed.
