### ISSUE TITLE
Seargent Bly

### ISSUE THREAD

**Issue by Nicholi417** [elysium-project/tbc-bug-tracker#339]
The group of guys in Zul Farrak are not scripted properly.  None of them help out in the stair fight.  The goblin is not talkable to open the door.  Only Bly attacks when insulted.  The rest of the stair fight is fine.

**Comment by Igraina** [comment]
All the friendly NPCs involved into the event:
Bly: http://db.hellfire-tbc.com/?npc=7604
Goblin: http://db.hellfire-tbc.com/?npc=7607
Rogue: http://db.hellfire-tbc.com/?npc=7605
Priest: http://db.hellfire-tbc.com/?npc=7608
Warlock: http://db.hellfire-tbc.com/?npc=7606

Troll enemies:
Drudge: http://db.hellfire-tbc.com/?npc=7788
Slave: http://db.hellfire-tbc.com/?npc=7787
Cretin: http://db.hellfire-tbc.com/?npc=7789
Nekrum: http://db.hellfire-tbc.com/?npc=7796
Sezz'ziz: http://db.hellfire-tbc.com/?npc=7275

This video from 2007 gives a good idea on how the spawns are and how long the event takes: https://www.youtube.com/watch?v=SF0i6Dt9d0o
And here's a normal run from 2008 (TBC): https://www.youtube.com/watch?v=LdzmZYLrM-k

At the moment the entire group will stay in their cages when freed. Here's a despriction of the event that should be playing.
![23](https://user-images.githubusercontent.com/45959227/50372986-534ada00-05d8-11e9-9589-bb4055a9a047.PNG)
They're suppossed to hearth out after a while, but they don't do this either.
