### ISSUE TITLE
[Spell 12613] Dark Iron Taskmaster

### ISSUE THREAD

**Issue by Nicholi417** [elysium-project/tbc-bug-tracker#341]
The Dark Iron Taskmaster's in Searing Gorge should not be fearing upon death.  That is something not in the original game.

http://db.hellfire-tbc.com/?spell=12613

**Comment by Ziggy-QA** [comment]
This has been verified as blizzlike. According to WoWWiki edit history, this ability was added in 2009.

**Comment by Nicholi417** [comment]
If that was added in 2009, then wouldn't that make is a Wraith of the Lich King add in and not a Burning Crusade one?

**Comment by Ziggy-QA** [comment]
Was a typo. 2007, under talk pages.

**Comment by Nicholi417** [comment]
That makes more sense then.

**Comment by Nicholi417** [comment]
If I find anything else out about this ability can I reply to this, because I don't think this ability was in the game the way it is in this beta.

**Comment by Ziggy-QA** [comment]
This issue has been reopened and confirmed. Upon further investigation, this spell was only meant to effect nearby slaves. It is not meant to effect players in any way. Spell 12613

**Comment by Nicholi417** [comment]
Thank you, I thought it was slightly wrong.
