### ISSUE TITLE
clearcasting procs

### ISSUE THREAD

**Issue by allerit** [elysium-project/tbc-bug-tracker#342]
Clearcasting talent (check at draenei elemental shaman) procs when you cast the spell instead of proccing when this spell hits the target.

In another words: i know that my lightning bolt will crit when i cast is and i already have clearcasting before it crits (however clearcasting correcltly procs only if your spell will crit).

**Comment by Igraina** [comment]
Spell: http://db.hellfire-tbc.com/?spell=16246
