### ISSUE TITLE
[Quest 3441] [NPC 8479]Kalaran Story

### ISSUE THREAD

**Issue by Nicholi417** [elysium-project/tbc-bug-tracker#343]
This quest is in searing gorge is not completing upon listening to the story.
http://db.hellfire-tbc.com/?quest=3441

**Comment by Ziggy-QA** [comment]
Can you please tell me what quest you are speaking of?

Please reply.

**Comment by Ziggy-QA** [comment]
Thank you. Investigating this as we speak

**Comment by Ziggy-QA** [comment]
This has been confirmed as not working as intended. The dialogue option does not show up.
