### ISSUE TITLE
[NPC 22123] [Hunter]Pet learning skills

### ISSUE THREAD

**Issue by Sifern** [elysium-project/tbc-bug-tracker#344]
When I tame a ravager with rank 9 gore (npc=22123) and fight with him, I should learn rank 9 gore so I can teach it to my other ravager who doesn't have it. When going back to my old ravager I haven't obtained the new spell/my trainer doesn't have it either.

**Comment by Ziggy-QA** [comment]
Confirmed.

**Comment by Sifern** [comment]
Yes, I have. Usually (and currently in Vanilla) using it once or twice is consistently enough to proc the effect. I killed 5 monsters well using gore everytime available and still haven't learned it. I'll keep testing!

**Comment by Sifern** [comment]
Sorry for wasting time! After some more testing I was able to get it to work. Possibly the reason it didn't work before is the mobs were level 63, which is over 5 levels lower than me. You can close the issue.

**Comment by Ziggy-QA** [comment]
@Sifern No problem! Thanks for your continued testing and contributions!
