### ISSUE TITLE
 "Each time you land a harmful spell" mechanics not working for dots

### ISSUE THREAD

**Issue by Ziggy-QA** [elysium-project/tbc-bug-tracker#345]
**Observations:** It seems any mechanic relating to  "Each time you land a harmful spell" is not proccing off of DoT's This was tested with Items such as "Wrath of Cenarius" http://db.hellfire-tbc.com/?item=21190 Darkmoon Card: Crusader http://db.hellfire-tbc.com/?item=31856 and the "Spellstrike Infusion" set http://db.hellfire-tbc.com/?itemset=559

**Intended Results:** There are confirmed reports on past comments on WoWhead that these items proc on landing a DoT (But not proccing from DoT damage)

**Comment by IvanDanshin** [comment]
Fixed.
