### ISSUE TITLE
TBC Enslave Demon castable on current level range

### ISSUE THREAD

**Issue by drgreed** [elysium-project/tbc-bug-tracker#346]
As Level 60 Warlock the ability "Enslave Demon" says "Enslaves the target demon, up to level 47..." but it can be cast on the enemy demons in your level range regardless. (I tried on 58, 59).

**Comment by Igraina** [comment]
Spell: http://db.hellfire-tbc.com/?spell=11725
Rank 2 goes up to level 47, but you get rank 3 at level 58 and it goes up to level 62 (http://db.hellfire-tbc.com/?spell=11726)

**Comment by Ziggy-QA** [comment]
I cannot reproduce this issue. Likely WDB
