### ISSUE TITLE
bug quest 

### ISSUE THREAD

**Issue by Davun4u** [elysium-project/tbc-bug-tracker#347]
![dzxneh0wkgm](https://user-images.githubusercontent.com/45742114/49889722-4a793c00-fe53-11e8-9e1d-7dc5a425b812.jpg)

This NPS must run, but he stands still and just waiting for his death)

**Comment by Ziggy-QA** [comment]
Hi there! Can you please tell me the name of this quest please?

Please respond!

**Comment by Davun4u** [comment]
https://vanilla-twinhead.twinstar.cz/?item=12564 
https://vanilla-twinhead.twinstar.cz/?npc=10617
quest DROP! mail
