### ISSUE TITLE
devilsaur pathing

### ISSUE THREAD

**Issue by pichu666** [elysium-project/tbc-bug-tracker#349]
The devilsaurs in Un' goro are not following there set paths they are just standing in place

**Comment by Igraina** [comment]
NPC 1: http://db.hellfire-tbc.com/?npc=6500
NPC 2: http://db.hellfire-tbc.com/?npc=6498
NPC 3: http://db.hellfire-tbc.com/?npc=6499

**Comment by Ziggy-QA** [comment]
Unable to replicate. They are pathing as normal.
