### ISSUE TITLE
Druid Tier 3

### ISSUE THREAD

**Issue by Nicholi417** [elysium-project/tbc-bug-tracker#352]
The druid tier 3 says that the initial cast and ticks of regrowth will increase the target health by 50, the cast does but the ticks don't.

**Comment by Igraina** [comment]
Tested it, works with both the initial cast and the ticks on every rank from 1-9, needs testing for rank 10.

**Comment by Ziggy-QA** [comment]
Hi @Nicholi417, I am unable to reproduce this issue.

This is now closed pending further info.
