### ISSUE TITLE
[Spell 5672] Healing stream totem

### ISSUE THREAD

**Issue by therealDahls** [elysium-project/tbc-bug-tracker#356]
Healing stream totem's visual healing shows healing ticks for a long time after the totem has expiered. Saw party members get +19 for 30 minutes after totem expiered.

**Comment by walkline** [comment]
@therealDahls, @Ziggy-QA  can you help me to reproduce this? As a shaman (without a party) I placed the totem and after 2m totem gone alongside with healing aura. There are some other steps to reproduce?

**Comment by therealDahls** [comment]
Step by step that I did was place healing stream totem, lasts for 45 sec,
but usualy switched to mana stream totem. Me and Ziggy tested yesterday and
was the same. Totem gone and healing was ticking. No visible buff in right
top corner.

-Dahls

18. des. 2018 10:15 a.m. skrev "Anton Popovichenko" <
notifications@github.com>:

@therealDahls <https://github.com/therealDahls>, @Ziggy-QA
<https://github.com/Ziggy-QA> can you help me to reproduce this? As a
shaman (without a party) I placed the totem and after 2m totem gone
alongside with healing aura. There are some other steps to reproduce?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/elysium-project/tbc-bug-tracker/issues/356#issuecomment-448150461>,
or mute the thread

**Comment by therealDahls** [comment]
Step by step that I did was place healing stream totem, lasts for 45 sec,
but usualy switched to mana stream totem. Me and Ziggy tested yesterday and
was the same. Totem gone and healing was ticking. No visible buff in right
top corner.

-Dahls

Den tir. 18. des. 2018, 10:15 skrev Anton Popovichenko <
notifications@github.com:

**Comment by Ziggy-QA** [comment]
I can recall a visible buff being there for me.

But yes, it is exactly how @therealDahls said, @walkline

**Comment by Ziggy-QA** [comment]
Seems since yesterday this has been fixed (?)

**Comment by therealDahls** [comment]
Nice! I can test when im home from work

- Dahls

Den tir. 18. des. 2018, 14:02 skrev Ziggy <notifications@github.com:

**Comment by Ziggy-QA** [comment]
Still happening - often times in dungeons. Cant pinpoint the exact cause

**Comment by Ziggy-QA** [comment]
After speaking with the player who was experiencing this bug, it was discovered that this specific player
had incorrect spells in his spellbook which bugged the totem. After the spells were removed, this issue was resolved.


![](https://cdn.discordapp.com/attachments/524368801190510595/526557693062676500/HST.PNG)
