### ISSUE TITLE
Tunneler's damage (Hellfire Peninsula)

### ISSUE THREAD

**Issue by KatharsisTBC** [elysium-project/tbc-bug-tracker#357]
Hey! I don't know if you've gotten any comments on this, but the mobs "Tunneler" in Hellfire Peninsula appear to have a far greater damage on their "Poison" than what they should. It goes from 800 to 1k damage per hit with a cast time of 1.5s, which makes it really hard to solo a single one without stuns. Being a normal mob, it made me think their damage table is probably off.

**Comment by HamonTim** [comment]
Down voted comment from wowhead: no poison if you're in melee range
![image](https://user-images.githubusercontent.com/38241815/49951731-e6aa4e00-fefa-11e8-8ca3-d62c2221adfb.png)

**Comment by HamonTim** [comment]
https://www.wowhead.com/quest=9355/a-job-for-an-intelligent-man

**Comment by HamonTim** [comment]
![image](https://user-images.githubusercontent.com/38241815/49951813-1fe2be00-fefb-11e8-93a6-696703f38925.png)
