### ISSUE TITLE
Quest: Hypercapacitor Gizmo

### ISSUE THREAD

**Issue by Davun4u** [elysium-project/tbc-bug-tracker#358]
![_brbba5ktt0](https://user-images.githubusercontent.com/45742114/49949588-05164680-ff07-11e8-8194-8db518c46a8e.jpg)
quest  [Hypercapacitor Gizmo]
Nps bg need kill cat =)

**Comment by Igraina** [comment]
Quest: http://db.hellfire-tbc.com/?quest=5151
NPC: http://db.hellfire-tbc.com/?npc=10992

**Comment by Ziggy-QA** [comment]
The creature is untargetable. Confirmed.

**Comment by hujbyka** [comment]
The problem is unchanged
