### ISSUE TITLE
Quest: "A Dip in the Moonwell"

### ISSUE THREAD

**Issue by Davun4u** [elysium-project/tbc-bug-tracker#359]
[A Dip in the Moonwell] (quest)
need fix

**Comment by Ziggy-QA** [comment]
@Davun4u , Can you please tell me the actual bug related to this quest?

"need fix" is not sufficent.

Please respond.

**Comment by Davun4u** [comment]
https://www.youtube.com/watch?v=loAIeZbYC8s 

Here is information about this quest and its proper operation.

**Comment by Igraina** [comment]
Quest: http://db.hellfire-tbc.com/?quest=9433
Item: http://db.hellfire-tbc.com/?item=23675
Interacting with console: http://db.hellfire-tbc.com/?spell=30009
The interaction summons the robot (http://db.hellfire-tbc.com/?npc=17178), which will be under the players direct control (http://db.hellfire-tbc.com/?spell=29989), then you can walk to the moonwell and use the robots ability (http://db.hellfire-tbc.com/?spell=29992) while standing it the water. This will place the quest item (http://db.hellfire-tbc.com/?item=23670) in the players inventory.

**Comment by Ziggy-QA** [comment]
I am closing this issue. Its a duplicate of #303
