### ISSUE TITLE
Logout is instantaneous

### ISSUE THREAD

**Issue by Drunkruptor** [elysium-project/tbc-bug-tracker#361]
Logout does not count down.

**Comment by Ziggy-QA** [comment]
@Drunkruptor ,

Can you tell me the location you were in when you expereinced this bug?

Please Respond.

**Comment by ApertureBear** [comment]
![image](https://user-images.githubusercontent.com/45749087/49983163-f8a5e400-ff2e-11e8-9276-0636ef663e7b.png)
I'm still well-rested here. But if I log out after I log back in (clearing well-rested), it reverts to a 20-second timer.

**Comment by ApertureBear** [comment]
Issue seems to be that well-rested accumulation status is lingering after leaving a well-rested area.

**Comment by ApertureBear** [comment]
![image](https://user-images.githubusercontent.com/45749087/49983200-386ccb80-ff2f-11e8-96ff-77df0b7db567.png)
Logged back in in the same spot, without moving, timer starts.

**Comment by Ziggy-QA** [comment]
Thanks for the detailed information.

It seems that once players enter a "well rested zone" it is not removed until logout.

This seems like it will be an easy fix.

**Comment by Drunkruptor** [comment]
Specifically it's (at least) the well rested/inn buff received at Nesingwary's Expedition.  I don't even know if you're supposed to get that buff at that location, but the buff from the Grom'Gol inn does not linger; the one from Nesingwary does.
