### ISSUE TITLE
Rate of being Dazed seems very high

### ISSUE THREAD

**Issue by ApertureBear** [elysium-project/tbc-bug-tracker#364]
A bit of a colloquial report but it's so frequent it's notable. It's not quite 100% but it's very frequent even against mobs several levels lower.

**Comment by Ziggy-QA** [comment]
All mob creatures have a chance to daze on each melee hit, ranging from 0% to a maximum 40%. Chance to daze is a function of player level, creature weapon skill and player base defense skill. A creature's weapon skill is its level times 5. For example, a level 70 creature has an attack skill of 350. A player's base defense skill is capped at his level times 5, and can be increased through some class talents and gear or other enhancements that have defense rating.

Base chance to daze is 20% given that the mob weapon skill and player defense skill are equal. As the player's defense skill increases relative to the mob's weapon skill, chance to daze decreases to a minimum of zero. As defense skill decreases relative to weapon skill, chance to daze increases to a maximum of 40%. This effectively makes chance to daze a function of level difference - mobs that are below a player's level have less chance to daze, while mobs above his level have a higher chance, with equal level mobs having the base 20% chance.

**Comment by ApertureBear** [comment]
Like I said, it's colloquial, but man did it seem like it was way more often than 20% (or less) against mobs same or lower level. I wasn't running through areas where mobs were 10 levels higher, the mobs in question were 4-5 levels lower than I am.

**Comment by Ziggy-QA** [comment]
@ApertureBear What was your defense level? I tested it on lvl 68 mobs as a level 70, and i was getting dazed on average every 6 hits, translating to 16.666.. (repeating of course)% daze chance. This adds up due to the level difference. Do you remember the monster that was attacking you? they could have an abnormally high weapon skill.

**Comment by ApertureBear** [comment]
Lashtail Raptors. I was 41.

**Comment by Ziggy-QA** [comment]
Hmm, according to the DB, lashtail raptors have an ability called "Lash" that stuns the player for 2 seconds. Could it be this?

**Comment by Ziggy-QA** [comment]
Alright, I'll take a look at the mobs specifically, and if I find anything, I'll re-open the issue. Thanks.

**Comment by Drunkruptor** [comment]
I don't think it's a specific mob.  Doing some testing now with Defense 280 vs. level 38 (weapon skill 190?) mobs still dazing me.

**Comment by Ziggy-QA** [comment]
@Drunkruptor Thank you for the detailed information.

Your tests seem to line up with the sporadic tests that I have also been doing, and there is definitely something not right. As a result this issue will be re-opened and confirmed.
