### ISSUE TITLE
Party Loot not working correctly

### ISSUE THREAD

**Issue by Drunkruptor** [elysium-project/tbc-bug-tracker#365]
When you are far enough away from a party member when they damage a mob, the mob turns gray and you will not be able to get loot even if you are there when the mob is killed.

**Comment by Ziggy-QA** [comment]
Hi there. Are you 100% sure that the mob killed was tagged by a member of your party? And not someone else? Also - How far away exactly were you? Were you far enough away for the party member to not render in the distance?

Please respond.

**Comment by ApertureBear** [comment]
I was the other person in the party. 100% certain I was the one who tagged. Far enough away to not render, yes. Maybe 100 yards?

**Comment by Ziggy-QA** [comment]
@ApertureBear Thank you for the response.

I will investigate this issue.

**Comment by Ziggy-QA** [comment]
Tested. Seems if a mob is out of render distance while tagged by a party member, it will not register as tagged for you. This can be replicated by walking out of render distance while a party member is attacking a mob. This has been confirmed.
