### ISSUE TITLE
Gurubashi Arena broken

### ISSUE THREAD

**Issue by Drunkruptor** [elysium-project/tbc-bug-tracker#367]
Arena does not turn you into pvp; can't attack people.  You can AoE them but it doesn't put you in combat.

**Comment by Ziggy-QA** [comment]
Have you tried other arenas? Or is it JUST the gurubashi arena?

Please respond.

**Comment by ApertureBear** [comment]
We only tried Gurubashi.

**Comment by Ziggy-QA** [comment]
Thank you for your reply.

I will investigate this issue.

**Comment by Ziggy-QA** [comment]
@ApertureBear I am chill :P Chill is my warrior I use to test combat-related issues.
