### ISSUE TITLE
Gurubashi Arena Chest not lootable

### ISSUE THREAD

**Issue by Drunkruptor** [elysium-project/tbc-bug-tracker#368]
Can't loot the chest

**Comment by ApertureBear** [comment]
It says "Invalid target." when right-clicked.

**Comment by Drunkruptor** [comment]
Chest now lootable.  Only had the Arena master trinket and 1 green in it.  I thought it was supposed to have a blue "Arena x of y" item too, though it's possible someone else looted it.  Will check back later
