### ISSUE TITLE
Pet Training

### ISSUE THREAD

**Issue by Nicholi417** [elysium-project/tbc-bug-tracker#369]
I did not get the pet training ability from the guy in Orgrimar and went to do the quest.  The first animal, the Mottled Dire Boar is not tamable for the quest.

**Comment by Ziggy-QA** [comment]
@Nicholi417 Did you try learning from the global class trainer? (Giant guy with the gutiar)

Please respond.

**Comment by Nicholi417** [comment]
Yes.  Since it was not in the list I decided to go try the quest and have to do the taming part just to get the divining rod looking skill that teaches pets their skills.

**Comment by Ziggy-QA** [comment]
This no longer seems to be an issue.
