### ISSUE TITLE
Wall Climbing

### ISSUE THREAD

**Issue by ApertureBear** [elysium-project/tbc-bug-tracker#370]
I jumped up here from below at impossible angles. You can test on any cliff I'm sure but this is Booty Bay.
![image](https://user-images.githubusercontent.com/45749087/49981861-ff7d2880-ff27-11e8-8cab-bb6eff36b88e.png)

**Comment by xergio** [comment]
Yes, this is a huge problem, you can climb any wall with almost < 90º

**Comment by Hunts123** [comment]
I am able to just walk up any mountain literally no jumping needed :/
