### ISSUE TITLE
Booty Bay bank is Broken

### ISSUE THREAD

**Issue by Drunkruptor** [elysium-project/tbc-bug-tracker#372]
![image](https://user-images.githubusercontent.com/45745053/49982638-43b9fa00-ff23-11e8-86b8-f8131d1fee36.png)
You can't add or remove items from bank in BB

**Comment by ApertureBear** [comment]
For reference: Orgimmar and UC banks are working fine. It's only Booty Bay that we've seen.

**Comment by Ziggy-QA** [comment]
Confirmed. Get the error message "Too far away from bank"
