### ISSUE TITLE
Bleeding Hollow Tormentor

### ISSUE THREAD

**Issue by Nicholi417** [elysium-project/tbc-bug-tracker#375]
So these guys, the tormentors, if you have more than one, or possibly just one but that is untested by us, they will fear each other and not us.

**Comment by Igraina** [comment]
NPC: http://db.hellfire-tbc.com/?npc=19424
Spell: http://db.hellfire-tbc.com/?spell=33924

**Comment by Ziggy-QA** [comment]
I was unable to replicate this. I believe this may have been fixed in a previous update.
