### ISSUE TITLE
[NPC 2453]Rare Spawn "Lo'Grosh" in Crushridge Hold, Alterac Mountains is untargetable.

### ISSUE THREAD

**Issue by ApertureBear** [elysium-project/tbc-bug-tracker#378]
He took aoe damage so I was able to kill/loot him. He starts as neutral and only aggros if I hit him with aoe. Consecration was able to kill him but he attacked me while I couldn't target him.

**Comment by Ziggy-QA** [comment]
Confrimed.

**Comment by Drunkruptor** [comment]
Same issue with Kresh in Wailing Caverns.
