### ISSUE TITLE
Quest Arelion's Secret

### ISSUE THREAD

**Issue by Fritzoid** [elysium-project/tbc-bug-tracker#380]
In quest (http://db.hellfire-tbc.com/?quest=10286) 

When you find and talk to the NPC (http://db.hellfire-tbc.com/?npc=20159), he should attack and then turn targetable so you can dps him down to 20% ish, where he gives you the next part.

He attacks, but is never targetable so you cant dps him.

**Comment by IvanDanshin** [comment]
Fixed.
