### ISSUE TITLE
Swimming

### ISSUE THREAD

**Issue by Kiricoco** [elysium-project/tbc-bug-tracker#381]
not sure if we are tracking this but when i went into the water to do a quest in Zang i sunk straight to the bottom an started walking but still had a breath bar and im playing a undead the breath bar still started to go away

**Comment by Saltygunner** [comment]
I just had the exact same issue. I was able to run along the bottom as if I was on land.

**Comment by Ziggy-QA** [comment]
@Kiricoco @Saltygunner We are aware of this issue and fixing it. This issue will be closed due to being a duplicate to #363
