### ISSUE TITLE
Deadmines

### ISSUE THREAD

**Issue by Nicholi417** [elysium-project/tbc-bug-tracker#384]
The Shredder boss in Deadmines does not path.

**Comment by Ziggy-QA** [comment]
Thank you for the report @Nicholi417 
After a quick test I found that the boss was able to path as normal.
Is there anything else you could tell me that may help me reproduce the bug?

**Comment by Nicholi417** [comment]
That is odd, I was in there just to get the minerals and he stood up the ramp and didnt move.  Maybe something fixed it.

**Comment by Ziggy-QA** [comment]
IF your talking about how the boss should patrol around outside of combat but does not, this is true. In that case, I will confirm this pug. The "Pathing" refers to the bosses ability move around at all.

Thank you for your report @Nicholi417 this has been added to the great list of vanilla issues :)

**Comment by AndiestAndy** [comment]
Sneed hasn't been spawning after his Shredder is destroyed. This will also make it impossible to proceed further into DM. Killed with a 68 prot pally doing just melee attacks.

**Comment by MadmanKel** [comment]
I was there, the boss does path a bit and walks around. Once Sneed's Shredder is dead, Sneed does not pop out as he should and I think that is the main problem. Once Sneed is killed, the doors to the rest of the dungeon should open. However, you kill Sneed's Shredder, both the Shredder and Sneed fall dead, and the doors stay closed. I was about to open a ticket myself, but there is one open rn.

**Comment by IvanDanshin** [comment]
Fixed.
