### ISSUE TITLE
Can't Attack to Hated Faction

### ISSUE THREAD

**Issue by tmpacct** [elysium-project/tbc-bug-tracker#385]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
I am Hated with The Scryers but I can't attack to them, I have normal action icons while they were attacking me. Attaching screenshots.
![wowscrnshot_121418_232835](https://user-images.githubusercontent.com/45762346/50026112-cc569a00-fff8-11e8-8ece-52dab86053c4.jpg)
![wowscrnshot_121418_232856](https://user-images.githubusercontent.com/45762346/50026114-cc569a00-fff8-11e8-96c5-511456787b9a.jpg)

**Comment by Ziggy-QA** [comment]
Hi there! Thanks for your report, @tmpacct 

This bug is one of the many to show up in the latest commits, which i believe will be fixed with the next restart (Hopefully). However, I am able to confirm this bug as is.
