### ISSUE TITLE
NPC named Unknown in Area 52

### ISSUE THREAD

**Issue by Gold1310** [elysium-project/tbc-bug-tracker#388]
[npc=20162] Veronia
A blood elf female standing next to the flight master Krexcil [npc=18938] just outside Area 52 in Netherstorm is named 'Unknown'.

**Comment by ZicoQA** [comment]
She appears as Veronia to me.
This is probably a corrupt file you might have picked up from the version you downloaded. Make sure to clear WTF files before joining new servers.
