### ISSUE TITLE
Digging for Prayer Beads [ quest=10916 ]

### ISSUE THREAD

**Issue by Reall3009** [elysium-project/tbc-bug-tracker#390]
Hi, 

Can not continue quest because item=31795 is not available

Thank

**Comment by HamonTim** [comment]
I was able to complete it this week

**Comment by SounDzElysium** [comment]
I too cannot find the cache... I've fed fei fei and followed him 4 times now, no cache appears

**Comment by Ziggy-QA** [comment]
@SounDzElysium Have you tried checking behind the inn?

![image](https://user-images.githubusercontent.com/45450044/50311514-b31f7480-0462-11e9-941b-c3b34b9898eb.png)

**Comment by SounDzElysium** [comment]
@Ziggy-QA yep... like i said, ive fed and followed fei fei 4 times. no mound spawns.
