### ISSUE TITLE
Drop: Sharptalon's Claw

### ISSUE THREAD

**Issue by Davun4u** [elysium-project/tbc-bug-tracker#391]
https://vanilla-twinhead.twinstar.cz/?npc=12676

This mob does not drop the quest
https://vanilla-twinhead.twinstar.cz/?item=16305

**Comment by IvanDanshin** [comment]
https://vanilla-twinhead.twinstar.cz/?quest=6383
First you need to complete quest 6383. It open Sharptalon's Claw quest.
