### ISSUE TITLE
mission to kill turtles 

### ISSUE THREAD

**Issue by Davun4u** [elysium-project/tbc-bug-tracker#392]
quest  [Hardened Shells]

the reason for not completing the quest is simple, yellow turtles cannot be attacked

**Comment by Saltygunner** [comment]
I found the same basic issue - I could not attack neutral mobs after I had accepted a quest for them. I could before, but then they were considered "invalid target" after accepting the quest. this happened to me on Azuremist when trying to do the Moongrazer quest.
