### ISSUE TITLE
Percentage and number health shown at the same time on target

### ISSUE THREAD

**Issue by ApertureBear** [elysium-project/tbc-bug-tracker#396]
![image](https://user-images.githubusercontent.com/45749087/50045696-897edb80-0065-11e9-951e-b5e50d39cc91.png)
I'm pretty sure percentage shouldn't show when I have the status text option marked.

**Comment by ApertureBear** [comment]
![image](https://user-images.githubusercontent.com/45749087/50045761-cf886f00-0066-11e9-9432-e2a82441223a.png)
here's a better picture of the issue

**Comment by Ziggy-QA** [comment]
@ApertureBear this is likely due to an addon. Please disable all addons and tell me if the problem is fixed.

Thanks!
