### ISSUE TITLE
Inconspicuous Landmark for quest Cuergo's Gold does nothing.

### ISSUE THREAD

**Issue by ApertureBear** [elysium-project/tbc-bug-tracker#398]
It also becomes un-interactable after clicking. Should summon a few mobs to fight. This is at Land's End Beach, Tanaris.

**Comment by Igraina** [comment]
Quest: http://db.hellfire-tbc.com/?quest=2882
NPC 1: http://db.hellfire-tbc.com/?npc=7899 with summon: http://db.hellfire-tbc.com/?spell=11463
NPC 2: http://db.hellfire-tbc.com/?npc=7901 with summon: http://db.hellfire-tbc.com/?spell=11487
NPC 3: http://db.hellfire-tbc.com/?npc=7902 with summon: http://db.hellfire-tbc.com/?spell=11485
