### ISSUE TITLE
Boat from Azuremist to Auberdine - stalls, then instantly shows in Auberdine

### ISSUE THREAD

**Issue by Saltygunner** [elysium-project/tbc-bug-tracker#400]
When taking the boat from Azuremist Isle to Auberdine, the boat stops a few seconds after it leaves the Isle, then finally shows instantly in Aubderdine.

**Comment by Ziggy-QA** [comment]
Hi there, thank you for the report!. 
This is related to #360 and has been reported before. as a result this issue will be closed to keep the bug tracker maintained.
