### ISSUE TITLE
Some neutral mobs cant by attacked

### ISSUE THREAD

**Issue by xergio** [elysium-project/tbc-bug-tracker#402]
This moths, or some rays in the middle of Zangarmarsh, cant be killed. I don't remember this in the TBC era: https://i.imgur.com/zMpca9o.png

Other server databases (cmangos-tbc) and the hellfire-tbc database agree with me and consider this mobs elegible to drop the quest item: http://db.hellfire-tbc.com/?npc=18468

**Comment by xergio** [comment]
Edit: this mobs should be killable, we cant complete the quest Strange Energy from Terokkar.

**Comment by therealDahls** [comment]
same goes for netrual enemies in Nagrand, seems to be alot of the yellow enemies around

**Comment by Ziggy-QA** [comment]
This is confirmed, and related to #376 and #367
