### ISSUE TITLE
Mob: Gorishi Egg moves

### ISSUE THREAD

**Issue by Drunkruptor** [elysium-project/tbc-bug-tracker#404]
The Gorishi Egg follows you around once it aggros to you.
![image](https://user-images.githubusercontent.com/45745053/50047402-b9d07500-0079-11e9-9904-307eeb4cf8a6.png)

**Comment by Igraina** [comment]
NPC: http://db.hellfire-tbc.com/?npc=9496
should cast suicide (http://db.hellfire-tbc.com/?spell=7) and then summon (http://db.hellfire-tbc.com/?spell=14206) a grub (http://db.hellfire-tbc.com/?npc=9498).
