### ISSUE TITLE
Mangled Journal repeatedly lootable

### ISSUE THREAD

**Issue by Drunkruptor** [elysium-project/tbc-bug-tracker#406]
Mangled Journal in Un'Goro drops off of mobs even after the quest has been completed.

**Comment by Igraina** [comment]
Journal: http://db.hellfire-tbc.com/?item=11116
Quest: http://db.hellfire-tbc.com/?quest=3884

**Comment by Ziggy-QA** [comment]
Confirmed

**Comment by IvanDanshin** [comment]
Fixed.
