### ISSUE TITLE
Quest: Defiling Uther's Tomb Bugged

### ISSUE THREAD

**Issue by Drunkruptor** [elysium-project/tbc-bug-tracker#407]
When you summon Uther he doesn't do whatever he is supposed to that completes the quest.  Don't mind that there are 2 of him; 2 of us defiled the tomb and spawned him, but he didn't do anything for either of us.
![image](https://user-images.githubusercontent.com/45745053/50048655-9ae0db80-0097-11e9-88aa-06704cc23315.png)

**Comment by Igraina** [comment]
Quest: http://db.hellfire-tbc.com/?quest=9444
Using the Item should instantly complete the quest, spawn Uther, and have him talk a bunch. Here's a referance from 2008: https://www.youtube.com/watch?v=lDynaDtPw6k
