### ISSUE TITLE
Mob emotes are in French?

### ISSUE THREAD

**Issue by ApertureBear** [elysium-project/tbc-bug-tracker#410]
![image](https://user-images.githubusercontent.com/45749087/50058013-7c82ea80-0140-11e9-9330-a2dac3ab0b90.png)

**Comment by ApertureBear** [comment]
Also before the server reset I had my show helm option off. It turned itself on. I assume these may be related.

**Comment by Ziggy-QA** [comment]
¯\_(ツ)_/¯

**Comment by ApertureBear** [comment]
If it's maybe specific to the mob, these were the Burning Blood Grunts in Zeth'Gor, Hellfire Peninsula.

But since it happened at the same time as the helm thing, I'm thinking maybe some default settings went screwy with the reset.
