### ISSUE TITLE
[Quest-Azuremyst Isle] tree's company

### ISSUE THREAD

**Issue by shadlan1** [elysium-project/tbc-bug-tracker#411]
geezle is by the naga flag by default and the tree disguise won't activate the event

**Comment by Igraina** [comment]
Quest: http://db.hellfire-tbc.com/?quest=9531
Item: http://db.hellfire-tbc.com/?item=23792
NPC 1: http://db.hellfire-tbc.com/?npc=17318
NPC 2: http://db.hellfire-tbc.com/?npc=17243
In this Quest you use the disguise in the Traitor's Cove on Silvermyst Isle which activates an event that spawns both NPCs at the edge of the cove, have them walk up to each other and talk. After the dialogue is finished the quest completes and the NPCs leave.

**Comment by Ziggy-QA** [comment]
confirmed

**Comment by IvanDanshin** [comment]
Fixed.
