### ISSUE TITLE
As the crow flies

### ISSUE THREAD

**Issue by Kiricoco** [elysium-project/tbc-bug-tracker#415]
after i finished the quest i didnt turn back into my char i stayed a crow had to log out an back into turn back to normal

**Comment by Kiricoco** [comment]
quest says complete but cant turn in as well

**Comment by Igraina** [comment]
There's also a credit marker NPC for this in the database: http://db.hellfire-tbc.com/?npc=17985

**Comment by DarkAsCanBe** [comment]
![wowscrnshot_010819_013816](https://user-images.githubusercontent.com/46396673/50797528-2b50bb80-12e6-11e9-9517-c2d50664ad73.jpg)
As quest name says 'As the crow flies' - this is how you look after u get bugged :)

**Comment by Dimosphen** [comment]
I have the same problem
![wowscrnshot_012119_201850](https://user-images.githubusercontent.com/46902682/51492358-2f86d980-1dba-11e9-8ab9-c0d0498b5092.jpg)

**Comment by IvanDanshin** [comment]
Fixed.
