### ISSUE TITLE
Quest Have you ever seen one of these?

### ISSUE THREAD

**Issue by Kiricoco** [elysium-project/tbc-bug-tracker#416]
the young murlocs dont leave the cage once you place it on the rock

**Comment by Igraina** [comment]
Quest: http://db.hellfire-tbc.com/?quest=9816
Murloc Cage: http://db.hellfire-tbc.com/?item=24470
The spawned murlocs (http://db.hellfire-tbc.com/?npc=18152) should run away a bunch and start to dance.

**Comment by Ziggy-QA** [comment]
Confirmed

**Comment by PhilosophyOfZen** [comment]
Confirmed here too.
