### ISSUE TITLE
Quest: From the Abyss Broken

### ISSUE THREAD

**Issue by Drunkruptor** [elysium-project/tbc-bug-tracker#417]
Using the Warp Rift Generator does not summon the warp rift or Void Baron Galaxis.

**Comment by Igraina** [comment]
Quest: http://db.hellfire-tbc.com/?item=19024
Rift Generator: http://db.hellfire-tbc.com/?item=29226
Galaxis: http://db.hellfire-tbc.com/?npc=16939

**Comment by Ziggy-QA** [comment]
This quest works as intended. Void Baron Galaxis spawned and I was able to kill him normally.
