### ISSUE TITLE
Arena Master Trinkets don't stack

### ISSUE THREAD

**Issue by Drunkruptor** [elysium-project/tbc-bug-tracker#418]
Not sure if Blizzlike, but on Vanilla server they do stack and right now on TBC they don't.

**Comment by Igraina** [comment]
related Trinkets:
http://db.hellfire-tbc.com/?item=18706
http://db.hellfire-tbc.com/?item=19024

**Comment by Drunkruptor** [comment]
I was referring to http://db.hellfire-tbc.com/?item=18706

**Comment by Ziggy-QA** [comment]
![image](https://user-images.githubusercontent.com/45450044/50430061-0177ad80-087f-11e9-80e2-b19e3602adb4.png)
