### ISSUE TITLE
Avruu's Orb quest bugged

### ISSUE THREAD

**Issue by Kriimaz** [elysium-project/tbc-bug-tracker#419]
After using the Haal'eshi Altar an elemental is supposed to be summoned. The npc is called Aeranas.

**Comment by Igraina** [comment]
Quest: http://db.hellfire-tbc.com/?quest=9418
Aeranas: http://db.hellfire-tbc.com/?npc=17085
After activating the altar Aeranas should spawn and he'll tell you to weaken him. He goes hostile and should revert to friendly at ~20% life, at which point you can turn in the quest.

**Comment by IvanDanshin** [comment]
Fixed.
