### ISSUE TITLE
Natural Remedies (10351) quest bug

### ISSUE THREAD

**Issue by Kriimaz** [elysium-project/tbc-bug-tracker#420]
Earthbinder Galandria Nightbreeze is missing an event after turning in The Earthbinder (10349)

**Comment by Igraina** [comment]
Turning in The Earthbinder (http://db.hellfire-tbc.com/?quest=10349) makes her put out a voice line, walk down the hill and plant the shard into the ground, which summons a Lured Colossus ( http://db.hellfire-tbc.com/?npc=20599). After fighting it she will return to her usual spot and offer the quest Natural Remedies (http://db.hellfire-tbc.com/?quest=10351).

**Comment by IvanDanshin** [comment]
Fixed.
