### ISSUE TITLE
Doorway to the Abyss quest bug

### ISSUE THREAD

**Issue by Kriimaz** [elysium-project/tbc-bug-tracker#422]
When trying to close the burning legion gate it says "Out of range" even when right next to it.

**Comment by Igraina** [comment]
Quest: http://db.hellfire-tbc.com/?quest=10392
the spell that's used for closing the gate (that say's out of range): http://db.hellfire-tbc.com/?spell=35739
and the object you interact with when trying to use the questitem: http://db.hellfire-tbc.com/?object=182935
