### ISSUE TITLE
The Demoniac Scryer Quest Bug

### ISSUE THREAD

**Issue by Kriimaz** [elysium-project/tbc-bug-tracker#423]
After placing the Demoniac Scryer down the mobs start spawning for the event but the event never ends.

**Comment by Igraina** [comment]
Quest: http://db.hellfire-tbc.com/?quest=10838
spawned NPC: http://db.hellfire-tbc.com/?npc=22258
When placing the Scryer an event should start that spawns waves of imps (http://db.hellfire-tbc.com/?npc=22259).
As the event progresses the Scryer also spawns 4 "Suckers" (http://db.hellfire-tbc.com/?npc=22260) that connect to the Scryer with a beam. When the event is finished the Scryer can be talked to for a dialogue option to get the quest item (http://db.hellfire-tbc.com/?item=31607).
The event looks rather fancy with lots of stuff loating around, here's a referance video from 2013: https://www.youtube.com/watch?v=7r2uRTcLdX8

**Comment by DarkAsCanBe** [comment]
Event technically ends with no mobs channeling crystal. Spawns just stop and nothing happens after. Soon crystal disappears and that is it. Quest does not get counted as finished. Nothing happened. Did it 3 times and wasted like 15 mins of my life for that test qq
