### ISSUE TITLE
Pet unable to attack Murkblood Invaders

### ISSUE THREAD

**Issue by Kriimaz** [elysium-project/tbc-bug-tracker#424]
![wowscrnshot_121818_155028](https://user-images.githubusercontent.com/45896647/50134660-d4565880-02dc-11e9-9dba-33f848515c15.jpg)
These Murkblood Invaders are unable to be attacked by my pet, even when they are attacking me my pet still doesnt do anything.

**Comment by Igraina** [comment]
NPC: http://db.hellfire-tbc.com/?npc=18238
