### ISSUE TITLE
Finding the Survivors Quest bug

### ISSUE THREAD

**Issue by Kriimaz** [elysium-project/tbc-bug-tracker#425]
![wowscrnshot_121818_191534](https://user-images.githubusercontent.com/45896647/50144309-9d8f3b00-02fa-11e9-91de-f8596acabcd6.jpg)

After looting a key and using it on a cage, the Mag'har prisoners do not count towards quest completion.

**Comment by Igraina** [comment]
Quest: http://db.hellfire-tbc.com/?quest=9948
Keys: http://db.hellfire-tbc.com/?item=25604
It looks like all the Warmaul Prisons that you can interact with are individual objects, so it needs to be tested, if it doesn't work for any of them. Object numbers are 182484 and all entries from 182486 to 182504, which adds up to 20 individual cages.

**Comment by IvanDanshin** [comment]
Fixed.
