### ISSUE TITLE
Gurok  the Usuruper

### ISSUE THREAD

**Issue by Igraina** [elysium-project/tbc-bug-tracker#427]
NPC: http://db.hellfire-tbc.com/?npc=18182
doesn't use his ability Knock Away (http://db.hellfire-tbc.com/?spell=32959) on pets, might work on player characters.
Related quest: http://db.hellfire-tbc.com/?quest=9853

**Comment by ZicoQA** [comment]
https://www.youtube.com/watch?time_continue=164&v=u8RXLP3yXV0
Working as intended.
Character gets knockback, pet doesn't
