### ISSUE TITLE
Patience and Understanding Quest bug

### ISSUE THREAD

**Issue by Kriimaz** [elysium-project/tbc-bug-tracker#428]
When talking to Sal'saladim and pressing the text, an event does not play therefore making the quest incompletable. 
![wowscrnshot_121818_233827](https://user-images.githubusercontent.com/45896647/50157843-2ec3d900-031e-11e9-95c4-2239725bb4b0.jpg)

**Comment by Igraina** [comment]
Quest: http://db.hellfire-tbc.com/?quest=10004
NPC: http://db.hellfire-tbc.com/?npc=18584
when talking to him, he should go hostile and revert to friendly on low health, completing the quest.

**Comment by McMittens** [comment]
Sal'salabim doesn't attack.

**Comment by IvanDanshin** [comment]
Fixed.
