### ISSUE TITLE
Body of Evidence quest bug

### ISSUE THREAD

**Issue by Kriimaz** [elysium-project/tbc-bug-tracker#429]
When using the Damp Woolen Blanket on the Blazing Warmaul Pyre the Boulderfist Saboteurs spawn for the event but then nothing happens. 
![wowscrnshot_121918_011307](https://user-images.githubusercontent.com/45896647/50163246-c4199a00-032b-11e9-9ce2-92712581afc1.jpg)

**Comment by Igraina** [comment]
Quest: http://db.hellfire-tbc.com/?quest=9932
Boulderfist: http://db.hellfire-tbc.com/?npc=18396
This is actually one of the more enjoyable quests in Nagrand. The Boulderfist Ogres start planting corpses (http://db.hellfire-tbc.com/?npc=18397) around the pyre while having a bit of a chat. I found a comment reciting the dialogue.
![245](https://user-images.githubusercontent.com/45959227/50309820-868a4d80-04a0-11e9-880e-332fd30ff370.PNG)
There are no extra spawns for this quest besides the corpses, the ogres simply need to be defended from the already present mobs.

**Comment by Ziggy-QA** [comment]
Confirmed on PTR

**Comment by IvanDanshin** [comment]
Fixed.
