### ISSUE TITLE
Quest: Escape from Umbrafen

### ISSUE THREAD

**Issue by Igraina** [elysium-project/tbc-bug-tracker#430]
While the escort works, it's missing two spawns of enemies along the path, one in Umbrafen and one at the end of the first bridge.

Quest: http://db.hellfire-tbc.com/?quest=9752
Enemy: http://db.hellfire-tbc.com/?npc=18042

Location 1: X: -926,424, Y: 5335,383, Z: 19,037
Spawn for location 1: X: -916,139, Y: 5358,740, Z: 18,022

Location 2: X: -681,338, Y: 5378,953, Z: 21,975
Spawn for location 2: X: -668,121, Y: 5384,034, Z: 22,386

reference video from 2008: https://www.youtube.com/watch?v=FXZNh27IHl4

**Comment by IvanDanshin** [comment]
Fixed.
