### ISSUE TITLE
Thrall started to attack our tank on GT1

### ISSUE THREAD

**Issue by Tybalth** [elysium-project/tbc-bug-tracker#433]
![image](https://user-images.githubusercontent.com/45772378/50185654-b0186d00-0318-11e9-9a72-000a878f0de8.png)

**Comment by Igraina** [comment]
NPC: http://db.hellfire-tbc.com/?npc=17876

**Comment by Ziggy-QA** [comment]
hi @Tybalth 

Looks like during our second internal test, this did not happen.

Is there any more info you can provide?

**Comment by XIIl** [comment]
I was in this CoT run, and it seems that Thrall started to attack our tank after we attacked the neutral guards patrolling on the road.

**Comment by Ziggy-QA** [comment]
@XIIl Were you alliance or horde?

**Comment by Ziggy-QA** [comment]
I also just tested this with alliance. Maybe some AOE spell damaged thrall? Does anything come to mind? Maybe some other interaction that would cause damage to thrall?

**Comment by XIIl** [comment]
We were Alliance. Yeah that could be, I can not recall exactly if our tank used some sort of AoE. Thanks anyway.
