### ISSUE TITLE
quest=10285 Return to Andormu

### ISSUE THREAD

**Issue by Tybalth** [elysium-project/tbc-bug-tracker#435]
**Summary:** 
The child Andormu does not offer to validate the quest
![image](https://user-images.githubusercontent.com/45772378/50185963-a5aaa300-0319-11e9-8124-cfbc4fdc04d3.png)

**Comment by Igraina** [comment]
An older Andormu is located towards the 2nd dungeon entrance. He's a vendor for ammunition and not supposed to complete this quest.
young Andormu: http://db.hellfire-tbc.com/?npc=20130
older Andormu: http://db.hellfire-tbc.com/?npc=19932 he ends this quest right now.
The quest text indicates that you turn it in to younger Andormu.
![wowscrnshot_121918_095700](https://user-images.githubusercontent.com/45959227/50209594-76754f80-0374-11e9-9af9-fac11d0c185d.jpg)
