### ISSUE TITLE
Cavern of time 1 (Hillsbrad) : Thrall's Pathfinding

### ISSUE THREAD

**Issue by XIIl** [elysium-project/tbc-bug-tracker#436]
**Summary:** The script of the beginning in CoT1 works fine. You can set the houses on fire and then start the escort with Thrall. But as soon as you enter the village with him, the scripts do not work correctly, especially his pathfinding.

**Expected Results:** 
- The mobs should spawn when Thrall exits the buildings. When he exits the barn, when he exits the church, and finally when he exits the house.
- Thrall should leave the house of Taretha (ID 18887) and come fight with the group against the draconids and then against Epoch (ID 18096).

**Actual Result:**
- All the mobs are spawned upon arrival, and are set by default in evade mode since they are targeting Thrall. 
- Once you leave the church, all the draconids spawn at the same time.
- Thrall does not go immediately upstair to see Taretha (ID 18887). 
- Once he gets there, he does not leave the house, and thus let the group fight alone against the boss Epoch Hunter (ID 18096)

**Additional Information:**
Not sure if everything is clear or if I should open several tickets for the different bugs encountered. I am available if more informations are needed.

**Comment by Ziggy-QA** [comment]
Hello @XIIl Thank you for this report>

I will investigate this issue. No need to make multiple reports!

**Comment by Igraina** [comment]
Thrall: http://db.hellfire-tbc.com/?npc=17876
Dragonkin 1: http://db.hellfire-tbc.com/?npc=18172
Dragonkin 2: http://db.hellfire-tbc.com/?npc=18170
Dragonkin 3: http://db.hellfire-tbc.com/?npc=18171
For the Tarren Mill Guardsman there's several entries; some for the ones that are actual guards (http://db.hellfire-tbc.com/?npc=18092) and for the ones that turn into dragons (http://db.hellfire-tbc.com/?npc=20545)

**Comment by Ziggy-QA** [comment]
After an internal testing run of this with the QA team, we found all issues described in this report legitimate.

**Comment by IvanDanshin** [comment]
Fixed.
