### ISSUE TITLE
Runewarden Deryan

### ISSUE THREAD

**Issue by InsanitoTBC** [elysium-project/tbc-bug-tracker#437]
**Summary:** 
I have been playing as a Blood Elf Priest and I have completed a quest called Runewarden Deryan (unfortunately I don't know how to get the IDs). For some reason the quest is still in a quest log as an incomplete quest.
**Steps to Reproduce:** 
Unaware what is meant by this point.
**Expected Results:** 
After accepting and completing the quest it should have been disappeared from the quest log.
**Actual Result:**
The quest still remained there as if it wasn't complete yet.
**Additional Information:**
None that could support the statement.

**Comment by Ziggy-QA** [comment]
Hi @InsanitoTBC I was unable to reproduce this issue.

I suspect it may have something to do with your WDB/WTF folder. Can you try deleting these folders and telling me if it gets fixed? Thank you.

Please Respond

**Comment by Ziggy-QA** [comment]
Since this has not been followed up in 48 hrs, and cannot be reproduced, this issue is closed.
