### ISSUE TITLE
Low Level Health/Mana Regen

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#438]
**Summary:** Health and mana regen for low level blood elf and draenei characters is incredibly low, much lower than on Vanilla

**Steps to Reproduce:** 

**Expected Results:** 

**Actual Result:**

**Additional Information:**

**Comment by Ziggy-QA** [comment]
They seem to be normal for me. If you have any information or references that indicates that the current regen rates are not correct, please do come forward, until then, this issue is closed.
