### ISSUE TITLE
Shatter Talent

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#439]
The Shatter talent in the mage frost tree does not interact with the spell Blizzard. Nearly every other mage spell will have the bonus crit value applied to frozen targets, but Blizzard does not.

**Comment by Ziggy-QA** [comment]
@AndiestAndy Do you know of any documentation/further info that may indicate that this is indeed not blizzlike?

Please respond.

**Comment by AndiestAndy** [comment]
It looks like Blizzard critical strikes only came in Patch 3.0.2. https://wow.gamepedia.com/Blizzard#Patches_and_hotfixes

**Comment by Ziggy-QA** [comment]
Thank you. As this is intended this issue will now be closed. Thank you for your reports regardless.
