### ISSUE TITLE
Bandage Cast Breaks While Shielded

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#441]
If a frost mage has Ice Barrier up and channels a bandage while being attacked, the first attack will break the channel. Bandage casts should only be broken when damage is dealt.

**Comment by Ziggy-QA** [comment]
This has been verfied to not be blizzlike. This will be forwarded to the developers.

**Comment by Ziggy-QA** [comment]
@AndiestAndy after further investigation, we found that this matches the behavior on Vanilla. And since there is no record of this ever being changed in TBC (That i can currently find) More info is needed before we can go through with a change. Thank you for your report regardless.
