### ISSUE TITLE
Blood Elf Bandit

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#444]
The mob Blood Elf Bandit on Azuremyst Isle spawns multiple times in multiple places even though only one  of these mobs is meant to exist on Azuremyst on a time.

**Comment by Ziggy-QA** [comment]
![image](https://user-images.githubusercontent.com/45450044/50427433-38d96080-0865-11e9-90aa-f989a7611450.png)
Confirmed. There are 10 of these that exist at the same time.
And here is evidence this is blizzlike
https://www.wowhead.com/npc=17591/blood-elf-bandit#comments:id=24147

**Comment by Ziggy-QA** [comment]
Fixed as of 12/27/2018
