### ISSUE TITLE
Quest: Matis the Cruel

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#445]
Quest Matis the Cruel cannot be completed. Using the Flare Gun quest item spawns the required mob to capture Matis, but will not actually capture him and the quest cannot be completed.

**Comment by Igraina** [comment]
Quest: http://db.hellfire-tbc.com/?quest=9711
NPC: http://db.hellfire-tbc.com/?npc=17664
Item: http://db.hellfire-tbc.com/?item=24278
