### ISSUE TITLE
Demon Hunter Supplicants

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#449]
The Demon Hunter Supplicant mobs at the top of the Black Temple do not execute their scripts and attack each other. They should attack each other to 50% health, end combat and then return to full health.

**Comment by Igraina** [comment]
NPC: http://db.hellfire-tbc.com/?npc=21179
![22](https://user-images.githubusercontent.com/45959227/50335586-0ef20800-050c-11e9-9ca5-24b55284e453.PNG)
