### ISSUE TITLE
Burstcap Mushrooms

### ISSUE THREAD

**Issue by Igraina** [elysium-project/tbc-bug-tracker#450]
The Burstcap Mushroms (http://db.hellfire-tbc.com/?object=182095) around Zabra'jin in Zangar Marsh don't explode.
**Expected Results:** 
Mushrooms explode on proximity, making it a challange to pick them up for the related quest (http://db.hellfire-tbc.com/?quest=9814).
**Actual Result:**
Mushrooms are lootable but don't react on contact.
**Additional Information:**
Unfortunately I couldn't find any reference for this.

**Comment by Igraina** [comment]
Only "evidence" I can provide is my memory of running into the mushrooms carelessly and triggering the explosion back on retail. Both the quest text and the item description hint that those mushrooms are meant to explode. That quoted comment is kind of curious, so I looked around some more and only found another comment contradicting my memory ...
![23](https://user-images.githubusercontent.com/45959227/50307644-4ecbd780-0499-11e9-8e7f-541f77a042e6.PNG)

**Comment by Ziggy-QA** [comment]
https://www.youtube.com/watch?v=sgNosDJl87U

This video was uploaded on Aug 14, 2013. Reference shows that burstcap mushroom did not explode. Patch on video is unknown.

Continuing to investigate

**Comment by Ziggy-QA** [comment]
@Igraina unfortunately I cannot find anything else that contradicts this. A search of blue posts came up with nothing, and a 2008 snapshot of thottbott also turned up nothing. 

As a result I will be closing this issue. Please comment here again if you find anything that contradicts this and the issue will be put back under investigation. Thanks!
