### ISSUE TITLE
Mob Umbrafen Eel evade when fear by warlock

### ISSUE THREAD

**Issue by Skaelle** [elysium-project/tbc-bug-tracker#451]
**Summary:** 
when the monster Umbrafel Eel (Zangarmarsh) is feared by the warlock, it happens that he comes out of the water and goes evade.
**Steps to Reproduce:** 

**Expected Results:** 
The mob must not come out of the water ?
**Actual Result:**

**Additional Information:**
![wowscrnshot_121918_163052](https://user-images.githubusercontent.com/45874632/50230043-139faa80-03ac-11e9-88d0-c051abbd0e11.jpg)
![wowscrnshot_121918_163030](https://user-images.githubusercontent.com/45874632/50230073-2ca85b80-03ac-11e9-95ea-0be628b3fca7.jpg)

**Comment by Igraina** [comment]
NPC: http://db.hellfire-tbc.com/?npc=18138
