### ISSUE TITLE
Blacksting not dropping questitem "Blacksting's Stinger"

### ISSUE THREAD

**Issue by jim-arbete** [elysium-project/tbc-bug-tracker#454]
**Summary:** 
In zone zangarmarsh

Quest:
[Nothin' Says Lovin' Like a Big Stinger]

**Steps to Reproduce:** 
Tried to kill 3x times, no dropp

**Expected Results:** 
Blacksting's Stinger item to drop
**Actual Result:**

**Additional Information:**

**Comment by Igraina** [comment]
I did that quest yesterday and it dropped normally. Might be fixed after a server restart.

**Comment by Ziggy-QA** [comment]
I believe this is either WDB related or fixed after the WDB update. This issue is closed. Thank you for your report regardless.
