### ISSUE TITLE
Rare Mob Drops

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#456]
When a rare mob is killed, if it has more than one green item to drop, it will drop between 2-3 items.

**Comment by Ziggy-QA** [comment]
Can you please give me some examples of what rare mobs drop multiple green items? And can you provide any evidence that this is not blizzlike?

Please respond

**Comment by AndiestAndy** [comment]
Old world and TBC starter rares like Fenissa the Assassin will drop all of the unique loot in their table.
Here's the evidence it's not Blizzlike:
https://youtu.be/0GpHGsuOm6E?t=162

On the beta, she dropped all over her unique items.

**Comment by Ziggy-QA** [comment]
@AndiestAndy Thank you for providing evidence to this. Once I am able to reproduce this I will forward to the developers.

**Comment by Ziggy-QA** [comment]
This has been confirmed.
