### ISSUE TITLE
Mining Nodes in the World

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#457]
There is a very, very sever deficiency in mining nodes in the old world. Going through several zones will turn up maybe 3 nodes total if there are no caves. There seems to be the right amount in dungeons.

**Comment by Ziggy-QA** [comment]
After a recent restart, this seems to be fixed.

**Comment by ApertureBear** [comment]
Just for the record, this has not been fixed at any point between Christmas 2018 and today. This is a persistent bug which breaks four professions.
