### ISSUE TITLE
Quest : A WARM WELCOME : The last naja Claws we must loot.... don't loot.

### ISSUE THREAD

**Issue by Skaelle** [elysium-project/tbc-bug-tracker#458]
**Summary:** 
For the quest at WARM WELCOME in Zandarmarsh, you have to loot 30 NAJA CLAWS (http://db.hellfire-tbc.com/?item=24280). For the first 29 no problem of drop rate. However for the last, after about 50 mobs, still not loot.
While going to see the quest giver, he has the yellow question mark on his head as if it were validated.

**Steps to Reproduce:** 

**Expected Results:** 

**Actual Result:**

**Additional Information:**
![wowscrnshot_122018_113352](https://user-images.githubusercontent.com/45874632/50279831-29b07800-044b-11e9-9d2e-cac837eb4a54.jpg)

**Comment by Ziggy-QA** [comment]
@Skaelle I was unable to reproduce this bug. I was at 29 naga claws and sucessfully was able to pick another one up making it 30. Is there any additional information you could provide that could help me reproduce this bug?

Please respond

**Comment by Skaelle** [comment]
I started the quest before the update on Monday or Tuesday when you deleted a lot of things (the bags and quest items) maybe I had looted a naja claw he counted but as it was erased it prevented me from having the last one. Will try to do the quest again.

**Comment by Skaelle** [comment]
Ok it works, I just redo the quest and no worries. I think the bug that I had was because of the erasure of a naja claw that I had before the update, the object disappeared but was counted for the quest.

**Comment by Ziggy-QA** [comment]
In that case this will be closed since this issue is no longer happening. Thank you for your report regardless.
