### ISSUE TITLE
quest : NOT ON MY WATCH (nagrand)

### ISSUE THREAD

**Issue by Skaelle** [elysium-project/tbc-bug-tracker#460]
**Summary:** 
http://db.hellfire-tbc.com/?quest=9918 , Lump still agressif
**Steps to Reproduce:** 

**Expected Results:** 
we must interrogate Lump to extract information from him. For that we must attack him and at 30% of his life he becomes friendly and we can talk to him.
**Actual Result:**
Lump does not become friendly and remains aggressive.
**Additional Information:**
![wowscrnshot_122018_154510](https://user-images.githubusercontent.com/45874632/50291479-013a7500-046f-11e9-925f-a37ea712b7bf.jpg)

**Comment by buhhdistmonk** [comment]
Confirmed.  2/14/19 Same issue.  Dragged Lump to the Alliance camp and even guards had no effect.

**Comment by IvanDanshin** [comment]
Fixed.
