### ISSUE TITLE
Shattrath Faction Graveyards in Shadowmoon

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#462]
Dying in eastern Shadowmoon can place the player in the graveyard of the Shattrath faction they are opposing. I do believe that you should appear only in the graveyard of the faction you are friendly with, but I can't find any documentation on that.

**Comment by Igraina** [comment]
I couldn't find any evidence for this either. Both graveyards are far enough away from any guards to safely ressurrect.
![wowscrnshot_122118_105646](https://user-images.githubusercontent.com/45959227/50336997-0996bc80-0510-11e9-8028-04a79507130b.jpg)
![wowscrnshot_122118_110331](https://user-images.githubusercontent.com/45959227/50337004-11eef780-0510-11e9-9967-f58c0f8cd136.jpg)

**Comment by ZicoQA** [comment]
I have not found anything to confirm this. If anyone has further information please come forward. until then I will close this post.
