### ISSUE TITLE
Captain Arathyn

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#463]
Quest mob Captain Arathyn will not move from his starting position once he spawns his hawkstrider mount. He will stand in place, whirlwinding when off cooldown.

**Comment by Igraina** [comment]
NPC: http://db.hellfire-tbc.com/?npc=19635

**Comment by McMittens** [comment]
Arathyn will not move unless forced to (e.g. fear). Wherever he is when fear breaks he will stay,
![24](https://user-images.githubusercontent.com/46020700/50448269-68996e80-0920-11e9-9a0c-e1d2035fdae3.PNG)
If you leave combat he will not properly reset. His summoned mount will despawn, but he will stay where ever he was when the fight ended.
![25](https://user-images.githubusercontent.com/46020700/50448284-82d34c80-0920-11e9-86f0-a75b81ac0de9.PNG)

**Comment by IvanDanshin** [comment]
Fixed.
