### ISSUE TITLE
Quest: Dimensius the All-Devouring

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#464]
When talking to Captain Saeed, he will not present the option to move forward into the Manaforge and Dimensius will not be spawned because of this.

**Comment by Igraina** [comment]
Quest: http://db.hellfire-tbc.com/?quest=10439
Captain Saeed: http://db.hellfire-tbc.com/?npc=20985
Saeeds army consist of 3 Defenders (http://db.hellfire-tbc.com/?npc=20984), 4 Avengers (http://db.hellfire-tbc.com/?npc=21805) and 2 Regenerators (http://db.hellfire-tbc.com/?npc=21783) that await his command in hte camp and follow him around during the quest.

This video shows the entire fight, starting at Captain Saeed: https://www.youtube.com/watch?v=HYuilDCG34Q

**Comment by Ziggy-QA** [comment]
Tested and Confirmed on PTR

**Comment by IvanDanshin** [comment]
Fixed.
