### ISSUE TITLE
Quest The Ring of Blood : The Final Challenge is bugged quest=9977 can't kill Mogor npc=18069

### ISSUE THREAD

**Issue by Tybalth** [elysium-project/tbc-bug-tracker#468]
**Summary:** 
When attacking Mogor, it stay at 1% and absorb every damage.

**Steps to Reproduce:** 
beat it and continue until 1% of life

**Expected Results:** 
He's supposed to die & ressurect to complete the quest

**Actual Result:**
stay alive at 1%

**Additional Information:**
![2018-12-21](https://user-images.githubusercontent.com/45772378/50365031-f7019f00-0572-11e9-9135-a7ef840d4c58.png)

**Comment by Ziggy-QA** [comment]
Hi @Tybalth , this was actually tested by myself a week ago and work fine. Can you please tell me:

How many attempts did you do on him, and did this happen during every attempt?

Did you notice any spell/ability that could trigger it?

Did he eventually die after this happened?

Please respond

**Comment by Ziggy-QA** [comment]
This issue has been closed due to no follow-up

**Comment by McMittens** [comment]
The reported issue still happens, Will take a further look on how to reproduce it.

**Comment by McMittens** [comment]
Happens every time now, He can't be killed after triggering the event. Could this have to do with the fact that he never opens combat after he walks into the arena?

**Comment by IvanDanshin** [comment]
Fixed.
