### ISSUE TITLE
Qu  [Arelion's Mistress]

### ISSUE THREAD

**Issue by Davun4u** [elysium-project/tbc-bug-tracker#471]
not correct work, leaves the Form of the rat, then nothing else happens, according to the idea you should call upon the MOUSE for which the cat will run .. thereby completing the task  
https://www.youtube.com/watch?v=Q3flYqKaJZw

**Comment by Davun4u** [comment]
the NPS also accepts purchased wine, but no reaction to that.

**Comment by McMittens** [comment]
Duplicate https://github.com/elysium-project/tbc-bug-tracker/issues/426
