### ISSUE TITLE
Sandfury Shadowhunter

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#474]
Zul'Farrak mob Sandfury Shadowhunter will spam their spell, Dismounting Blast repeatedly. They should only cast this on mounted players, but will spam it on dismounted players.

**Comment by AndiestAndy** [comment]
I got the mob wrong. It's actually the Sandfury Shadowcaster. Gather up many of them all at once and you'll notice it very clearly. They're not supposed to cast it on dismounted players. I was mashed into a corner continuously.

**Comment by McMittens** [comment]
I can confirm this. The Sandfury Shadowcasters (http://db.hellfire-tbc.com/?npc=5648) use this spell (http://db.hellfire-tbc.com/?spell=18396) throughout the fight every 4-12 seconds and don't check for mounted targets.
![34](https://user-images.githubusercontent.com/46020700/50383224-9330c080-06af-11e9-97ac-d09803276523.PNG)

**Comment by Ziggy-QA** [comment]
on the dev to do list
