### ISSUE TITLE
NPC [Bone Crawler- ] unable to be targeted-stays above ground

### ISSUE THREAD

**Issue by polynumerous** [elysium-project/tbc-bug-tracker#48]
npc untargetable:
![wowscrnshot_061118_161618](https://user-images.githubusercontent.com/40154788/41262065-a87afea2-6d93-11e8-8511-72fc8d69042e.jpg)

note - he does not submerge , just moves around the surface
        - he CAN attack you , but he doesnt engage combat with distance : i entered combat with a *Bonelasher*  that was close to him and he joined combat starting to  hit me->
![wowscrnshot_061118_163017](https://user-images.githubusercontent.com/40154788/41262384-5f6f0134-6d95-11e8-8492-6b512cc2b2fb.jpg)

note- he wont always join combat when fighting beside him though.

**Comment by polynumerous** [comment]
![wowscrnshot_061118_163017](https://user-images.githubusercontent.com/40154788/41262418-924fbda0-6d95-11e8-84ae-1aad1a7fd07f.jpg)

**Comment by Inomares** [comment]
Since it probably uses a similar mechanic, I'll mention that Hellfire Peninsula's Crust Bursters (16844) also likes to either perma-evade or attack you without submerging.

**Comment by polynumerous** [comment]
45.0, 56.3
