### ISSUE TITLE
 [Frankly, It Makes No Sense...] Bug 

### ISSUE THREAD

**Issue by Davun4u** [elysium-project/tbc-bug-tracker#483]
[Frankly, It Makes No Sense...] 
quest does not work
the reason is simple, you can not sit on the scorpion and finish the quest

https://www.youtube.com/watch?v=fsnRujQd1m8 Work

**Comment by McMittens** [comment]
http://db.hellfire-tbc.com/?quest=10672

Game object (http://db.hellfire-tbc.com/?object=185010) is not clickable by players and doesn't prompt to control one of the nearby scorpions (http://db.hellfire-tbc.com/?npc=21909).

**Comment by IvanDanshin** [comment]
Fixed.
