### ISSUE TITLE
 [To Legion Hold]

### ISSUE THREAD

**Issue by Davun4u** [elysium-project/tbc-bug-tracker#485]
Generally does not work Quest item namely [Box o 'Tricks] there is no way to know their plans for quest xD 
![default](https://user-images.githubusercontent.com/45742114/50402482-19c8c900-07a8-11e9-819f-d64c7128c232.png)

**Comment by McMittens** [comment]
http://db.hellfire-tbc.com/?quest=10596
Using the quest item (http://db.hellfire-tbc.com/?item=30638) will always prompt an out of range error message.
Item should be usable around the location of http://db.hellfire-tbc.com/?object=184833 - This object has 2 spawns, for the one in Shadowmoon Valley there's also another object, probably connected to the quest: http://db.hellfire-tbc.com/?object=300112
(X: -3302.490, Y: 2928,760, Z: 170,92 Map: 530)

After using the device there it should spawn Deathbringer Jovaan (http://db.hellfire-tbc.com/?npc=21633), who walks up to the device and starts a conversation with the Image of Warbringer Kazuun (http://db.hellfire-tbc.com/?npc=21502).
Best reference I could find: https://www.youtube.com/watch?v=zAgfemQubUA

**Comment by IvanDanshin** [comment]
Don't understand, it works..
https://i.gyazo.com/c863d08e2d45f2c999849fa98c062a29.mp4

**Comment by IvanDanshin** [comment]
Fixed.
