### ISSUE TITLE
Players have access to Isle of Quel'Danas

### ISSUE THREAD

**Issue by ZicoQA** [elysium-project/tbc-bug-tracker#488]
**Summary:** 
Players have access to Isle of Quel'Danas

**Steps to Reproduce:** 
Flight destination can be taken from Ironforge or Undercity

**Expected Results:** 
Flight destination not show

**Actual Result:**
Flight is shown and gryphon takes you to the island

**Additional Information:**
The Island of Quel'Danas was introduced in 2.4 and as such should have no access to players
This is causing loads of github posts talking about features that are not live (As they are suppose to not be) which are all unnecessary.

**Comment by Ziggy-QA** [comment]
@ZicoQA Can you reference all those unnecessary github posts please?

**Comment by ZicoQA** [comment]
https://github.com/elysium-project/tbc-bug-tracker/issues/487
https://github.com/elysium-project/tbc-bug-tracker/issues/486
https://github.com/elysium-project/tbc-bug-tracker/issues/234
To name a few

**Comment by Ziggy-QA** [comment]
#234 will now be closed. If theres any others please close them aswell. Thanks @ZicoQA !

**Comment by IvanDanshin** [comment]
Fixed.
