### ISSUE TITLE
From the Abyss

### ISSUE THREAD

**Issue by Diebythegun1** [elysium-project/tbc-bug-tracker#494]
Квест работает не правильно, при призыве Galaxis остается летать над пропастью, не выдвигаясь в сторону призыва.

**Comment by McMittens** [comment]
https://github.com/elysium-project/tbc-bug-tracker/issues/417 
This Quest is working, you will see him spawn up ahead of you.
![wowscrnshot_122718_134604](https://user-images.githubusercontent.com/46020700/50480706-e5d6e900-09dd-11e9-8ffb-2a7b1896f459.jpg)
