### ISSUE TITLE
Bladespire ogres not reacting to keg (quest "getting the bladespire tanked" 37, 59 Blade's Edge Mountains)

### ISSUE THREAD

**Issue by miecachu** [elysium-project/tbc-bug-tracker#495]
During quest "getting the Bladespire tanked" the Bladespire ogres do not react/interact with the brew kegs placed in their paths, they actually walked over one.
Blade's Edge Mountains, I was at Bladespire Hold, roughly 39, 58.

**Comment by Ziggy-QA** [comment]
![image](https://user-images.githubusercontent.com/45450044/50492357-61cc3380-09d4-11e9-8af9-1ad085e42191.png)
For reference

This has been confirmed

**Comment by Ziggy-QA** [comment]
![image](https://user-images.githubusercontent.com/45450044/50492420-b66fae80-09d4-11e9-9727-18885c7a6ed0.png)
For reference

This has been confirmed.

**Comment by Ziggy-QA** [comment]
Upon further investigation, and speaking with the original reporter, I have determined that this is an invalid report. The item was used on the wrong ogres. 

Thank you for your report regardless.

**Comment by miecachu** [comment]
![wowscrnshot_122718_205002](https://user-images.githubusercontent.com/46163708/50492680-50594a80-0a19-11e9-9a1e-f254e469bb29.jpg)

**Comment by Ziggy-QA** [comment]
![image](https://user-images.githubusercontent.com/45450044/50493168-06507480-09d9-11e9-8a02-fbaea15b7525.png)
Based on this comment from patch 2.0.6

**Comment by miecachu** [comment]
Aahh this makes it so clear. Thanks!
