### ISSUE TITLE
Rampage ability

### ISSUE THREAD

**Issue by miecachu** [elysium-project/tbc-bug-tracker#502]
**Summary:** 
the issue was made by me a while ago :maximanouz but the issue was not WDB folder related, after deleting the WDB folder the problem was still at hand and the rampage ability does not work on my warrior even after creating another warrior and trying it on that one
**Steps to Reproduce:** 
![wowscrnshot_122918_161022](https://user-images.githubusercontent.com/46163708/50539665-4c960700-0b84-11e9-9e8d-59b49f26c652.jpg)
![wowscrnshot_122918_161026](https://user-images.githubusercontent.com/46163708/50539666-4c960700-0b84-11e9-95c3-2258da3516d5.jpg)
![wowscrnshot_122918_161033](https://user-images.githubusercontent.com/46163708/50539668-4d2e9d80-0b84-11e9-9557-95c15ce5534d.jpg)
after criting a mob try to use the ability rampage rank 2 
**Expected Results:** 
the rage will deplete and the rampage buff will be granted + animations
**Actual Result:**
the rage actually depletes and the rampage animation is there but the buff is nowhere to be found, not in the buff bar or hidden in the stats
**Additional Information:**
Ziggy helped me before with this problem. there is no difference whether the battle stance or beserker stance is used

**Comment by miecachu** [comment]
the screenshots were there in case you needed my talents or stats

**Comment by Ziggy-QA** [comment]
Hi @miecachu . Can you please do the following:

 - Remove all gear, and then try using it
 - Make sure you are using all ranks. (if this is only replicated with 1 rank, do let me know)
 - Try making a horde character, and see if you can still reproduce it
 - Watch the combat log for any indication of its effects.

If there is still a problem, after deleting your WDB and WTF folders, please post here again, as its working fine for me. (and this is not widely reported)

![image](https://user-images.githubusercontent.com/45450044/50541351-0a0f0300-0b61-11e9-9b64-a74044169434.png)

**Comment by ZicoQA** [comment]
I think we need to test more.. with me this spell is working completely the other way. I click it the first time and almost instantly I get 5 buffs of the spell. This is happening in beserk and Battle stance. And happened to me on rank 1 and Rank 2

**Comment by Ziggy-QA** [comment]
@ZicoQA That also seems to be working as intended. You need to hit an enemy repeatedly to make it stack up to 5 times. Please do not re-open tickets that I have closed.

**Comment by miecachu** [comment]
@Ziggy-QA after futher testing it turned out that neither the rank or amount of gear the issue was but the race, my human warrior(s) are unable to use rampage. although in the combat log it does say: Lionsheart gains Rampage but no other indication is given.
