### ISSUE TITLE
Quest "Tomber's Supplies" not working properly

### ISSUE THREAD

**Issue by Khalazhad** [elysium-project/tbc-bug-tracker#507]
I tried to do the quest "Tomber's Supplies" along with another party member. The quest is simple, retrieve an item and bring it back to quest giver. After I looted the item, it never respawned for the other party member to loot it as well. We waited about 15 minutes before giving up.

**Comment by ZicoQA** [comment]
this needs a better respawn timer. will talk to the devs. thanks for reporting guys
