### ISSUE TITLE
Mailbox not sending items

### ISSUE THREAD

**Issue by Khalazhad** [elysium-project/tbc-bug-tracker#508]
I have tried twice now to send myself items through the mailbox. Both times the alt character received the mail, but with no attachments.

**Comment by ZicoQA** [comment]
Couple questions:
What are you trying to send?
Are you using any type of mail addons?
Why are you sending them?
Please be as specific as you can as I have tried to replicate the issue and its working fine on my end.

**Comment by Khalazhad** [comment]
Just replicated it again sending only one stack of Wool just to test it out and still nothing.

**Comment by miecachu** [comment]
I can confirm. I also did receive the mail but no items. 
I send a stack to a friend and he did receive the item. So from my part it's only when sending something to myself on a different char.

**Comment by ZicoQA** [comment]
Yes strangely with me only happened when I sent multiple items.

**Comment by Ziggy-QA** [comment]
This issue is due to a problem with the the "Mail server"

I was unable to produce this problem, however, as its commonly reported, we can go ahead an confirm there are problems happening

**Comment by mantiblades** [comment]
> Couple questions:
> What are you trying to send?
> Are you using any type of mail addons?
> Why are you sending them?
> Please be as specific as you can as I have tried to replicate the issue and its working fine on my end.

This has happened to me 3 times as well.... sent silver rod to mage to further enchantment skill but mail said no attachments sent even though mail subject states I sent it. also 2 other separate items to be disenchanted. I noticed so far it has only been items that were sent one at a time.

**Comment by mantiblades** [comment]
I would like to suggest have your other toon stand at auction house and put items up for auction cheap and logon other toon to purchase. I wish I would have done that with the silver rod cause I can't seem to find the mats needed to make another one. mat drops are extremely rare in this beta even simple cloth drops are far few in between I've only found cloth in treasure chests not on mobs.

**Comment by bandini9** [comment]
I just started to think its might be about characters since i can send my stuff to my alt #964

**Comment by Tolle44** [comment]
![image](https://user-images.githubusercontent.com/3256025/64653659-4486aa80-d427-11e9-85af-62d000c3e2e4.png)
LVl 5 bank char in Orgrimmar, sending to lvl 70 mage in Shat. Items do not appear in mail.

**Comment by bandini9** [comment]
Yup Tolle44 that's exactly what's happening

**Comment by invwax** [comment]
Me and my friend also encounter same problem. One detail  - we check inbox **immediate** after sending. Hope it could help.

**Comment by SUrbli** [comment]
Sent two aces Blessings, only a letter arrived. how to get them back.
[https://dropmefiles.com/awmuS](url)

**Comment by SUrbli** [comment]
Sent two aces Blessings, only a letter arrived. how to get them back.
<a href="https://ibb.co/30qVgjF"><img src="https://i.ibb.co/Q6RhyTH/21322.jpg" alt="21322" border="0"></a>
