### ISSUE TITLE
Stuck in Wizard's Sanctum in Stormwind (portal going out is not working)

### ISSUE THREAD

**Issue by miecachu** [elysium-project/tbc-bug-tracker#509]
After taking the portal from Shattrath to stormwind my character is stuck in the magetower. The 'portal' going outside is not working. 
Relog or exiting the game did not work. 
Heartstone on cd for now so can't retry.

loc. 37, 81 in Stormwind.

**Comment by ZicoQA** [comment]
This has been fixed.
