### ISSUE TITLE
 [Shutting Down Manaforge B'naar] not shutting down when clicking it.

### ISSUE THREAD

**Issue by jim-arbete** [elysium-project/tbc-bug-tracker#511]
**Summary:** 

**Steps to Reproduce:** 
![image](https://user-images.githubusercontent.com/41271891/50550573-4763b580-0c73-11e9-9903-a42bcd57d22f.png)

**Expected Results:** 

**Actual Result:**

**Additional Information:**

**Comment by miecachu** [comment]
I can confirm, no technicians are spawn to repair the console and the quest does not complete.
loc. 23, 68 Netherstorm.
