### ISSUE TITLE
Herb Gathering

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#513]
Certain old world herbs like Gromsblood and Mountain Silversage will not disappear when looted. The lower level ones like Peacebloom and Silverleaf did.

**Comment by McMittens** [comment]
Can you give more detailed information? I tried reproducing this, but the herbs disappeared like they normally would. From which zones did you gather them?

**Comment by AndiestAndy** [comment]
I picked a Gromsblood in the Blasted Lands and it still occurred. [Link](http://puu.sh/Cqjps.jpg) to image. Checking other zones right now.

**Comment by McMittens** [comment]
Thanks! Also, please upload pictures directly into your github post (it's right below the text box).

**Comment by McMittens** [comment]
This Problem persists, but it's random which herbs don't dissappear. Please comment if you have any further information!
