### ISSUE TITLE
Quest "The Stone" not working properly

### ISSUE THREAD

**Issue by Khalazhad** [elysium-project/tbc-bug-tracker#514]
**Summary:** Earlier while leveling in the Ghostlands with my wife, she was doing her Voidwalker quest chain. part of that chain is a quest called The Stone. The objective is to go find and collect a Voidstone. After looting the Voidstone, the quest is supposed to complete and give the next part of the quest chain. However, when attempting to complete the quest, it would instead give an error that said "invalid bag space." She had an almost empty bag at the time and even made space in each bag just to be sure. We even tried again after the next server restart and same result. 

**Additional Information:**
We were in a 2 person party at the time. Looking back, we didn't try to have her complete the quest solo.

**Comment by xPunchfacex** [comment]
Has this been resolved? I have the exact same issue. I posted to the forum and was told to post here, but I don't want to add issues if this is already being looked at.

**Comment by Thalminior** [comment]
this also reported as #649 
also reported as bug #758 
please fix soon

**Comment by Thalminior** [comment]
this issue it appears to be resolved
