### ISSUE TITLE
Swamp Eye Jarl

### ISSUE THREAD

**Issue by Khalazhad** [elysium-project/tbc-bug-tracker#516]
**Summary:** While questing in Dustwallow Marsh I went to Swamp Eye Jarl to complete his quest chain. Both the "Soothing Spices" and "Jarl needs a Blade" quests allowed me to complete them without having the item(s) needed in my bag. I accepted the quest(s) and then turned them in right then and there for free loot and EXP without needing to actually do the work. 

**Additional Information:**
These two quests are the first and last quest in a three quest chain. The 2nd/middle quest worked as usual.

**Comment by McMittens** [comment]
I couldn't find sufficient information if this quest is meant to be available. Currently the quest is instantly completable bc some items are missing from the DB, which is an indication that they where not in before 2.1
Needs further investigation.
