### ISSUE TITLE
Respawn Times on Battered chests 

### ISSUE THREAD

**Issue by Mrzoggy** [elysium-project/tbc-bug-tracker#519]
**Summary:**
Looted chest at 35,59 at Noon on 12/31/18. Chest de-spawned as it should. Returned on 1/1/19 @ 8:30 am and chest had not re-spawned. 
**Steps to Reproduce:** 
Loot chest at 35,59
**Expected Results:** 
Re-spawn after 5 hours
**Actual Result:**
No Re-spawn after 20+ hours
**Additional Information:**

**Comment by McMittens** [comment]
Thank you for your report! Can you state the zone you encountered this in?
