### ISSUE TITLE
Corrupted Ashbringer Combat Bug

### ISSUE THREAD

**Issue by PhilosophyOfZen** [elysium-project/tbc-bug-tracker#521]
**Summary:** 
Corrupted Ashbringer causes hostile targets to randomly enter combat while within approximately 25 yards of the character wielding it. It causes rogues to lose stealth and succubi to become visible, among other things.

**Steps to Reproduce:** 
Have player 1 equip Corrupted Ashbringer and player 2 start a duel with them. Player 2 will enter combat randomly while near player 1 even though no hostile action has been taken. Player 2, if a rogue, will also lose stealth.

**Expected Results:** 
Player 2 should not enter combat.

**Actual Result:**
Player 2 will be put into combat.

**Additional Information:**

**Comment by Ziggy-QA** [comment]
@PhilosophyOfZen Did you notice any effects in your combat log caused by corrupted ashbringer?

**Comment by PhilosophyOfZen** [comment]
I did not, but if I can get a volunteer I can attempt to reproduce this and see.

**Comment by Ziggy-QA** [comment]
Tested and confirmed.

**Comment by Ziggy-QA** [comment]
Some additional information: Corrupted ashbringer will also aggro mobs with its effect.

**Comment by PhilosophyOfZen** [comment]
Additional Information:
Nothing shows up in the combat log. When in pvp, it puts both the wielder and any hostile pvp target within about 20-25 yards into combat.

**Comment by PhilosophyOfZen** [comment]
***Additional Thought:***
I don't know if this has been fixed yet, but it occurred to me that wielding Corrupted Ashbringer in Scarlet Monastery produces an event. Scarlet Crusade mobs within a certain distance will kneel toward the wielder and Commander Mograine goes through a whole sequence/cut-scene-ish type deal.

I would bet that something in the aura effect for the SM event is the cause of this bug.
