### ISSUE TITLE
 [There Can Be Only One Response]

### ISSUE THREAD

**Issue by Davun4u** [elysium-project/tbc-bug-tracker#526]
after killing monsters, the soul must open the portal, after which kill the boss and do the quest, the souls do not open the party ... Quest do not succeed
https://www.youtube.com/watch?v=aepKdY_Y1jY

**Comment by kolgarlol** [comment]
ya, quest dont works

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
