### ISSUE TITLE
Terokkar Forest: "Torgos!" quest: Torgos is already flying around but does not want to land.

### ISSUE THREAD

**Issue by miecachu** [elysium-project/tbc-bug-tracker#528]
The Torgos! quest in Terokkar Forest asks you to * Call down Torgos with Trachela's Carcass* but upon arrival Torgos is already spawned, without use of the quest item. But he does not want to land not even when using the quest item (the carcass of Trachela). The carcass just disappears and Torgos keeps flying circles.
The quest cannot be completed.

Loc.  27, 55 in Terokkar Forest.

**Comment by McMittens** [comment]
The item[30618] is suppose to call Torgos[18707] down.
