### ISSUE TITLE
Quest: "They're alive! Maybe..."

### ISSUE THREAD

**Issue by nyhotep** [elysium-project/tbc-bug-tracker#533]
**Summary:** 
Spiderwebbed creatures (objective of quest 9670 They're Alive! Maybe... are able to move towards player when attacked. (Bloodmyst isle)
**Steps to Reproduce:** 
Attack a cocooned creature at range
**Expected Results:** 
Creature or drenai prisoner is trapped until released 
**Actual Result:**
Cocooned mob heads towards the attacker, even though it is supposed to be immobilised.
**Additional Information:**
Does not affect the quest; cosmetic/ immersion only.

**Comment by McMittens** [comment]
http://db.hellfire-tbc.com/?npc=17680 Should be immobile at all times.

**Comment by McMittens** [comment]
Summary of the other issue:
Cocoons[17680] are spawning the wrong creatures upon death.
For the spawns I couldn't find a source that gave the exact spawns, I rather found some comments on WoWHead that suggest these spawns are blizzlike:
![24](https://user-images.githubusercontent.com/46020700/53444220-dd1a8780-3a0d-11e9-8716-6ec92d31585a.PNG)
If there's any info on specific spawns that are wrong please post the source here.
