### ISSUE TITLE
Quest: Are We There, Yeti?

### ISSUE THREAD

**Issue by Khalazhad** [elysium-project/tbc-bug-tracker#534]
**Summary:** During the final part of the "Are We There, Yeti?" where one must scare the 3 goblins by summoning the mechanical yeti, I found that although it registered that I had scared the NPC's, they did not react as though I had. When the goblins "see" the mechanical yeti they're supposed to run away from it and say some dialogue. None of that happened. While this bug is not game breaking at all, it does break immersion.

**Comment by McMittens** [comment]
Quest: http://db.hellfire-tbc.com/?quest=5163
Using the quest item makes each goblin run around a specific path, basically going around the camp their in and then returning to their usual spot.

Legacki: http://db.hellfire-tbc.com/?npc=10978
![24](https://user-images.githubusercontent.com/46020700/50698602-a5164a00-1045-11e9-8931-a1da9abdef38.PNG)

Sprinkle: http://db.hellfire-tbc.com/?npc=7583
What should happen when using the quest item near Sprinkle:
Umi's Mechanical Yeti marches around, roaring and making a ruckus.
Umi's Mechanical Yeti: RAAAAAAAR!
Sprinkle jumps in fright.
(starts running away)
Sprinkle: Ahhhh!!! What is that thing?!
(after returning)
Sprinkle: Umi sent you, didn't she?! She told me to expect a surprise, but I never thought that this is what she meant!

Quixxil: http://db.hellfire-tbc.com/?npc=10977
What should happen when using the quest item near Quixxil:
Umi's Mechanical Yeti marches around, roaring and making a ruckus.
Umi's Mechanical Yeti: RAAAAAAAR!
Quixxil jumps in fright.
(starts running away)
Quixxil: Why do you chase me, Mechanical Yeti? WHY?
