### ISSUE TITLE
Prophecy of Akida

### ISSUE THREAD

**Issue by Folwar96** [elysium-project/tbc-bug-tracker#539]
**Summary:** 
Bristlelimb cages in bristlelimb village respawn in a very long time, the prisoners in the cages don't even escape the cage after it gets opened. I came here and found 8 opened cages with prisoners inside. I have waited for 20 mins, found other 7 cages to open, waited another 20 minutes and not even one of the original opened cages has respawned. No interactions (emotes or speak) with the Capitives.

**Steps to Reproduce:** 
Get at Bristlelimb village with Prophecy of Akida in the quest log, get bristlelimb keys by killing furbolgs, open the cages and wait.

**Expected Results:** 
https://youtu.be/sMtG2CBMYwA?t=205
Stillpine capitive escapes, eventually after saying something, and the cage respawns with a new capitive in a reasonable time.

**Actual Result:**
There is no interaction with the capitives, they don't escape and the cages seem to take ages to respawn. This happened to every one of the 7 cages i did open.

**Additional Information:**
The opened cages have no collision.

**Comment by Ziggy-QA** [comment]
#308 Duplicate
