### ISSUE TITLE
Nagrand, Throne of the Elements.

### ISSUE THREAD

**Issue by thk88** [elysium-project/tbc-bug-tracker#54]
When you swim up there, you get to a point where you can start running in the water. It's not possible to mount though, cause it says you're still swimming. Once you get on land, you are able to mount as normal.
If you then walk out into the low water where you couldn't mount (coming from the land), it's now possible to mount, where it was otherwise telling "Cannot use while swimming".

**Comment by AntilaT** [comment]
This seems to be true for all bodies of water based on my experience so far.

**Comment by thk88** [comment]
is it expected behaviour?

**Comment by AntilaT** [comment]
No it's not. You should be able to mount when you are in a water so shallow that your feet touch the ground
