### ISSUE TITLE
NPC Crowd Control Diminishing Returns

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#541]
Enemy NPCs do not appear subject to CC diminishing returns or at least stuns. I fought Exarch Maladaar as a paladin and his summoned mobs chain stunned me with Hammer of Justice with absolutely no diminishing returns. [Wiki says](https://wow.gamepedia.com/Diminishing_returns#In_PvE) that NPCs are subject to a different DR rule than players, but they should not be capable of chain stunning like they did. A three second stun was constantly refreshed by three mobs. This should not be possible.

**Comment by ZicoQA** [comment]
This NPC is not supposed to have DR. It is a mechanic of the fight that the NPC can only cast one spell for each class it takes. So depending on the class, that spell will be spamed on the player. 
The reason for not having DR on this fight is, the idea of the fight that you have to focus the stolen souls. they have the same hp as you when they spawn and if attack by everyone in group should die after 1 or 2 hits. 
It's part of the difficulty of the fight that he stunlocks a palading.

I am closing this ticket and it will be reopen in case someone reports of another npc that is not causing a similar issue.
