### ISSUE TITLE
Npc Kirrik the Awakened does not stop walking when talked to.

### ISSUE THREAD

**Issue by miecachu** [elysium-project/tbc-bug-tracker#545]
NPC Kirrik the Awakened in Terrokar Forest (patrols at the refugee caravan loc. 37, 50) 
Does not stop patrolling when you talk to him, it makes completing quests and accepting them a tad challenging sometimes.

I see this has already been reported (#94) but also closed, it may therefore be worth reporting again?

**Comment by ZicoQA** [comment]
To be honest, its easier for organizing purposes if you had commented on the closed issue and we would have reopen it if needed. 

This is working for me. I am able to stop him whenever I talk to him, even when he changes to bear.
