### ISSUE TITLE
Rogues Can't Train Rank 1 Instant Poison

### ISSUE THREAD

**Issue by PhilosophyOfZen** [elysium-project/tbc-bug-tracker#547]
**Summary:** 
This is test realm specific. Rogues cannot train rank 1 instant poison and hence cannot train later instant poisons.

**Comment by McMittens** [comment]
Spell ID for rank 1 is 8681

**Comment by AndiestAndy** [comment]
I managed to get it after completing the quest, but on the Alliance side.

**Comment by McMittens** [comment]
Since this issue is PTR specific I will close it, if any problem with the alliance or horde poison quest chain arises please open a new issue.

**Comment by PhilosophyOfZen** [comment]
Ty McMittens. The quest chain is long and tedious. For testing purposes it's simply a bit inconvenient. I think warriors have a similar issue with intercept (it is gotten via a level 30 quest iirc).
