### ISSUE TITLE
NPC Brumman Alliance

### ISSUE THREAD

**Issue by jeeb73** [elysium-project/tbc-bug-tracker#553]
**This NPC (Honor horde) is not detected as Profession Trainer in minimap:**

**Comment by McMittens** [comment]
This is true for all profession trainers in Honor Hold:

LW: http://db.hellfire-tbc.com/?npc=18771
Skinning: http://db.hellfire-tbc.com/?npc=18777
Ench: http://db.hellfire-tbc.com/?npc=18773
Alch: http://db.hellfire-tbc.com/?npc=18802
Herbs: http://db.hellfire-tbc.com/?npc=18776
Jewelcrafting: http://db.hellfire-tbc.com/?npc=18774
BS: http://db.hellfire-tbc.com/?npc=16823
Mining: http://db.hellfire-tbc.com/?npc=18779
Tailor: http://db.hellfire-tbc.com/?npc=18772
Cooking: http://db.hellfire-tbc.com/?npc=18987
