### ISSUE TITLE
The Earthbinder quest not working

### ISSUE THREAD

**Issue by DarkAsCanBe** [elysium-project/tbc-bug-tracker#556]
**Summary:** 
Quest can not be turned in after it is marked as complete.

**Steps to Reproduce:** 
Obtain item [Crimson Crystal Shard] from Colossus and bring it to Earthbinder Galandria.

**Expected Results:** 
NPC talks to you and you turn the quest in.

**Actual Result:**
With quest marked as complete and q item in your bag you can't talk to NPC and thus can't finish quest.

**Additional Information:**
![wowscrnshot_011019_033811](https://user-images.githubusercontent.com/46396673/50938425-342dc280-1489-11e9-9d7e-33a86e67a8b5.jpg)

**Comment by McMittens** [comment]
Thank you for your report! This quest used to work, it might be that it glitches out once it gets turned in, since the NPC is missing a script. Will further investigate after the next server restart.

**Comment by McMittens** [comment]
Questgiver doesn't respond after the first turn-in.

**Comment by McMittens** [comment]
https://github.com/elysium-project/tbc-bug-tracker/issues/420
