### ISSUE TITLE
Quest “Unexpected Results”

### ISSUE THREAD

**Issue by Kaghol** [elysium-project/tbc-bug-tracker#557]
**Summary:** Quest at East Sanctum in Eversong Woods “Unexpected Results”. The Scourge appear then pull back. Able to attack and kill but quest doesn’t complete.

**Steps to Reproduce:** Accept quest from Apprentice Mirveda

**Expected Results:** Defend Mirveda, complete quest.

**Actual Result:** Scourge don’t attack, completion doesn’t happen. 

**Additional Information:** I tried abandoning and redoing, won’t allow me to retake quest.

**Comment by PeppyDolphin** [comment]
So the Scourge appear but they don't target her and attack her?
I did notice that she wasn't accepting quest when I stopped by her. I re-spawned her and it seems to be working okay now. I could do the pre-quest and the mentioned quest just fine.
Could you try again for me when you have time?

**Comment by Kaghol** [comment]
Just tried it again. Working properly!
