### ISSUE TITLE
Item: Haste Potion

### ISSUE THREAD

**Issue by Murades** [elysium-project/tbc-bug-tracker#558]
**Summary:** 
The haste potion I bought from the vendor in org doesn't increase my haste when I drink it. (the lvl 60 +400 haste for 15seconds).
**Steps to Reproduce:** 
drank it
**Expected Results:** 
gain 400 haste! :)
**Actual Result:**
gained 0 haste :(
**Additional Information:**
-

**Comment by Ziggy-QA** [comment]
@AndiestAndy This seems to be working as intended. Can you supply more information on how to reproduce the bug? What class were you playing? Are you saying you do not get melee haste or spell haste?

Please reply

**Comment by AfterShave** [comment]
Haste potions still don't do anything.
