### ISSUE TITLE
Status Text: Numerical

### ISSUE THREAD

**Issue by Murades** [elysium-project/tbc-bug-tracker#559]
**Summary:** 
Under the status text when I toggle off "show percentages" with everything else checkmarked, it still shows my targets in %, but myself and pet in numeric
**Steps to Reproduce:** 
Toggle off display percentage with all other status texts checked
**Expected Results:** 
To see my targets numerical health
**Actual Result:**
I see health as a % but secondary resources (mana/rage/energy) as numeric
**Additional Information:**

**Comment by ZicoQA** [comment]
Which addons are you using? Make sure to clear wdb before starting in a new server as addons might glitch your ui.
With mine everything works fine. Can you take a look at wdb and get back to me if its fixed?

**Comment by Ziggy-QA** [comment]
This is blizzlike.
