### ISSUE TITLE
Wolfshead helm isn't working properly

### ISSUE THREAD

**Issue by BrVer** [elysium-project/tbc-bug-tracker#560]
**Summary:** 
wolfshead helm (link to classic item is https://classicdb.ch/?item=8345) is not giving 20 energy when shapeshifting to a cat
**Steps to Reproduce:** 
roll druid, equip item, shift to a cat multiple times
**Expected Results:** 
with 'Furor" talent to 0/5 (unlearned) and helm equipped you get 20 energy, if you shift right when energy tick comes - 40
with 'Furor" talent to 5/5 and helm equipped you get 60 energy, if you shift right when energy tick comes - 80
with 'Furor" talent to 5/5 and helm unequipped you get 40 energy, if you shift right when energy tick comes - 60
**Actual Result:**
with 'Furor" talent to 0/5 (unlearned) and helm equipped you get 0 energy, if you shift right when energy tick comes - 20
with 'Furor" talent to 5/5 and helm equipped you get 40 energy, if you shift right when energy tick comes - 60
with 'Furor" talent to 5/5 and helm unequipped you get 40 energy, if you shift right when energy tick comes - 60
**Additional Information:**
tested on Drulenka char, realm "TBC Beta PVP"

**Comment by Ziggy-QA** [comment]
Confirmed. Tested on current build.
