### ISSUE TITLE
Windfury Weapon Consuming Clearcasting Procs

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#561]
When clearcasting procs for an enhancement shaman, if windfury happens, both clearcasting procs will be eaten by the windfury.

**Comment by ZicoQA** [comment]
Please go to this site:
https://legacyplayers.com/Tools/Talents/#U
Put your talents up and link here.
I want to make sure I have your talents right to recreate this.

**Comment by AndiestAndy** [comment]
[Here you go](https://legacyplayers.com/Tools/Talents/#UE0zxZxVMdVMsAuqo).

I have 5 pieces of T4 enhance shammy gear as well.

**Comment by ZicoQA** [comment]
This:
> Patch 2.4.0 (25-Mar-2008): This buff will no longer be removed when Shamanistic Focus is triggered.
Makes it blizzlike. We are starting in patch 2.0.1.
Patch 2.4 is when Sunwell hits
