### ISSUE TITLE
Quest: Dust From the Drakes

### ISSUE THREAD

**Issue by AndiestAndy** [elysium-project/tbc-bug-tracker#562]
The quest Dust From the Drakes requires 4 of the quest item, Dust of the Fey Drakes to drop from the Fey Drake mobs, but it _seems_ to be internally tagged to stop dropping after 3 drops. I got 3 of the drops in a full clear of the area and then did another two clearings (about 20 or so mobs) and got no further drops.

**Comment by ZicoQA** [comment]
My first try of this quest gave me all 4 in 14 kills wich gives success rate of 28.57%.
Wowhead gives the droprate of these to be 39%.
I will give some more tests later. It's soon to see if the droprate is off, only with more sampling.

**Comment by AndiestAndy** [comment]
I deleted all my initial dusts and after 15 drakes, I got the 4th.

**Comment by ZicoQA** [comment]
I have tried with 3 different characters and they are giving me roughly the percent drops close to wowhead. It is working as intended
