### ISSUE TITLE
Skittering Crawlers near Odesyes' Landing

### ISSUE THREAD

**Issue by Bayonn** [elysium-project/tbc-bug-tracker#563]
**Summary:** 
Skittering Crawlers evading when attacking them with a range attack from on land near Odesyus' Landing on Azuremyst Isle

**Steps to Reproduce:** 
Attack a Skittering Crawler from on land not touching the water.

**Expected Results:** 
Skittering Crawler goes to player and attacks them.

**Actual Result:**
Skittering Crawler takes damage at first but then does not move and evades damage resulting in npc reseting.

**Additional Information:**
n/a

**Comment by ZicoQA** [comment]
We are aware of the issues that we are having due to water. Please post any more in our Water ticket. (Pinned)
