### ISSUE TITLE
Shadowfang Keep

### ISSUE THREAD

**Issue by Kaghol** [elysium-project/tbc-bug-tracker#564]
**Summary:** Deathstalker Adamant won’t open the door after the first boss.

**Steps to Reproduce:** Kill first boss, talk to Adamant.

**Expected Results:** He opens the door to the rest of instance.

**Actual Result:** nothing happens

**Additional Information:**

**Comment by ZicoQA** [comment]
Also sorcerer's gate not Opening after Fenrus de Devourer dies

**Comment by ZicoQA** [comment]
Arugal's lair door also not opening after boss dies
