### ISSUE TITLE
Blackfathom Deeps

### ISSUE THREAD

**Issue by Kaghol** [elysium-project/tbc-bug-tracker#566]
**Summary:** After killing Twilight Lord Kelris lighting the Braziers does not summon mobs or open the door to the final boss.

**Steps to Reproduce:** Kill Kelris, light braziers

**Expected Results:** light brazier, group of mobs come. Do this four times to open door to final boss.

**Actual Result:** nothing

**Additional Information:**

**Comment by TheGreyMouser** [comment]
Issue still exists.
