### ISSUE TITLE
Wailing Caverns

### ISSUE THREAD

**Issue by Kaghol** [elysium-project/tbc-bug-tracker#568]
**Summary:** Mobs attacking from across the dungeon and through walls

**Steps to Reproduce:** had a 60 run my through and I believe his thunderclap was aground across the instance

**Expected Results:** 

**Actual Result:**

**Additional Information:**

**Comment by ZicoQA** [comment]
Also Disciple of Naralex doesn't have a script to sumon last boss. Clicking his dialog box does nothing.
