### ISSUE TITLE
Disciple of Naralex escort

### ISSUE THREAD

**Issue by Kaghol** [elysium-project/tbc-bug-tracker#569]
**Summary:** talking to him after clearing the instance does not start the escort to final boss.

**Steps to Reproduce:** clear instance, talk to him

**Expected Results:** he talks and starts walking

**Actual Result:** nothing

**Additional Information:**

**Comment by ZicoQA** [comment]
This has been added on the other Wailing Caverns Ticket:
https://github.com/elysium-project/tbc-bug-tracker/issues/568
