### ISSUE TITLE
Draenei Starter Quests Glitchy

### ISSUE THREAD

**Issue by nielsen-larell** [elysium-project/tbc-bug-tracker#570]
**Summary:** 

**Steps to Reproduce:** 

**Expected Results:** 

**Actual Result:**

**Additional Information:**

**Comment by nielsen-larell** [comment]
On multiple occasions the starting quests will glitch/lag. I am not sure if this is a server issue not responding to the click but what will happen is that you will try and complete and it will just hang. If you exit the completion and come back a few minutes later it will work or it has also completed it a minute after you exit. In some cases the NPC will not ever be there to finish and using the same actions they will magically appear after you are in the area for a minute.

**Comment by ZicoQA** [comment]
Nielsen this looks like an issue with your client side. Could you please clear your WDB folder and report back to us if this glitch is still on going?

**Comment by Ziggy-QA** [comment]
This was due to ASAN
