### ISSUE TITLE
Draenei Azuremyst Isle Copper Nodes glitchy

### ISSUE THREAD

**Issue by nielsen-larell** [elysium-project/tbc-bug-tracker#571]
Every time I try and mine a copper node in the zone it will hit once, every subsequent time fails so you get a max of 1 ore per node. :(

**Comment by nielsen-larell** [comment]
Ok, worked some more with it. The node will eventually get cleaned up but you still only got 1 ore :(

**Comment by Kaghol** [comment]
This is not just in start areas, but around the world too

**Comment by McMittens** [comment]
This is a known and being investigated, if you have any further info please psot it into this issue: https://github.com/elysium-project/tbc-bug-tracker/issues/255
