### ISSUE TITLE
Doorway to the Abyss

### ISSUE THREAD

**Issue by Kaghol** [elysium-project/tbc-bug-tracker#574]
**Summary:** burning legion gate is out of range

**Steps to Reproduce:** kill Warbringer Arix’ Amal, get key, close gate

**Expected Results:** 

**Actual Result:** gate is out of range to close it

**Additional Information:**

**Comment by McMittens** [comment]
Duplicate https://github.com/elysium-project/tbc-bug-tracker/issues/422
