### ISSUE TITLE
Quest: Missing Friends [10852]

### ISSUE THREAD

**Issue by kedross** [elysium-project/tbc-bug-tracker#581]
Children will not leave the cage, go home to their families, lead a happy life, and count for credit on the quest.

I don't know if this warrants as a quest bug or Stockholm's Syndrome. Probably the former.

**Comment by McMittens** [comment]
Quest: http://db.hellfire-tbc.com/?quest=10852
Children: http://db.hellfire-tbc.com/?npc=22314
Key: http://db.hellfire-tbc.com/?item=31655
Cage object IDs: 185202 -185205

Right now nothing happens upon opening a cage, except the cage closes eventually.

As stated the children should run away from the cage (all the way out of the camp, then despawn) and give credit when their cage gets opened. Each child counts on their own.

![23](https://user-images.githubusercontent.com/46020700/51861493-b00a8480-233c-11e9-8887-559bd84fdc08.PNG)

They also thank their saviour by saying things like
Captive Child: Woot!
Captive Child: Yay! We're free!
Captive Child: Yay! We love you! You saved us!
and
Captive Child 1: I think those weird bird guys were going to eat us! Gross!
Captive Child 2: Gross!
