### ISSUE TITLE
NPC Location : Misplaced Wrath Master

### ISSUE THREAD

**Issue by Whynoth** [elysium-project/tbc-bug-tracker#583]
**Summary:** 
A Wrath Master (npc=19005) is standing 10yd away from Portal Xilus (object=184290). 

**Expected Results:** 
There's a legit elite who has a %chance to spawn upon successfull interaction with the portal during the quest Disrupt their reinforcements (quest=10208), but that's a lvl 60 Felguard Destroyer (npc=18977), not a lvl 71 crusher of hopes & dreams.

**Additional Information:**
![wowscrnshot_012619_220753](https://user-images.githubusercontent.com/45531621/51793085-40b95700-21bb-11e9-9fd0-7e90b2407c77.jpg)

**Comment by McMittens** [comment]
This NPC is in the wrong spot, it should be placed at the Dark Portal.

The Felguard Destroyers have a seperate issue: https://github.com/elysium-project/tbc-bug-tracker/issues/493
