### ISSUE TITLE
Spell broken[25218]

### ISSUE THREAD

**Issue by Sifern** [elysium-project/tbc-bug-tracker#584]
**Summary:** 
Power word shield has a 30 second cooldown, applies "weakened soul". Weakened soul lasts 15 seconds. On blizzards servers you could recast PW:S after the 15 seconds to refresh the buff, however currently on the beta if you recast PW:S after weakened soul ends, and you still have PW:S up, it doesn't refresh PW:S but it keeps ticking down. 

**Steps to Reproduce:** 
Use spell: [25218] on any player, then re-use it after weakened soul ends

**Expected Results:** 
PW:S refreshes back to 30 seconds, and full buff.

**Actual Result:**
PW:S timer doesn't get refreshed after re-using it.

**Additional Information:**
Happened by player "Pire".

**Comment by PhilosophyOfZen** [comment]
Ah, looks like you got the same issue as my priest did. xD

**Comment by McMittens** [comment]
https://github.com/elysium-project/tbc-bug-tracker/issues/587 Duplicate, thanks for the report tho!
