### ISSUE TITLE
All casts get interrupted when destroying items.

### ISSUE THREAD

**Issue by Sifern** [elysium-project/tbc-bug-tracker#585]
**Summary:** 
When you're casting anything (greater heal, mounts, hearthstone etc.) and you destroy an item (for example destroying a herb well mounting up) it will interrupt your cast. You should be able to destroy items well casting.

**Steps to Reproduce:** 
Use your hearthstone -> destroy any item well your hearthstone is casting

**Expected Results:** 
Hearthstone keeps casting and finishes

**Actual Result:**
Hearthstone cast gets interrupted

**Additional Information:**
Very very annoying well herbing when you want to cast your flying mount and destroy a bad-tier herb.

**Comment by Ziggy-QA** [comment]
This is confirmed since casts do not interrupt in vanilla and they do in TBC.
