### ISSUE TITLE
Power Word Shield Refresh

### ISSUE THREAD

**Issue by PhilosophyOfZen** [elysium-project/tbc-bug-tracker#587]
**Summary:**
Refreshing Power Word: Shield after Weakened Soul drops (but before Power Word: Shield itself drops) does not refresh the duration of Power Word: Shield.

**Steps to Reproduce:**
Refresh PW:S after weakened soul drops.

**Expected Results:** 
PW:S's duration should refresh.

**Actual Result:**
PW:S's duration does not refresh.

**Additional Information:**
Possibly could have something to do with Priest Gladiator's Satin set bonus.

**Comment by McMittens** [comment]
This seems to always happen as soon as the character has any additional healing power.

**Comment by Ziggy-QA** [comment]
Mages frost barrier had the same issue. It happened when any item with int was equipped. The devs should know how to fix this quickly fortunately.

**Comment by AfterShave** [comment]
Bug is still present as of the 8th of May 2019

**Comment by AfterShave** [comment]
bump
