### ISSUE TITLE
Fel Iron Shells

### ISSUE THREAD

**Issue by Lympy** [elysium-project/tbc-bug-tracker#601]
Crafting Fel Iron Shells with engineering currently gives 400 shells instead of the intended 200.
![r0gweo2](https://user-images.githubusercontent.com/47334835/52246763-3dbf1480-28e7-11e9-8f5a-344a04063d6d.jpg)
![pevzcpi](https://user-images.githubusercontent.com/47334835/52246770-46174f80-28e7-11e9-9f29-94e247c156ef.jpg)

**Comment by McMittens** [comment]
Thank you for your report!
