### ISSUE TITLE
Dummy Issue

### ISSUE THREAD

**Issue by ljjumper** [elysium-project/tbc-bug-tracker#606]
**Summary:** 
The dummy's ( in Shattrath ) tend to attack back sometimes and in addition to that, they keep you in combat forever. Only way to flee is through portal, or abilities like vanish
**Steps to Reproduce:** 
Just attack a dummy. This might take some tries/ luck but at least the combat bug should be reproduce able all the time. 
**Expected Results:** 
-Dummy's shouldn't hit/attack you back
-You should leave combat as soon as you stop attacking a dummy
**Actual Result:**
-Dummy's is attacking back 
-Staying in combat forever if you dont know how to break it with tricks
**Additional Information:**

**Comment by Ziggy-QA** [comment]
Dummys will attack you back if you use a stun effect on them. It replaces the stun forever aura on them and then it expires. This is an unavoidable game mechanic, however useful to warriors who want to test with rage gained from being hit. As for the combat bug, this can be a problem, but thats why i placed portals to shattrath next to the places you port in orgrimmar and stormwind, for easy combat reset.

This is PTR specific, and will not be an issue at launch in any case
