### ISSUE TITLE
Apprentice riding and mounts available at lvl 30

### ISSUE THREAD

**Issue by MrMarvin** [elysium-project/tbc-bug-tracker#609]
**Summary:** Both the Apprentice riding and the 40% mounts are available at level 30. This was only introduced in patch 2.4.3.

> Mounts at 30?! Yes, it’s true: Apprentice Riding and mounts are now available at level 30. Training costs 35Gold.

(https://wowwiki.fandom.com/wiki/Patch_2.4.3)

**Steps to Reproduce:**
1. Visit riding trainer, buy skill
2. visit mount vendor, buy mount
3. ride away

**Expected Results:** 
* riding at lvl 40

**Actual Result:**
* riding at lvl 30

**Additional Information:**
Yep, I cleaned WDB.

**Screenshots:**
![inkedwowscrnshot_020719_115004_li](https://user-images.githubusercontent.com/100136/52407878-b8e41e80-2ad1-11e9-875d-c8ecbd5c7e09.jpg)
![inkedwowscrnshot_020719_120219_li](https://user-images.githubusercontent.com/100136/52407885-bb467880-2ad1-11e9-8c83-9eca18fcedf7.jpg)

**Comment by Ziggy-QA** [comment]
Thank you for this report!

**Comment by Ziggy-QA** [comment]
Hello, it has been decided that this will be kept in game. Thank you for the report regardless!
