### ISSUE TITLE
Pet Training not showing buff timer, not dismissing pet on turning in

### ISSUE THREAD

**Issue by saltyqa** [elysium-project/tbc-bug-tracker#610]
**Summary:** 
When a hunter trains a pet during [Taming the Beast], upon turning the quest in each time, the pet is not dismissed. There is also no buff timer on the trained pet for how long it would last. 

**Steps to Reproduce:** 
Level 10 Hunter
Select [Taming the Beast] quest
Tame beast
Turn in quest

**Expected Results:** 
Beast would be dismissed

**Actual Result:**
Tamed beast is not dismissed
Timer buff would be present

**Additional Information:**
This happened on all three tamed beasts

**Comment by McMittens** [comment]
It's working as it should that the beast doesn't get dismissed on it's own, you have to do that manually.
![23](https://user-images.githubusercontent.com/46020700/52731379-e2171a00-2fbd-11e9-81a1-f9cd46ec6b9a.png)
Timer does show up for me.

**Comment by McMittens** [comment]
If you have any further information to reproduce this issue please comment!
