### ISSUE TITLE
Toshley's Station: "Test Flight" quests

### ISSUE THREAD

**Issue by Lympy** [elysium-project/tbc-bug-tracker#612]
The quest "Test Flight: The Zephyrium Capacitorium" requires you to talk to Rally Zapnabber which after a dialogue option should cause the player to fly into the air. Upon talking to Rally Zapnabber nothing happens making the quest impossible to complete.

**Comment by McMittens** [comment]
I found all of the test flight quests at Toshley's Station don't work.

Test Flight: The Zephyrium Capacitorium [10557] destination is X: 1764.261, Y: 5903.822, Z: 149.837 (for reference of flight path: https://www.youtube.com/watch?v=OGOlMDCGMO4)

Test Flight: The Singing Ridge [10710] destination is X: 1768.118, Y: 5182.214, Z: 265.771 (for ref. of flight path: https://www.youtube.com/watch?v=rdydD6sqARQ)

Test Flight: Razaan's Landing [10711] destination is X: 2617.488, Y: 5222.392, Z: 265.542 (for ref. of flight path: https://www.youtube.com/watch?v=fFSAMFj_An0)

Test Flight: Ruuan Weald [10712] destination is X: 2977.739, Y: 5481.433, Z: 143.379 (for ref. of flight path: https://www.youtube.com/watch?v=O7f61WsQjp8)
