### ISSUE TITLE
"Protecting our own" Not working

### ISSUE THREAD

**Issue by Lympy** [elysium-project/tbc-bug-tracker#616]
The quest "Protecting Our Own" currently gives no credit when interacting with the Grove Seedlings.

**Comment by McMittens** [comment]
http://db.hellfire-tbc.com/?quest=10457

Quest works, just doesn't give credit when using http://db.hellfire-tbc.com/?item=29952 on http://db.hellfire-tbc.com/?object=184631.

**Comment by saltyqa** [comment]
@McMittens what is the quest ID?
