### ISSUE TITLE
Hellfire Ramparts

### ISSUE THREAD

**Issue by Marckotobelo** [elysium-project/tbc-bug-tracker#618]
**Summary:** 
Omor the Unscarr.... kicking players out of the Dungeon.
**Steps to Reproduce:** 
Fight against the Boss, get close to the edge, get kicked. Then u fly out of the Dungeon and die.
**Expected Results:** 
The Boss does use the Kick-ability, but he usually pulls you straight back to him, after knocking you up in the air.
**Actual Result:**
The pullback mechanic doenst always work. If it doenst work, u fly away and die outside the Dungeon. Usually he should ALWAYS pull you back to him.
**Additional Information:**

**Comment by Marckotobelo** [comment]
Summary: Omor the Unscarr.... kicking players out of the Dungeon.

Steps to Reproduce: Fight against the Boss, get close to the edge, get kicked. Then u fly out of the Dungeon and die.

Expected Results: The Boss does use the Kick-ability, but he usually pulls you straight back to him, after knocking you up in the air. 

The pullback mechanic doenst always work. If it doenst work, u fly away and die outside the Dungeon. Usually he should ALWAYS pull you back to him.

![screen1](https://user-images.githubusercontent.com/45903438/52520565-d39dcb00-2c6a-11e9-8a0e-07605e18b15c.png)

**Comment by Ziggy-QA** [comment]
This has already been confirmed internally, however, thank you for the report
