### ISSUE TITLE
Armortype not tagged "red/unuseable" as clothuser

### ISSUE THREAD

**Issue by Marckotobelo** [elysium-project/tbc-bug-tracker#620]
**Summary:** 
![awdda](https://user-images.githubusercontent.com/45903438/52520903-75271b80-2c6f-11e9-9d99-7252af9ed551.png)
As u can see on the screenshot, the armortype is not shown as unuseable when it dropps/also when its in the inventory.
**Steps to Reproduce:** 
Mouseover an item which is Plate as Cloth-User (f.e. warlock)
**Expected Results:** 
The name "Mail", "plate" should be red, to show, it is unuseable.
**Actual Result:**
The name is white, so i might be thinking of rolling on items, which cant even be used by my class.
**Additional Information:**

**Comment by Ziggy-QA** [comment]
Hello, I cannot reproduce this. Please delete your WDB folder, disable all addons, and let me know if it continues to happen. Thank you!

**Comment by Marckotobelo** [comment]
ok thx, working fine for me now :)
