### ISSUE TITLE
Guild charter signatures from same account

### ISSUE THREAD

**Issue by MrMarvin** [elysium-project/tbc-bug-tracker#621]
**Summary:**
When creating a guild via signatures on a guild charter, there is an inconsistency on who can sign the charter. When signing with multiple toons from the same account, for the charter holder multiple signatures appear, however they are not persisted.
The charter is ultimately not accepted at the embassy, as it has not enough signatures.

**Steps to Reproduce:** 
Have two accounts ready.
1. Create guild charter on a toon on accountA
2. Let a toon from a accountB sign it.
2. Create an additional toon on accountB
3. Log in new toon
4. Sign guild charter
5. See error message when signing: 'You already signed that charter.'
6. See open guild charter frame on accountAs toon, it has the new name on it. Also the chat message confirms signature.
7. Close charter frame
8. Open charter frame from the item in bags
9. See list of names does not have the signature

**Expected Results:** 
I don't now actually. Should it be allowed to sign the same charter on multiple toons from the same account?

**Actual Result:**
Inconsistency in display of signatures and misleading chat messages.

**Additional Information:**
![guild_charter_signature_missmatch](https://user-images.githubusercontent.com/100136/52534171-5d6a9880-2d3e-11e9-9534-5d1345a4615b.PNG)

**Comment by McMittens** [comment]
The base mechanic is working as intended, you can't sign your own guild charta, or sign it multiple times with toons from one account.
Only thing questionable here is if you can turn in the charta after collecting 10 names on it, without opening the charta again to show that they didnt count.

**Comment by Ziggy-QA** [comment]
This is working as intended. I think relogging would refresh the list as its temporarily stored in WDB
