### ISSUE TITLE
Invasion point: Annihilator

### ISSUE THREAD

**Issue by mrhenkz** [elysium-project/tbc-bug-tracker#622]
**Summary:** 
After you've slain Arix'Amal and you get the Burning Legion Key you're not able to close it, says you are too far away whenever you try to use it.

**Steps to Reproduce:** 

**Expected Results:** 
Able to reach the Rune of Spite so you can close the gate.

**Actual Result:**
Not able to reach Rune of Spite. or what ever it is called.

**Additional Information:**
![wowscrnshot_022119_125255](https://user-images.githubusercontent.com/47500238/53167408-1f8c3080-35d8-11e9-83bb-985871c76d82.jpg)

**Comment by Ziggy-QA** [comment]
#461
