### ISSUE TITLE
Digging for Prayer Beads

### ISSUE THREAD

**Issue by mrhenkz** [elysium-project/tbc-bug-tracker#623]
**Summary:** 
There is no dirt pile or anything at the back of the Inn to dig from.

**Steps to Reproduce:** 

**Expected Results:** 
A pile of dirt, might be called "Fei Fei's Cache" should spawn at the back of the Honor Hold Inn.

**Actual Result:**
Nothing appears at all.

**Additional Information:**
Even after giving Fei Fei it's treat and following it around the whole of Honor Hold it still doesn't show up.
![feifei](https://user-images.githubusercontent.com/47500238/52587370-25e11680-2e3a-11e9-99c1-2acd6239b1bf.jpg)

**Comment by McMittens** [comment]
This issue has already been reported: https://github.com/elysium-project/tbc-bug-tracker/issues/390
