### ISSUE TITLE
Quest#5321 [The Sleeper Has Awakened] Kerlonian returns to the starting point when he sleeps

### ISSUE THREAD

**Issue by saltyqa** [elysium-project/tbc-bug-tracker#625]
**Summary:** 
The first time Kerlonian sleeps, he returns back to the starting point. Can never get beyond the first sleep.

**Steps to Reproduce:** 
Start quest 5321 [The Sleeper Has Awakened] in Darkshore (near Onu)
Run with Kerlonian until the first time he sleeps

**Expected Results:** 
He falls asleep on the spot where he is

**Actual Result:**
He returns back to the start point

**Additional Information:**
I'm finding it difficult to test across different characters because Kerlonian wasn't there when I logged on a few minutes after trying it with one toon,, but was able to reproduce numerous times with different ones eventually.

**Comment by Koenshi** [comment]
Can confirm, just tried doing this quest, right now it's completely impossible as Kerlonian always returns to his starting spot.
