### ISSUE TITLE
Spider cocoons spawning wrong creatures on Bloodmyst isle

### ISSUE THREAD

**Issue by nyhotep** [elysium-project/tbc-bug-tracker#631]
**Summary:** 
Spider web cocoons (objective of 9670 They're alive! Maybe...) are spawning random creatures including quest objectives from elsewhere.
**Steps to Reproduce:** 
Break cocoons
**Expected Results:** 
Should spawn expedition researchers or local mobs (satyrs, constrictor vines, ravagers etc.)
**Actual Result:**
Spawning all sorts of creatures including those only triggered by other quests.
**Additional Information:**
Two circuits round the hill included all the following mobs:
atoph the bloodcurst (17715)
wrathscale sorceress  (17336)
wrathscale marauder (17334)
deathclaw (17661)
tel'athion the impure (17359)
zarakh (17683)
void anomaly (17550)
lord xiz (17701)
cruelfin (17496)
myst spinner (17552) - spider in own web!

**Comment by McMittens** [comment]
Not exactly a duplicate but directly realtes to issue https://github.com/elysium-project/tbc-bug-tracker/issues/533
I will close this ticket and add your information to the existing one. Thanks for your report!
