### ISSUE TITLE
Mage: "Refreshment Table" bug

### ISSUE THREAD

**Issue by ljjumper** [elysium-project/tbc-bug-tracker#642]
**Summary:** 
The "Refreshment Table" of the mage class throws an error, as soon as its summoned and someone tries to click it. (Error: Item not found)
**Steps to Reproduce:** Summon the "Refreshment Table" as a mage and try to click it. You should receive an error message. (Error: Item not found)

**Expected Results:** 
People should be able to receive "conjured mana food " after clicking on it
**Actual Result:**
Receive of an error message. 
**Additional Information:**

**Comment by McMittens** [comment]
https://wowwiki.fandom.com/wiki/Ritual_of_Refreshment

The spell should only be implemented in a later patch, the item[34062] it conjures is not in the current 2.0.12 database, hence it throws an error.
Ritual of Refreshment[43987] should be removed from class trainers until 2.3

**Comment by Ziggy-QA** [comment]
This is a PTR specific issue and will now be closed. Thank you for your report regardless.
