### ISSUE TITLE
Raid IDs

### ISSUE THREAD

**Issue by McMittens** [elysium-project/tbc-bug-tracker#645]
There is two major problems regarding raid IDs.

Currently people in a raid will get into seperate instances when going through a raid portal. They all get seperate IDs which causes them to not see each other and be unable to do the raid. This can only be resolved with GM help by summoning all palyers into the GMs ID.

**This does not happen all the time.** Today (28.02.)we had 2 alliance raids go into Karazhan after the weekly reset and one raid had no trouble while the other needed assistance.
Theres further investigation needed to find what triggers it.

Furthermore IDs will fully reset when the raid group is reformed. People keep their assigned ID but defeated bosses are not properly saved and get reset when the raid is entered with a newly formed raid group.

**Comment by Ziggy-QA** [comment]
This has been fixed (I think)
