### ISSUE TITLE
Warlock Quest Voidwalker for Bloodelfs

### ISSUE THREAD

**Issue by Raenerys** [elysium-project/tbc-bug-tracker#649]
Im trying to do the "The Stone" quest for the Voidwalker for the Bloodelfs. I found the Blue stones to click. When I try to end the quest I can't geht the reward. It only says "internal bag error"

**Comment by IvanDanshin** [comment]
Don't understand, it works..
https://i.gyazo.com/c863d08e2d45f2c999849fa98c062a29.mp4

**Comment by Raenerys** [comment]
For me it's not. With and Without Addons, always when I want to turn in the Quest to the Stones, it say's "Internal Bag Error". My Warlock level 10 is Standing at these Stones now for weeks in hope it will work some day xD I dont know why it's working for you, but not for me!

**Comment by Raenerys** [comment]
![WoWScrnShot_050519_071738](https://user-images.githubusercontent.com/49061968/57188853-08d25600-6f06-11e9-9a5f-6701f539c784.jpg)

**Comment by xPunchfacex** [comment]
I have the exact same issue. Has this been resolved? I was told to post the bug, but I don't want to clog the issues list if this is a known bug either being worked on, or already resolved. 

https://forum.elysium-project.org/topic/73354-internal-bag-error-the-stone-quest/?tab=comments#comment-481016

**Comment by Liljaco** [comment]
Bumping thread, my fresh level 11 Blood elf warlock has the same issue. When I loot and complete quest I get the Internal Bag Error.

**Comment by jayplex** [comment]
Just wanted to report that I am having this issue as well. Same as the screenshots above.

**Comment by samassaro** [comment]
Same issue as screenshot above.

**Comment by SilvioDoMine** [comment]
Same issue as screenshot above.

**Comment by Thalminior** [comment]
Same issue as above,
i have abandoned and attempted to re acquire, have also cleared WDB folder and tried again same issue

**Comment by Thalminior** [comment]
also reported as bug #758

**Comment by SilvioDoMine** [comment]
This issue can be safely closed now.
