### ISSUE TITLE
Auberdine boats are buggy

### ISSUE THREAD

**Issue by Koenshi** [elysium-project/tbc-bug-tracker#651]
The boats moving to and from Auberdine seem to be quite buggy.
At times the arrival and departure animations don't seem to work, the boats just appear and disappear instead. In addition, when travelling, the boat briefly appears somewhere under the map either in Stonetalon Mountains or Alterac Valley (player is unable to move) for a good 10-20 seconds before teleporting to the destination and approaching the harbour as normal.

**Comment by Ziggy-QA** [comment]
This is a known issue that happens when the server is online for an extended period of time.

Thank you for your report, however this is a duplicate. You may post more information here #480
