### ISSUE TITLE
Jumping in water (?)

### ISSUE THREAD

**Issue by Koenshi** [elysium-project/tbc-bug-tracker#652]
Not _entirely_ sure this is a bug, my memory of Vanilla/TBC swimming mechanics isn't exactly perfect, but as far as I remember jumping while swimming should not be possible - instead hitting the spacebar should just make your character swim upright. Please correct me if I'm wrong.

**Comment by Ziggy-QA** [comment]
https://youtu.be/R0qKrobNNVI?t=298

This video clearly shows a player jumping in water exactly as described. What you are remembering is from a later expansion
