### ISSUE TITLE
Paladin: judgment of the seal of command

### ISSUE THREAD

**Issue by itipou** [elysium-project/tbc-bug-tracker#654]
**Summary:** when using judgment of the seal of command, the damage applied isn't instant, there's a delay before the damage occurs.

**Steps to Reproduce:** used judgment on the seal of command on any mob

**Expected Results:**  damage is instant

**Actual Result:**  a delay before damage is applied

**Additional Information:**

**Comment by Ziggy-QA** [comment]
This is an intentional design decision to allow for paladin seal twisting. It still might need some adjustment, but its definitely not a bug.

#512
