### ISSUE TITLE
Summoning warlock pets in nagrand causes crash

### ISSUE THREAD

**Issue by jsprn** [elysium-project/tbc-bug-tracker#655]
**Summary:** 
When summoning a warlock pet the game crashes in nagrand
**Steps to Reproduce:** 
Summon any pet and game crashes
**Expected Results:** 
No crash
**Actual Result:**
Game crash

**Additional Information:**

**Comment by Ziggy-QA** [comment]
Could not reproduce. Game doesnt crash for me. Maybe download a different client or delete your WDB folder? Could also be an addon. Feel free to give me more additional info if it keeps happening. Closing this for now!
