### ISSUE TITLE
Mobs in Stillpine Hold have no pathing

### ISSUE THREAD

**Issue by AfterShave** [elysium-project/tbc-bug-tracker#657]
**Summary:** 
None of the mobs in Stillpine Hold have any pathing, they just stand where they spawn . Pretty much sure they should pace around since that's the norm.

**Steps to Reproduce:** 

Go to Stillpine Hold, North most part of Azuremyst Isles. 

**Expected Results:** 

Mobs should move

**Actual Result:**

Mobs don't

**Additional Information:**

**Comment by Draakspeel** [comment]
Every mob/npc on the main isle (Exodar included) EXCEPT npc "Artificer Daelo, Engineering Trainer" in Azure Watch, has no pathing. They all just stand there.

**Comment by lilyzephyr** [comment]
I just crossed the bridge to Bloodmyst Isle, and the mobs there are just standing around too
