### ISSUE TITLE
What We Don't Know... (ID: 9756)

### ISSUE THREAD

**Issue by KarisaV** [elysium-project/tbc-bug-tracker#659]
**Summary:** 
You are given Exarch's Enchantment to talk to the Captured Sunhawk Agent to receive Sunhawk Information but the dialogue is not translated and quest objective not met.
![Captured Sunhawk Agent](https://user-images.githubusercontent.com/50557420/57588378-f5f8ec00-74d8-11e9-8535-1ad5490aecb2.png)

**Steps to Reproduce:** 
Try talking to the Captured Sunhawk Agent.

**Expected Results:** 
Captured Sunhawk Agent should have translated dialogue and quest objective met.

**Actual Result:**
Captured Sunhawk Agent dialogue isn't translated and quest objective cannot be completed.

**Additional Information:**

**Comment by McMittens** [comment]
Quest: https://tbcdb.com/?quest=9756
Trigger: https://tbcdb.com/?npc=17974
Prison: https://tbcdb.com/?object=182012

https://www.youtube.com/watch?v=_k7x2hXlqPE best source I could find.

The Trigger NPC[17974] doesn't do anything.
Apparently additionally to not being able to talk to the bloodelf, he's not even imprisoned. The GO Makeshift Prison[182012} is missing at his location.

**Comment by IvanDanshin** [comment]
Fixed.
