### ISSUE TITLE
[Quest] WANTED: Murkdeep! (ID: 175320)

### ISSUE THREAD

**Issue by KarisaV** [elysium-project/tbc-bug-tracker#660]
**Summary:** 
Quest mob Murkdeep (NPC ID: 10323) doesn't spawn.

**Expected Results:** 
Murkdeep should spawn at 37,44 of Darkshore

**Actual Result:**
Searched spawn area and all up and down the shore. Murkdeep is nowhere to be found.

**Comment by McMittens** [comment]
https://youtu.be/AHwNovEpx0M?t=60

In this you can see Murkdeep spawn on the right as the player get's closer to the Murkdeep Spawner NPC [100197]. The script to spawn Murkdeep on approach of the spawner is missing.

https://tbcdb.com/?npc=10323
https://tbcdb.com/?quest=4740

**Comment by IvanDanshin** [comment]
Fixed.
