### ISSUE TITLE
Ridgespine Horror

### ISSUE THREAD

**Issue by philoxg** [elysium-project/tbc-bug-tracker#665]
**Summary: These spiders "Ridgespine Horror" seem to be bugged: they won't move from the original stealthed location when in combat.** 

**Steps to Reproduce: Pull a "Ridgespine Horror" and run.** 

**Expected Results: It should come melee range and hit you.** 

**Actual Result: Instead, it only casts ranged attacks from its location, same as if you go melee range, still ranged attack(Toxic Spit).**

**Additional Information: If you run out of their range, they'll move from their location, but still only ranged attacks and snaring web. Also, they do the "melee attack animation" but they're actually casting Toxic Spit.**

**Comment by McMittens** [comment]
I couldnt find any source on how exactly they should behave since these creatures aren't linked to any quest. If you find info on that please re-open the ticket.
