### ISSUE TITLE
[Quest] The Dwarven Spy (ID: 8483) target despawns instead of dying

### ISSUE THREAD

**Issue by makethatwork** [elysium-project/tbc-bug-tracker#666]
**Summary:** When attacking Prospector Anvilward (ID: 15420), when his health gets too low he despawns instead of dying, leaving you unable to loot his head which is required to complete the quest.

**Steps to Reproduce:** Accept quest, speak with Anvilward, fight him down to approximately 10% health.

**Expected Results:** Anvilward drops to 0 health and dies, allowing you to loot the item Prospector Anvilward's Head (ID: 20764) which is required for quest completion

**Actual Result:** Anvilward despawns when his health gets to about 10-20% (can't tell exact percentage)

**Additional Information:** This quest can be skipped so it will not hinder levelling progress, but Anvilward takes a couple of minutes to respawn after despawning or being killed, so it is frustrating if you think you may have bugged out the quest and want to try again.

**Comment by McMittens** [comment]
https://tbcdb.com/?quest=8483
https://tbcdb.com/?npc=15420

Doesn't despawn if you kill him hard enough, but despawns immediately if you bring him to about 20% health and he doesn't die in one blow.

**Comment by IvanDanshin** [comment]
Fixed.
