### ISSUE TITLE
Atiesh karazan portal

### ISSUE THREAD

**Issue by Tercoil** [elysium-project/tbc-bug-tracker#673]
**Summary:** 
Portal that you cast if you have atiesh not teleporting player to Karazan, you can click on it but wont teleport.

**Steps to Reproduce:** 
Give yourself atiesh and make a portal.(tryed with mage version of atiesh:22589)

**Expected Results:** 
Teleportation to Karazan
**Actual Result:**
Only portal that you can click but wont be teleported
**Additional Information:**

**Comment by Ziggy-QA** [comment]
@Tercoil In TBC, The Karazhan Portal will now teleport you directly inside Karazhan. This means you must be in a raid group for it to work.
