### ISSUE TITLE
Ship to Azuremyst Isle from Auberdine has no animation

### ISSUE THREAD

**Issue by AfterShave** [elysium-project/tbc-bug-tracker#687]
**Summary:** 
Ship to Azuremyst Isle from Auberdine has no travel animation upon arrival to port. Simply appears out of nowhere, moves to a region of the ocean and then after a minute or so teleports to Azuremyst Isle. 

**Steps to Reproduce:** 
Get on the ship

**Comment by Ziggy-QA** [comment]
#480 Duplication. This issue is closed.
