### ISSUE TITLE
Vale Moth [NPC: 16520]

### ISSUE THREAD

**Issue by marcengeler** [elysium-project/tbc-bug-tracker#696]
**Summary:** 
Vale Moth [NPC: 16520] give too much XP and drop too many bags. I get to level 3 within minutes after starting in the draenei starter zone.

**Steps to Reproduce:** 
Start a draenei, start questing, first collection quest

**Expected Results:** 
Normal drops, normal XP

**Actual Result:**
150 XP per Mob and a lot of bag drops.

**Additional Information:**

**Comment by snat99** [comment]
Can confirm the high XP from the Vale Moth and also from the Volatile Mutation. Additionally both types of mobs stand still and don't move outside of combat. They do move when you attack them. 

Cannot confirm the bag part. Have killed a couple of mobs so far but not a single bag drop.

**Comment by McMittens** [comment]
XP rates are increased on PTR
