### ISSUE TITLE
Quest: Delivering the Message

### ISSUE THREAD

**Issue by Rorau** [elysium-project/tbc-bug-tracker#700]
**Summary:** 
The quest "Delivering the Message" in Netherstorm where a friendly quest-npc (https://tbc-twinhead.twinstar.cz/?npc=20802) (goes by the name "Protectorate Demolitionist") is spawned which you are supposed to protect, ends up failing when the npc seems to get stuck at a certain point. 

**Steps to Reproduce:**
Simply click the platform to summon the quest-giver, and then accept and complete quests until you get to the part of the questline where a friendly npc is supposed to sabotage a pipeline. 

The friendly escort npc will spawn and start to walk around to different locations and get attacked by hostile mobs. At some point it will walk over to a large glowing pipeline that leads into the Manaforge nearby and seem to perform some sabotage task. 

It will call for protection while this happens. A couple of hostile npcs spawn which you quickly dispose of. And then the friendly npc seems to get stuck. It says the task is completed with the words "_Done! Back up! Back up!_" but it just stands there and does nothing and the quest never completes. Eventually the escort npc just despawns. If you move too far away from the sabotage spot the quest fails so you have to abandon and retake it, but it has a 10 minute cooldown before you can summon the escort npc again. 

**Expected Results:**
The quest is supposed to complete when he has sabotaged the pipeline, but that never happens. 

**Actual Result:**
Nothing happens after the escort npc "completes" his sabotage job, he says the words but the quest does not complete. 

**Additional Information:**
Nothing I can think of.

**Comment by Rorau** [comment]
Quest is still bugged on live TBC server Stormrage as of August 16. This is the pre-quest immediately before the quest Nexus-King Salhadaar. 

Will this quest be fixed soon?

**Comment by Ziggy-QA** [comment]
It would help if I had the name and the ID of the "Friendly quest giver"

**Comment by Rorau** [comment]
The name of the escort npc is "Protectorate Demolitionist".

**Comment by HamonTim** [comment]
How it's supposed to work: https://www.youtube.com/watch?v=kbJgCI54fbA
Right now he's just stuck after his dialogue
![image](https://user-images.githubusercontent.com/38241815/63223506-bec06800-c1b6-11e9-9f37-cdb32c53fcb7.png)

**Comment by Nywucmuk** [comment]
Still doesnt work. After 5 mins of waiting npc dissapear.

**Comment by AfterShave** [comment]
Quest still impossible to complete as of this time.

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
