### ISSUE TITLE
Intercept rank one seem to be missing from trainer.

### ISSUE THREAD

**Issue by Jezzawar** [elysium-project/tbc-bug-tracker#701]
**Summary:** 
Intercept rank 1 seem to be lacking from the trainer. I cannot recall a quest prerequisit. Hence the report. Thx
**Steps to Reproduce:** 

**Expected Results:** 

**Actual Result:**

**Additional Information:**
![image](https://user-images.githubusercontent.com/52182503/60365618-217c5b00-99e1-11e9-8ff1-3af96362af7f.png)

**Comment by Jezzawar** [comment]
Just created ano

**Comment by Jezzawar** [comment]
I think I learnt the skill but is still doesn't exist and is still available in the trainer how peculiar.

**Comment by McMittens** [comment]
This is PTR specific since you normally get the skill for the lv30 berserk stance quest chain
