### ISSUE TITLE
Fishing: Catching a fish awards too many skill point

### ISSUE THREAD

**Issue by snat99** [elysium-project/tbc-bug-tracker#703]
**Summary:**  When fishing, catching a fish awards 10 skill points in fishing instead of 1.

**Steps to Reproduce:** As Draenei leaving the starting zone, Ammen Vale, bought fishing pole and learned fishing. 

**Expected Results:** Successfully catching a fish should have a chance to be given ONE skill point in fishing.

**Actual Result:** As far as tested, every catch gives TEN still points in fishing

**Additional Information:** Additional testing needed if this is race/zone/class specific issue

![fishing](https://user-images.githubusercontent.com/52359871/60394232-77581c80-9b21-11e9-9e99-78c4e0980b19.PNG)

**Comment by Jezzawar** [comment]
I believe this like other profession and skill gain are boosted this is not not a bug but an intended design for player to test things faster without being boosted by a gm

**Comment by snat99** [comment]
Alright, I wasn't aware of this. Apologies all.
