### ISSUE TITLE
AUCTION HOUSE

### ISSUE THREAD

**Issue by mantiblades** [elysium-project/tbc-bug-tracker#709]
**Summary:** 
2 Items sold in auction house show up in mail as amount pending . So buyer receives item but seller's payment shows pending.
![image](https://user-images.githubusercontent.com/52470199/60732574-40a64b80-9eff-11e9-84d1-ec0710914635.png) 
 
![image](https://user-images.githubusercontent.com/52470199/60732799-d6da7180-9eff-11e9-840d-fe2dc0d77147.png)

**Steps to Reproduce:** 

**Expected Results:** 

**Actual Result:**

**Additional Information:**

**Comment by mantiblades** [comment]
Still have not received payment for items in above pics that were sold in auction house and today again same thing payment pending here is pic . 
![image](https://user-images.githubusercontent.com/52470199/60759872-cc43d900-9fe0-11e9-84d5-bdf6b771e88a.png) So is this a hack by players or a bug?

**Comment by mantiblades** [comment]
Again I am not receiving payment for items I have sold in the auction house and none of my issues have been addressed. 
![image](https://user-images.githubusercontent.com/52470199/60775067-6e8fb980-a0d2-11e9-9752-b02a1485abbd.png)

**Comment by Ziggy-QA** [comment]
@mantiblades Did you receive payment at the indicated time? Or did the payment disappear forever?

**Comment by mantiblades** [comment]
Disappeared this is a recurring problem

**Comment by Ziggy-QA** [comment]
This should be fixed now.
