### ISSUE TITLE
RP event in "To Catch a Thistlehead" bugged

### ISSUE THREAD

**Issue by AfterShave** [elysium-project/tbc-bug-tracker#716]
**Summary:** 

Quest "To Catch a Thistlehead" (https://tbc-twinhead.twinstar.cz/?quest=10570) bugged out when I tried to do it.  I died during the RP event and this seems to have bugged out the NPC "Envoy Icarius". Scripted event could not be reset, even by abandoning the quest and as of this moment I don't see a way to complete the quest. 

**Steps to Reproduce:** 
1. Start the quest  
2. Plant "Bundle of Bloodthistle" at the end of the bridge
3. Wait for the 2 NPCs to appear
4. Die somehow, I attacked the mounted NPC and was 1 shoted
5. Come back to find "Envoy Icarius" alone, unable to be attacked

**Expected Results:** 
NPC "Envoy Icarius" becomes attackable after the RP event.

**Actual Result:**
NPC "Envoy Icarius" cannot be attacked after the RP event. 

**Additional Information:**

Since I cannot reset the scripted event, I do not know whether or not it was my dying that bugged out the script. The scripted event itself could just be broken even without any dying. 

**UPDATE**
After a server restart the NPC despawned and I was able to successfully re-do the RP event and thus the quest (didn't die during the RP this time obviously). So it seems like it was indeed the dying that bugged out the event, strongly suggest this be fixed since the bug can prevent the entire server from doing the quest until a server restart

**Comment by AfterShave** [comment]
It's been 24 hours and "Envoy Icarius" is still where he was and the quest remains impossible to complete

**Comment by pebeto** [comment]
The bug is present right now. Did the developers fixed it?
