### ISSUE TITLE
Nat Pagle, Angler Extrema

### ISSUE THREAD

**Issue by Madmattes123** [elysium-project/tbc-bug-tracker#739]
**Summary:*after 200+ fish still no drop of a rare fish.* 

**Steps to Reproduce:** 

**Expected Results:** 

**Actual Result:**

**Additional Information:**

**Comment by boban33** [comment]
Experienced the same issue.

**Comment by pauvas** [comment]
https://tbcdb.com/?quest=6607
been fishin for >3 hours , still no catch. even went to Ogrimar to pick firts part repicked the q at dustwallow , and still nothing

**Comment by danhalen01** [comment]
Also not working for me.. the quest fish are not able to be caught in the designated locations.
