### ISSUE TITLE
Character stuck!

### ISSUE THREAD

**Issue by Lunasina** [elysium-project/tbc-bug-tracker#743]
**Summary:** 
All characters that were copied over are stuck, cannot cast spells, and I cannot even log out of the game. Please help!
**Steps to Reproduce:** 

**Expected Results:** 

**Actual Result:**

**Additional Information:**

**Comment by Ziggy-QA** [comment]
Try and leave your guild @Lunasina , If that works, then the issue is your guild has too many players in it.

**Comment by Lunasina** [comment]
Thank you!
