### ISSUE TITLE
Guild charter

### ISSUE THREAD

**Issue by Posetdon731** [elysium-project/tbc-bug-tracker#744]
**Summary:** 

**Steps to Reproduce:** 

**Expected Results:** 

**Actual Result:**

**Additional Information:**

**Comment by Posetdon731** [comment]
Не работает Хартия в Wow 2.4.3. нельзя использовать ее.
The charter does not work in Wow 2.4.3. You cannot use this

**Comment by saltyqa** [comment]
You can register a guild, but cannot open it to allow others to sign.

**Comment by Posetdon731** [comment]
Ну так для создания гильдии и надо подписать ее, а она не открывает для подписи, это и не работало. Проблема то так и не решена(Well, to create a guild, you need to sign it, but it does not open for signature, this did not work.  The problem is still not resolved)

**Comment by TinyChuck** [comment]
Confirming that this is still an issue. You can move the charter in your bags, you can delete the charter (which it will ask if you want to delete the "Guild Charter"), but you cannot open it via macro nor by clicking. Writing here to avoid opening a new issue thread.
