### ISSUE TITLE
Level 10 Bloodelf Warlock Quest "The Stone" Incompletable

### ISSUE THREAD

**Issue by Xqwizit** [elysium-project/tbc-bug-tracker#758]
**Summary:** 
-I am able to open the stone and look at the quest where i can push the "complete quest" button but only after i have chosen my reward, 1 item, before selecting I get the error "no reward selected" and after I select the reward "Voidstone" I get the error "internal bag error"

**Steps to Reproduce:** 
-constant

**Expected Results:** 
-It looks to be a quest that is just turned in without selecting the reward you just obtain the stone when clicking quest complete.

**Actual Result:**
-listed in summary

**Additional Information:**
-I dont know if this video was live or not but the only interaction I found https://youtu.be/n680Ov8JrBo starts at 3:18

**Comment by Gibblewilt** [comment]
GM confirmed.

**Comment by SilvioDoMine** [comment]
Confirmed, and this is very seriously since we can't get the void

**Comment by Sarelis** [comment]
Confirmed. I have tried abandoning it and deleting the WDB still the issue remains. No void is sad days!

**Comment by Prestly** [comment]
This still didn't get fixed. much regret making a blood elf.

**Comment by Thalminior** [comment]
it is now working for me
