### ISSUE TITLE
Quest : Zapping Giants

### ISSUE THREAD

**Issue by itipou** [elysium-project/tbc-bug-tracker#760]
**Summary:** the quest "Zapping Giants" in Feralas is bugged.

**Steps to Reproduce:** Zap the giants with the quest's device.

**Expected Results:** Giants shrink down and aren't elite anymore.

**Actual Result:** Nothing happens

**Additional Information:**

**Comment by RandomUserOfInternet** [comment]
Same issue with following quests.
