### ISSUE TITLE
player closed tickets will re-open at server restarts

### ISSUE THREAD

**Issue by Gibblewilt** [elysium-project/tbc-bug-tracker#770]
**Summary:** 

When a player creates a support ticket, then finds out it is no longer needed and closes it. It'll reappear once the server is restarted.

**Steps to Reproduce:** 

Create a Gamemaster help request ticket. Close it, Restart server.

**Expected Results:** 
Ticket is closed forever when the player closes or abandons it.

**Actual Result:**

Ticket is reopened, likely due to the player's actions not closing it in the ticket system at all.

**Additional Information:**

**Comment by Ziggy-QA** [comment]
Should be fixed now. (lets hope)
