### ISSUE TITLE
Plagued Lands: Cannot trap Rabid Thistle Bear

### ISSUE THREAD

**Issue by skillywilly** [elysium-project/tbc-bug-tracker#771]
**Summary:** 
The Trap doesn't activate.

**Steps to Reproduce:** 
Place the trap and have ther bear run through the trap.

**Expected Results:** 
Bear should be trapped.

**Actual Result:**
Bear isn't trapped.

**Additional Information:**
I tried it as a druid, friends of me (priest and hunter without pet) also couldn't trap a bear.

**Comment by Ziggy-QA** [comment]
Not enough information here. I have no idea what your talking about. Name of the quest, name of the NPC, and whatever item you are using to "trap" the bears would be helpful.

**Comment by skillywilly** [comment]
> Not enough information here. I have no idea what your talking about. Name of the quest, name of the NPC, and whatever item you are using to "trap" the bears would be helpful.

I updated the description with the requested information. Please reopen this issue.
