### ISSUE TITLE
Quest: Avruu’s Orb

### ISSUE THREAD

**Issue by boban33** [elysium-project/tbc-bug-tracker#774]
**Summary:** 
 Bringing the quest item to the orb and starting the dialogue does not spawn the elemental, required to finish the quest.
**Steps to Reproduce:** 
Gather quest item, click in orb.
**Expected Results:** 
Elemental spawns, that finishes the quest once defeated.
**Actual Result:**
Nothing happens after clicking on the orb and starting the dialogue.
**Additional Information:**

**Comment by Ziggy-QA** [comment]
#419 This is a duplicate please put all info in this bug report
