### ISSUE TITLE
Bride of the Embalmer

### ISSUE THREAD

**Issue by Seanhcampbell8** [elysium-project/tbc-bug-tracker#776]
**Summary:** 
Quest issue: Bride of the Embalmer quest - Darkshire
Eliza hostile to player, but cannot be attacked. Error message "invalid target" on hostile ability.
Multiple Eliza's spawn after each attempt. 

**Steps to Reproduce:** 
Attempt to complete the quest.

**Expected Results:** 
Eliza spawn from mound of dirt, kill.

**Actual Result:**
God-Mode Eliza and the Elizaette's aren't having none of your sass.

**Additional Information:**
Contact "Addshot" in game if needed. Alliance faction.

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
