### ISSUE TITLE
Bugged vendor in Tranquillien

### ISSUE THREAD

**Issue by Kschak** [elysium-project/tbc-bug-tracker#778]
**Summary:** 
Vendor called Provisioner Vredigar should sell reputation earned items. Instead of several types of items there are only 2 armors avaible _leather and mail ones.
**Steps to Reproduce:** 

**Expected Results:** 

**Actual Result:**

**Additional Information:**

**Comment by nickpelone** [comment]
See also: https://github.com/elysium-project/tbc-bug-tracker/issues/762#issue-479355190

[Provisioner Vredigar (NPC: 16528)](https://tbcdb.com/?npc=16528)

Correct vendor table:
https://tbcdb.com/?npc=16528
