### ISSUE TITLE
Guild Charter

### ISSUE THREAD

**Issue by arskucherov** [elysium-project/tbc-bug-tracker#779]
**Summary:** Guild charters are broken

**Steps to Reproduce:** Come to guild master and buy a new charter

**Expected Results:** You got a guild charter that you can open and read, also you can ask unguilded players to sign it via right clicking their portraits

**Actual Result:** Nothing of that is working. Item is not usable and you can't invite someone to sign it

**Additional Information:**

**Comment by Ziggy-QA** [comment]
Should be fixed after next restart if not already.
