### ISSUE TITLE
Quest "Into Occupied Territory" - quest item not spawns

### ISSUE THREAD

**Issue by kolgarlol** [elysium-project/tbc-bug-tracker#787]
2 scrolls - spawns, but Night Elf Plans: An'Owyn - does not.

**Comment by Ziggy-QA** [comment]
It would be nice to have a little more info.

How long did you wait for the scroll to spawn? Was their other players nearby trying to do the same thing? Please respond.

**Comment by SilvioDoMine** [comment]
@Ziggy-QA this issue should be reopened. This quest is indeed bugged, the mentioned object don't respawn. I've been waiting for 45 minutes+, and there was alot of people nearby waiting as well.
