### ISSUE TITLE
Quest: Cruel’s Intentions

### ISSUE THREAD

**Issue by boban33** [elysium-project/tbc-bug-tracker#788]
**Summary:** 
There is no way to pick up the quest Cruel’s Intentions in Theallmar.
**Steps to Reproduce:** 

**Expected Results:** 

**Actual Result:**

**Additional Information:**

**Comment by Ziggy-QA** [comment]
There is, you just have to be level 63.

**Comment by pichu666** [comment]
im having this problem you should be able to pick up the quest after Doorway to the Abyss and be level 58. did the quest with my friend he was able to pick up quest but my hunter was not.
