### ISSUE TITLE
Learning “Smelt Adel Iron” impossible

### ISSUE THREAD

**Issue by boban33** [elysium-project/tbc-bug-tracker#789]
**Summary:** 
Some players (including me) experienced a bug, where it was not possible to learn to smelt fel iron in Thrallmar.
**Steps to Reproduce:** 

**Expected Results:** 

**Actual Result:**

**Additional Information:**

**Comment by Ziggy-QA** [comment]
The trainer is simply missing the option. This will be fixed as soon as higher priority issues are fixed. You can try other trainers around outland in the meantime.

**Comment by boban33** [comment]
Thanks for pointing out a workaround, Ziggy! :)

**Comment by boban33** [comment]
@ziggy: By the way, where would I find another TBC mining trainer, who can teach me that skill?

**Comment by SenjiuKanuba** [comment]
For scryers: https://www.wowhead.com/npc=33640/hanlir
For aldor: https://www.wowhead.com/npc=33682/fono

If those are broken too there is no way to learn smelt fel iron right now.

**Comment by boban33** [comment]
Tried to find the scryer one but apparently, the npc is not even implemented to the game (yet?)...

**Comment by Ziggy-QA** [comment]
Should be fixed now
