### ISSUE TITLE
Sporefish School (object 182953)

### ISSUE THREAD

**Issue by Tolle44** [elysium-project/tbc-bug-tracker#794]
**Summary:** 
When fishing from Sporefish Schools in Umbrafen Lake, Zangarmarsh, only the first catch yields loot. After the first catch the loot table will appear empty altough the pool will deplete as normal (after a few "catches").

I am using Bright Baubles and the Nat Pagle's Extreme Angler FC-5000 rod.

**Steps to Reproduce:** 
Fish from a Sporefish School in the Umbrafen Lake (this might be the case for more schools).

**Expected Results:** 
There should always be a fish in the loot table on successful catch.

**Actual Result:**
There is only a fish in the first loot when fishing in the pool, all consecutive catches yield no fish despite depleting the pool.

**Additional Information:**

**Comment by idefix2121** [comment]
This also happens when fishing fishschools and floating wreckage in Tanaris

**Comment by Tsukumogamiru** [comment]
This happens with all the pools in the game as I noticed. I can't even see loot table. Looks like bag because I don't get message that fish got away.

**Comment by invwax** [comment]
#843
