### ISSUE TITLE
Hunter's Viper Sting

### ISSUE THREAD

**Issue by Trigerxx** [elysium-project/tbc-bug-tracker#796]
Viper Sting working not correctly. It is only burning enemies mana, but no draining

**Comment by SenjiuKanuba** [comment]
I don't think you're supposed to get the mana it drains. I think that was added in WotLK. The tooltip then also changed.

TBC:
Stings the target, draining 1108 mana over 8sec. Only one Sting per Hunter can be active on any one target.

WotLK:
Stings the target, draining 1% mana over 8sec (up to a maximum of 1% of the caster's maximum mana), and energizing the Hunter equal to 300% of the amount drained. Only one Sting per Hunter can be active on any one target.

I must say though, that I didn't play a hunter for long in vanilla / tbc.

**Comment by boban33** [comment]
I am quite sure that you are not supposed to generate mana from viper sting in tbc.

**Comment by espinozatbc** [comment]
acording to tbc db spell is a mana "leech" wich means it should transfer to caster 

 https://tbc-twinhead.twinstar.cz/?spell=3034

also note thats how it worked on vainilla server and tooltip remains the same as then

**Comment by SenjiuKanuba** [comment]
I've talked to hunters I raided with on Northdale and according to them it doesn't regenerate your mana.
And I don't finy any mentions of getting mana back from it pre-2009. Guides start mentioning that as a way to get mana in 2009 but WotLK was released in November 2008 so I'm fairly certain that it only applies to WotLK.
