### ISSUE TITLE
Blade Flurry

### ISSUE THREAD

**Issue by ljjumper** [elysium-project/tbc-bug-tracker#808]
**Summary:** The ability "Blade Flurry" is doing way less damage to nearby enemys than expected. I know someone already reported this issue some days ago, but instead of only doing 70% of the expected damage (mentioned in the first report), it barely removes 30% oft the hp from the nearby mobs, while killing the main target entirely. 

**Steps to Reproduce:** 
-Stack up at least two mobs
-Cast "Blade Flurry" and examine the damage

**Expected Results:** Same damage should be applied to nearby enemys as on the main target

**Actual Result:** Perhaps 25-30% of the main damage dealt to nearby enemy´s

**Additional Information:**Would be nice if this could be fixed in the near future since "Blade Flurry" is one of the core abilities from rogues to deal (aoe-)damage

**Comment by Huntitude** [comment]
I noticed this too...

**Comment by Ziggy-QA** [comment]
Blade flurry has two attributes:

It cannot crit
It does not scale with bonus damage effects

This seems pretty intentional so im gonna close this.
