### ISSUE TITLE
A few issues I've noticed

### ISSUE THREAD

**Issue by Naigio** [elysium-project/tbc-bug-tracker#816]
**Summary:** 
Aspect of the Viper
Hunter Traps
Health regen & mana regen
**Steps to Reproduce:** 
Aspect of the Viper: I've tried it in a few places, dungeons, outside in questing areas, never seems to buff my mana regen, tried relogging tried taking off and on again no nothing
Hunter Traps: As I lay them out they take 1-3 seconds before they activate, so they're at least beyond useless in pvp. Try putting one down at the feet of a mob and watch it whack you a few too many times before it activates and I more or less need the second ready at the bat because it breaks way too easily
Health & mana regen: Barely regain any mana/health while out of combat
**Expected Results:** 
Aspect of the Viper: Gib dat mana
Hunter Traps: I expect them to activate instantly and break less
Health & Mana: Should have more than 10 hp per 5 second
**Actual Result:**
AotV:  No apparent mana regen increase
Hunter traps: takes way too long to activate and break way too easily
Health & Mana Regen: waiting 20 mins outside of combat for your mana & health to fill a quarter aint fun
**Additional Information:**

**Comment by SenjiuKanuba** [comment]
I think all those things act the way they should.

Viper Sting in vanilla and TBC is not supposed to regenerate your mana as a hunter. You might confuse it with aspect of the viper or with a later version of viper sting introduced in WotLK.
Traps have a slight delay before they work. They changed that at some later point but in Vanilla and TBC the traps have something like a 2sec delay.
Source: https://eu.battle.net/forums/en/wow/topic/7257098141
https://us.battle.net/forums/en/wow/topic/20769757520
Health regen is supposed to be 25% of your spirit + 6 every 2 seconds. So yes, you should have more than 10 HP every 5sec. Do you really have less regeneration? My shaman definitely has a normal health regeneration rate.
Source: http://wow.allakhazam.com/wiki/HP_Regen_%28WoW%29

I get the feeling that you're comparing the reported problems to the way hunters work in retail, not how they used to work in TBC.

**Comment by Naigio** [comment]
-Aspect OF THE VIPER- not Viper Sting

Traps can not seriously have had an delay during TBC because it would render them useless in pvp and hunters even worse off against melees but whatever

Seems Health Regen is fine then too

I'm comparing them to how it worked in Project Elysium Vanilla, not Retail

**Comment by Senjiu** [comment]
Whoops, sorry then about Aspect of the Viper.

Fairly certain about the traps, though. We'll see what version of traps (delayed or not) will be correct in 12 days, I guess, when Blizzard releases classic. :-)

**Comment by Naigio** [comment]
Yea, I don't doubt you on it at all, it's just it activated at least near instantly on project vanilla, so sad to see it go is all.

**Comment by Ziggy-QA** [comment]
I've had to address the hunter trap issue to many hunters that think they know better when the fact of the matter is this:

![image](https://user-images.githubusercontent.com/45450044/63188840-842cc300-c030-11e9-8e92-b66f78c4e2dd.png)

Everything you listed here appears to be working fine. Closed
