### ISSUE TITLE
Not working Quest: Felsworn Gas Mask

### ISSUE THREAD

**Issue by Myriald** [elysium-project/tbc-bug-tracker#817]
**Summary:**
Quest: https://tbcdb.com/?quest=10819
 Impossible to interect with the communicator.

**Steps to Reproduce:** 
Equip the Mask, move to the communication device. Nothing happens.

**Expected Results:** 
Possible interaction with the device

**Actual Result:**
nothing, no interaction

**Additional Information:**
added a screenshot of the non working device
https://gyazo.com/f59de34e36c1913ad5042795d34751ee

**Comment by asaphlive** [comment]
confirmed.. issue is at hand.. communicator missing at the spot.
