### ISSUE TITLE
After last crash i lost all of my arrow stacks. They just got deleted lol! 

### ISSUE THREAD

**Issue by Zondy** [elysium-project/tbc-bug-tracker#818]
**Summary:** 

**Steps to Reproduce:** 

**Expected Results:** 

**Actual Result:**

**Additional Information:**

**Comment by kolgarlol** [comment]
ya, I had lost my Ramparts spell power ring this evening!!!

**Comment by saltyqa** [comment]
Closing - this was an issue with the databases, which has been resolved. Please note any items lost in a ticket to GMs
