### ISSUE TITLE
Shadow Labs Key

### ISSUE THREAD

**Issue by Shaplex** [elysium-project/tbc-bug-tracker#821]
**Summary:** 

Final boss in sethekk halls does not drop chest that contains Shadow Labs key

**Steps to Reproduce:** 

Complete Sethekk Halls

**Expected Results:** 

Final boss should drop chest with shadow labs key.

**Actual Result:**

Final boss does not drop chest with shadow labs key.

**Additional Information:**

Video clip: - no chest https://clips.twitch.tv/ExcitedConfidentOxTakeNRG

**Comment by SenjiuKanuba** [comment]
It is not a drop.

https://wow.gamepedia.com/The_Talon_King%27s_Coffer

**Comment by Ziggy-QA** [comment]
Chest was removed as part of progression gating, but the key is still supposed to drop from the boss. We applied a fix that enabled the Talon Kings Coffer since its the same outcome anyways.
