### ISSUE TITLE
Задание Finding the Antidote

### ISSUE THREAD

**Issue by AlexGloom2019** [elysium-project/tbc-bug-tracker#822]
Задание
https://tbcdb.com/?quest=813
Не выпадает необходимый предмет 
https://tbcdb.com/?item=4886
из квестовых монстров, таких как 
https://tbcdb.com/?npc=3127
https://tbcdb.com/?npc=3226
данная проблема не позволяет продолжить цепочку заданий.

**Comment by kolgarlol** [comment]
I had completed this quest today, man, it is works

**Comment by AlexGloom2019** [comment]
нет, это не так. зачистил все местность. не выпало ни одной вещи из задания.

**Comment by kolgarlol** [comment]
ну я кв сделал

**Comment by AlexGloom2019** [comment]
после отказа заново не выдается((( 

вообще не работает
