### ISSUE TITLE
Dustwallow Marsh quest NPCs missing, turtles are bugged

### ISSUE THREAD

**Issue by owletrowlet** [elysium-project/tbc-bug-tracker#823]
**Summary:** I've only attempted a few quests in Dustwallow Marsh- Help for Mudsprocket, Defias in Dustwallow?, and Mudrock Soup and Bugs. NPCs are missing in Mudsprocket, the only one there is the flight master so it is impossible to complete a quest there. There are no NPCs on the small island where you would get the Defias Orders, so it is impossible to obtain them to complete the quest since the objective is to get them from Garn Mathers. While attempting to kill the Mudrock turtles for their tongues, turtles in the water will become hostile and target you after you attack them but they will stay in the water and are unable to be killed.

**Steps to Reproduce:** Accept quests "Help for Mudsprocket", "Defias in Dustwallow?", and "Mudrock Soup and Bugs". Attempt to turn in the first quest, travel to the small island to attempt to find Garn Mathers for the second, and attempt to attack turtles in the water for the third.

**Expected Results:** NPCs should be in place, turtles should be able to be fought and killed.

**Actual Result:** NPCs are missing and the turtles remain in the water evading all attacks while being hostile and targeting your character, keeping you in combat.

**Additional Information:**

**Comment by gdossantos87** [comment]
Most quest in that zone don't work properly

**Comment by Ziggy-QA** [comment]
Mud sprocket is not implemented until 2.3, Closed.
