### ISSUE TITLE
(Updated) Paladins resurrection quest "The Tome of Divinity" is bugged

### ISSUE THREAD

**Issue by Komuccap** [elysium-project/tbc-bug-tracker#824]
Impossible to use "Symbol of Life" on NPC Hezen Faulk, says "out of range".
Error persists even if there is no actual target at all.

**Comment by IvanDanshin** [comment]
Quest working

**Comment by jedediah1** [comment]
Quest not working.

**Comment by xenocide21** [comment]
Not working.

**Comment by nadeauk6012** [comment]
Same not working

**Comment by Komuccap** [comment]
Update 27.08.2019: It is now possible to resurrect Hezen Faulk, but there is no actual way to turn in the quest (and take the following one respectively).

**Comment by Komuccap** [comment]
Issue fixed.
