### ISSUE TITLE
КЛЮЧИ ЗА РЕПУ АДМИНЫ УГАДАЙТЕ ПО СКРИНАМ ЧТО НЕ ТАК 

### ISSUE THREAD

**Issue by vargraf** [elysium-project/tbc-bug-tracker#832]
https://cdn.discordapp.com/attachments/549556832377634826/611680310379151379/unknown.png
https://cdn.discordapp.com/attachments/549556832377634826/611680505951420487/unknown.png
https://cdn.discordapp.com/attachments/549556832377634826/611686109889560597/unknown.png
вы хоть тестите что делает это элементарно и самы черт побери пустяковый баг сколько уже можно

**Comment by IvanDanshin** [comment]
Работает нормально для меня. Не могу воспроизвести баг. Возможно проблема на стороне Вашего игрового клиента.
https://i.gyazo.com/b71a6c04bc7db678703c88d9f0c5506c.mp4

**Comment by vargraf** [comment]
да только вопрос как влияет КЛИЕНТ НА ПОКУПКУ У ВЕНДОРА КОТОРАЯ ИДЕТ ЧЕРЕЗ СЕРВер ( остальные вещи скупил норм )

**Comment by vargraf** [comment]
по вашей логике каждый может себе в клиенте образно ( нарисовать шмот ) и все будет ок ( но так это не работает )

**Comment by vargraf** [comment]
и я все так же не могу  купить ключи ( тогда добавте мне их в сумку сами ) ( репа то есть )

**Comment by vargraf** [comment]
https://cdn.discordapp.com/attachments/549556832377634826/611815379832143883/unknown.png скрин с серверным временем

**Comment by vargraf** [comment]
Эм але а как вы баги восроизводите 
![image](https://user-images.githubusercontent.com/54158078/63149263-428a2100-c00c-11e9-94dd-2748b7df57a9.png)
 ( добейте репу до моей и тогда покупайте а не на фул

'v

**Comment by vargraf** [comment]
![image](https://user-images.githubusercontent.com/54158078/63149336-7bc29100-c00c-11e9-9a4f-fa4c623d1295.png)

**Comment by vargraf** [comment]
у вас скорее все прописано что ключ за реверд в файлах ( судя по репу сейчас у вас реверед ) ( а на ключ нада ХОНОРИД )

**Comment by vargraf** [comment]
вы хоть воспроизводите с точностью вам же и скрины скинул для этого

**Comment by xoverdr1vex** [comment]
Чайник, в начале бк репа идет за РЕВЕРЕД. сначала возьми ее, реверед а потом гунди!

**Comment by vargraf** [comment]
чайник я покупаю все вещи ща хонерид кроме ключей и пишет на них ошибку

**Comment by vargraf** [comment]
и в начале идет не реверед

**Comment by vargraf** [comment]
чайник не смущает тебя ничего 
https://cdn.discordapp.com/attachments/549556832377634826/611695511673765918/unknown.png
https://cdn.discordapp.com/attachments/549556832377634826/611695571144540171/unknown.png
https://cdn.discordapp.com/attachments/549556832377634826/611695724001755137/unknown.png
https://cdn.discordapp.com/attachments/549556832377634826/611695802561069113/unknown.png

**Comment by vargraf** [comment]
вот почитай на досуге неуч https://www.igromania.ru/article/10175/Analitika_sistema_reputacii_v_World_of_Warcraft.html

**Comment by xoverdr1vex** [comment]
А я тебе говорю что ты наб и никогда не играл на ритэйле. Этот баг был всегда. И ключи покупались на РЕВЕРЕД хотя в описании и стояло ХОНОРЕД. Это известный баг самого клиента а не сервера. И уж мне точно не нужно рассказывать очередность, я в отличие от тебя не создаю заявку на русском. На почитай

https://wowwiki.fandom.com/wiki/Flamewrought_Key_(Alliance)

Bc icon Patch 2.3.0 (13-Nov-2007): Changed amount of reputation required.
Went from revered to honored.

**Comment by xoverdr1vex** [comment]
Повторюсь, это не баг сервера а клиента. Берешь реверед (Friendly = honored ⇐ revered ⇒  exalted) /// дружелюбие = уважение ⇐ почтение ⇒  превознесение

И будет тебе счастье!

**Comment by vargraf** [comment]
ты сам сказал что это баг !

**Comment by vargraf** [comment]
поэтому я жду своих ключей
