### ISSUE TITLE
Veins for mining are not as they should be

### ISSUE THREAD

**Issue by idefix2121** [elysium-project/tbc-bug-tracker#836]
**Summary:** veins cant be found in usual spots over the world. it seems like that veins appear now in places they werent before or that they have changed to another material: eg thorium vein became mithril. 

**Steps to Reproduce:** run a round in your favorite high level area where you could mine rich thorium veins, thorium and dome truesilver and mithril. I used Burning steppes, i know other people covered other area’s as well

**Expected Results:** you would still be able to find veins at their usual spot

**Actual Result:** no rich thorium veins found or there was mithril vein instead of the rich thorium. Also other spots have now other mineral then what they used to be

**Additional Information:**

**Comment by invwax** [comment]
#658
