### ISSUE TITLE
Quest : Videre Elixir bugged

### ISSUE THREAD

**Issue by itipou** [elysium-project/tbc-bug-tracker#837]
**Summary:**  Can't drop the bait in front of Miblan Snarltooth, thus can't continue with the quest

**Steps to Reproduce:** Go in front of Miblan Snarltooth and click on the bait item

**Expected Results:** you drop the bait, Miblan Snarltooth comes to eat it. The door behind him opens and you can get the Evoroots.

**Actual Result:** can't drop the bait. the game says : "requires Miblan Snarltooth"

**Additional Information:**

I could actually drop the bait in one place, right behind Miblan Snarltooth. But the NPC doesn't react. Nothing happens.

Edit : Actually, you can get through the wall behind the NPC. Like a ghost. But that is not how he should be.

**Comment by idefix2121** [comment]
Did you try tonjuts pass him buy and run into the space? Cause in vanilla you also didnt need to use the bait, you just passed him by and went to get that evoroot
