### ISSUE TITLE
Guild Charters (Status Update)

### ISSUE THREAD

**Issue by TinyChuck** [elysium-project/tbc-bug-tracker#845]
**Summary:**

Guild charters remain broken. Unable to interact with them in any way (macros, clicking). Charters can be deleted, repurchased and moved around in the bags. Cannot be placed on the action bar.

**Steps to Reproduce:**

Purchase a guild charter from a guild master.

**Expected Results:**

Right-clicking to open a quest-styled page that contains a list of signatures needed to form a guild.

**Actual Result:**

Nothing.

**Additional Information:**

N/A or available upon request.

**Comment by Ziggy-QA** [comment]
#779 duplicate. Please add to the existing issue instead of making a new one.
