### ISSUE TITLE
Ending Their World

### ISSUE THREAD

**Issue by xoverdr1vex** [elysium-project/tbc-bug-tracker#848]
**Summary:** Cant finish escort quest in Draenei Start Location because Demolitionist Legoso doesnt move

**Steps to Reproduce:** Follow and protect Demolitionist Legoso as he attempts to destroy the Vector Coil and slay Sironas.

**Expected Results:** After starting of quest NPC should start to move to the Vector Coil

**Actual Result:** He doesnt move, but keep standing

**Additional Information:**

**Comment by IvanDanshin** [comment]
Fixed. Thanks for report!
