### ISSUE TITLE
Cross Faction Communication

### ISSUE THREAD

**Issue by Cyrulaen** [elysium-project/tbc-bug-tracker#849]
Alliance and Horde members can communicate by custom emoting with "/me XXXXXXXXX"

**Comment by bush5150** [comment]
If I remember correctly, this was how it was in Vanilla and maybe in TBC.  Blizz put a stop to it, but early on, we could do that (it's been so long, I can't remember when this was done).  I know hunters were also able to do this by renaming pets.  Priests could MC a rival faction player and communicate using the /me or /say command line.
