### ISSUE TITLE
Grisnath Orbs Do Not Spawn - Blade's Edge Mountains

### ISSUE THREAD

**Issue by Drissin** [elysium-project/tbc-bug-tracker#855]
**Summary:** Part of the quest Exorcising the Trees doesn't work.  Grisnath orbs do not spawn correctly.

**Steps to Reproduce:** 
Take quest.  No orb spawn in area.

**Expected Results:** 
Orbs spawn in veil area.

**Actual Result:**
No orbs spawn in veil area.

**Additional Information:**
N/A

**Comment by pauvas** [comment]
confirm this , no orbs , other item works from birds but orbs do not spawn
