### ISSUE TITLE
Healthregeneration after leaving combat unusual slow without eating

### ISSUE THREAD

**Issue by idefix2121** [elysium-project/tbc-bug-tracker#856]
**Summary:** after you leave combat in outland you expect that your health would regenerate in usual speed as it was before without eating, so that if you are walking a bit, after that your health is back up at least by some good percentage.

**Steps to Reproduce:** fight in outland a mob and get hit some bit that your health is down to also like 50% at least. Beat the mob or run out of combat. Look at health bar and its regeneration speed being really low

**Expected Results:** after the fight yout health will go up faster then it is now doing

**Actual Result:**
If you forget to eat before attacking a mob for which you have mounted up ridden over to him for like 20 secs, your health is still doen like it was when you left combat

**Additional Information:**

**Comment by Senjiu** [comment]
Can you give us some numbers? Health regeneration isn't supposed to be fast.

According to http://wow.allakhazam.com/wiki/HP_Regen_%28WoW%29 your health regen every 2s should be between 10% and 50% of your spirit (+6 or so) depending on your class.

That means for me, as a shaman with roughly 4500 HP and 150 Spirit or so, I would regenerate 22 HP every 2 seconds. That means it takes about 440 Seconds aka 7 Minutes to regenerate my health to full just from passive regeneration. 20 seconds of regeneration would be barely visible on my healthbar.

**Comment by idefix2121** [comment]
I guess then it is correct the health regeneration. Fir me it felt like it was do mich slower as on vanilla. Lets close it then for now. Thanks for the explanation. Sorry you had to put valuable time in it

**Comment by Senjiu** [comment]
Hahaha, I'm not a dev, I'm just a regular player. No valuable time went into it. ;-)
