### ISSUE TITLE
Rogue quest Horde bugged deep cover the npc has no question mark for quest to be turned in!

### ISSUE THREAD

**Issue by squishymcpuff** [elysium-project/tbc-bug-tracker#864]
**Summary:** 
the npc  even after proper quest procedure does not interact with me I have him as a friendly target after 2 flare shots and a salute yet no work.
**Steps to Reproduce:** 
please help
**Expected Results:** 
to be able to complete the quest
**Actual Result:**

**Additional Information:**

**Comment by Zolzar** [comment]
Can confirm. 2 flares then /salute will change him from aggressive to friendly, but you can only target him. You cannot interact with him and he has no quest indicators above his head while in the friendly state. Can be reproduced even if the quest is dropped and retaken.

**Comment by Stenns** [comment]
Same problem for me. Any fix about it yet?

Could any GM be so kind and grant my blood elf rogue (named Stenns) "Poisons" skill? This quest is still bugged and this looks to be the only way around it for the time being.

**Comment by magnetic9** [comment]
Same here. Couldn't complete it with my rogue Bassie, lvl 41 blood elf.

**Additional information:** Tried the process 5 times, with the same result as the above players (Fizzule turns friendly but doesn't give dialogue prompt). Tried abandoning the quest, killing him and waiting him to respawn, picking the quest again, but the result is always the same.

To be a rogue without poisons is... bad. It is really bad.

**Comment by invwax** [comment]
Any update or any workarounds? Rogue named Kalych
