### ISSUE TITLE
Quest : getting donw to business

### ISSUE THREAD

**Issue by Nasherrr** [elysium-project/tbc-bug-tracker#868]
**Summary:** 
After collecting the 8 nether dragon essences, when you want to re-open the ethereal teleport pad to make the NPC appear to turn in the quest, the pad doesn't make the NPC appear. Message from the pad: "This etherreal teleport pad is covered in brightly colored buttons and switches, but seems to have fallen into disuse."
**Steps to Reproduce:** 
Go to celestial ridge in netherstorm, accept the quest "getting donw to business", collecte 8 nether dragon essence from near dragonkin, try to turn the quest.
**Expected Results:** 
NPC appear from pad and you're able to turn the quest.
**Actual Result:**
No NPC appear and pad useless. impoosible to take the next part.
**Additional Information:**
Fellow up of the "A Not-So-Modest Proposal" quest.
NPC is "Wind Trader Marid"

**Comment by IvanDanshin** [comment]
Quest working. Quest taker is:
https://www.wowhead.com/npc=20154/shrouded-figure
located near this pad...
