### ISSUE TITLE
Nat Pagle Angler Extreme Bugged

### ISSUE THREAD

**Issue by danhalen01** [elysium-project/tbc-bug-tracker#874]
**Summary:** The four quest fish in Nat Pagle, Angler Extreme quest#6607 are not obtainable at the confirmed cords after hundreds of attempts, preventing players from maxing out their fishing skill. The four fish are Feralas Ahi item#16967, Misty Reed Mahi Mahi item#16970, Sar'theris Striker item#16968, and Savage Coast Blue Sailfin item#16969

**Steps to Reproduce:** Caught over 200 fish in each of the confirmed cords with not a single quest fish given. This is well beyond the normal drop rate and is clearly bugged.

**Expected Results:** Obtain the four fish required for the quest

**Actual Result:** The four fish do not drop as intended after hundreds of attempts in each of the known cords.

**Additional Information:** I am not the only one who has had this problem but the other bug report on GitHub was so poorly written that I figured I would report it myself.

**Comment by elithys** [comment]
Yes please fix this it is very important for my health and well being

**Comment by testymouse** [comment]
I agree spent it is triggering my ocd

**Comment by IvanDanshin** [comment]
Soon will be fixed!

**Comment by danhalen01** [comment]
fixed
