### ISSUE TITLE
Mechanar door closed

### ISSUE THREAD

**Issue by Zinsora** [elysium-project/tbc-bug-tracker#877]
**Summary:** The door behind [Nethermancer Sepethrea](https://www.wowhead.com/npc=19221/nethermancer-sepethrea) which you open by collecting the two crystals which drop off the Gatewatchers closes shortly after you opened it. So if you wipe just once you have to reset the dungeon and run it again.

**Steps to Reproduce:** 

**Expected Results:** The door should stay open

**Actual Result:** It closes and cant be opened again

**Additional Information:**

**Comment by Myriald** [comment]
Had the same issue. We wiped on the bridge before last boss and the door stayed closed.
