### ISSUE TITLE
Quest "Into Occupied Territory" - quest item not REspawns

### ISSUE THREAD

**Issue by kolgarlol** [elysium-project/tbc-bug-tracker#892]
Night Elf Plans: An'Owyn doesnt REspwawns

**Comment by Zinsora** [comment]
True

**Comment by MissKam** [comment]
Summary: An'owyn night elf plan is missing at quest Into Occupied Territory

Steps to Reproduce: Go to the island where the night elves are. You will only be able to find the other 2 plans (1 on the ship and 1 on the island). An'daroth can be actually found at 2 places, next to 2 separate night elves, on the southern side of the island..

Expected Results: It should be 'In a Long Tent at 12,24 on the floor next to the other moonwell to the North.'

Actual Result: It's not there 
![WoWScrnShot_082219_152254](https://user-images.githubusercontent.com/54189537/63519043-8e4c3700-c4f2-11e9-9f7b-b30c7975c526.jpg)


Additional Information: -

**Comment by IvanDanshin** [comment]
Soon will be fixed.
