### ISSUE TITLE
quest cruel's intentions

### ISSUE THREAD

**Issue by pichu666** [elysium-project/tbc-bug-tracker#894]
**Summary:** unable to pick up quest Cruel's intentions on my hunter Umbreons

**Steps to Reproduce:** 
finish quest doorway to the abyss and be level 58 pick up cruel's intentions
**Expected Results:** 

**Actual Result:**

**Additional Information:**did quest doorway to the abyss with friend Cowculas he was able to pick up quest Cruel's Intentions I was not

**Comment by SenjiuKanuba** [comment]
I can't accept the quest either and I also did doorway to the abyss. Other people can get the quest. I am not sure why. I didn't care that much about it as there are many other trinkets to get for me as a damage dealer but it's a problem for tanks, who often wear that trinket until lvl 70.
Character: Spazzle (Troll Shaman)

**Comment by Ziggy-QA** [comment]
You need to be level 63

**Comment by pichu666** [comment]
just hit 63 still can't get quest. most people are able to get it after doing quest "doorway to the abyss" and be level 58
