### ISSUE TITLE
Epic Helmets from Engineering Trainers Missing

### ISSUE THREAD

**Issue by tricornx** [elysium-project/tbc-bug-tracker#895]
**Summary:** 
Epic Helmets from Engineering Trainers **Missing**. Tried several different master engineers in outlands and they should be trainable from all.

**Steps to Reproduce:** 

**Expected Results:** 

**Actual Result:**

**Additional Information:**

**Comment by Ziggy-QA** [comment]
It would help to know exactly what engineering helmets you are talking about. There are plenty after all.

**Comment by Subrias** [comment]
I think he means the 350 skill ones like the tankatronic goggles. Te reason for this would be they weren't added until patxh 2.1 I believe

**Comment by SenjiuKanuba** [comment]
https://www.wowhead.com/item=32494/destruction-holo-gogs are patch 2.1 according to Wowhead. I didn't check the others but I assume that applies to all of them.

**Comment by HamonTim** [comment]
I don't really trust WoWHead when it comes to availability by patch, but goggles are in the 2.1 patch note (https://wowwiki.fandom.com/wiki/Patch_2.1.0)

Engineering
    11 new epic goggles have been introduced at 350 engineering skill and are available from the trainer. They range from cloth to plate, and have a variety of stats to appeal to most talent specs.
