### ISSUE TITLE
Honor Hold Rep vendor

### ISSUE THREAD

**Issue by nafk1450** [elysium-project/tbc-bug-tracker#901]
**Summary:** 
Can't buy rare bullets from quartermaster in HH.
**Steps to Reproduce:** 
Go to the vendor and try to buy them.
**Expected Results:** 
Bullets being there.
**Actual Result:**
No bullets in the shop.
**Additional Information:**

**Comment by SenjiuKanuba** [comment]
https://www.wowhead.com/item=32883/felbane-slugs those?
They were added in Patch 2.1. We are currently playing Patch 2.0.

**Comment by nafk1450** [comment]
Why are CE revered arrows in game then?

**Comment by Senjiu** [comment]
https://www.wowhead.com/item=24412/wardens-arrow

Because it's in patch 2.0

Honestly, you could have answered that question yourself.

**Comment by nafk1450** [comment]
https://www.wowhead.com/item=31949/wardens-arrow

**Comment by nafk1450** [comment]
Same happens with slugs depending on which id you look for its either 2.1 or 2.0

**Comment by Senjiu** [comment]
Huh, you're right, that is confusing.
