### ISSUE TITLE
Quest: Vyletongue Corruption: uncompletable.

### ISSUE THREAD

**Issue by losvtranse** [elysium-project/tbc-bug-tracker#909]
**Summary:** Quest is uncompletable - using "Filled Cerulean Vial" does nothing.

**Steps to Reproduce:** Gain "Filled Cerulean Vial" - use it on the specific plants inside Mauradon (orange entrance)

**Expected Results:** "Filled Cerulean Vial" on use makes a cone aoe that should destroy the plants and spawn 2-3 Vylestem Vines, needed for completing the quest.

**Actual Result:** "Filled Cerulean Vial" does nothing.

**Additional Information:**

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
