### ISSUE TITLE
Secret of the Circle

### ISSUE THREAD

**Issue by Flinvoltx** [elysium-project/tbc-bug-tracker#915]
**Summary:** Secret of the Circleis broken, serpent statues doesn't glow

**Steps to Reproduce:** Pick up quest, try to activate them in order S, N, SW, SE, NW, NE.

**Expected Results:** The Statues just Glow when you click them they dont turn or do something else.

**Actual Result:** Nothing

**Comment by HamonTim** [comment]
Netherwing is supposed to be 2.1 (like Ogri'la / Skettis)

**Comment by Flinvoltx** [comment]
> Netherwing is supposed to be 2.1 (like Ogri'la / Skettis)

and this is vanilla quest

**Comment by HamonTim** [comment]
I'm sorry I'll remove my comment.
Was not written in the right report :'(.

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
