### ISSUE TITLE
Heroic Badges Vendor missing a item: https://de.wowhead.com/item=29272/kugel-des-seelenfressers

### ISSUE THREAD

**Issue by Marckotobelo** [elysium-project/tbc-bug-tracker#917]
**Summary:** https://www.wowhead.com/item=29269/sapphirons-wing-bone Patch 2.1.0 available for Heroic Badges
https://de.wowhead.com/item=29272/kugel-des-seelenfressers also Patch 2.1.0 seems to be missing

**Steps to Reproduce:** go to the vendor and browse though the items, realizing the only needed item for shadows is missing

**Expected Results:** go to the vendor and be happy

**Actual Result:** go to the vendor and be mad

**Additional Information:** all items are patch 2.1.. the server is running on 2.0 i thought? why dont the horde get their 2.1 wappon from honorhold then while alliance can alrdy buy it?

**Comment by Senjiu** [comment]
I'd say the error is that the wing bone is available when it shouldn't be. Not that the orb is missing. We are on patch 2.0..

**Comment by Marckotobelo** [comment]
every single item in the HC vendor is 2.1.. so we cant be on patch 2.0 anymore

**Comment by HamonTim** [comment]
![image](https://user-images.githubusercontent.com/38241815/63653630-ab416e00-c76f-11e9-8166-57f3d93b26e8.png)
The only item that is not there but should be is Orb of the Soul-eater.
All other are 2.3 (ZA)
