### ISSUE TITLE
Tablet of the Seven

### ISSUE THREAD

**Issue by Flinvoltx** [elysium-project/tbc-bug-tracker#921]
**Summary:** Quest Tablet of the Seven is not working

**Steps to Reproduce:** Pick quest and try to copy transcription from tablet.

**Expected Results:** Copied transcription, quest complete.

**Actual Result:** You can't copy transcription from tablet.

**Comment by andersleet** [comment]
Confirmed. Cannot transcribe the tablet even after abandoning and reaccepting the quest.

**Comment by IvanDanshin** [comment]
Fixed. Thanks for report!
