### ISSUE TITLE
Prove Your Hatred (Minion's Scourgestones)

### ISSUE THREAD

**Issue by ophiepala** [elysium-project/tbc-bug-tracker#934]
**Summary:** 
Undead mobs in Western Plaguelands do not drop Minion's Scourgestones (item=12840), making the blood elf paladin quest "Prove Your Hatred" aswell as the Argent Dawn rep quests incompletible.
**Steps to Reproduce:** 
Kill any undead mob in Western Plaguelands
**Expected Results:** 
Minion's Scourgestones would drop from undead mobs
**Actual Result:**
They don't
**Additional Information:**

**Comment by NregitneK** [comment]
You need the Argent Dawn trinket in order to get Scourgestones. Did you check that you have it equipped when killing undeads ?
