### ISSUE TITLE
A Mission of Mercy quest missing

### ISSUE THREAD

**Issue by Sherayin** [elysium-project/tbc-bug-tracker#937]
**Summary:** The Quest "A mision of mercy" should be available from Commander Ameer at Honored Reputation with Consortium 

**Steps to Reproduce:** 
Reach Honored Rep/do almost all other consortium quest in the area
**Expected Results:** 
Recieve Quest " a mission of mercy" from Commander Ameer
**Actual Result:**
No Quest available
**Additional Information:**
the Quest "Seek Out Ameer" from Protectorate Advisor Rahim may or may not be optional if you have not spoken to Ameer before, i believe i have already done it, it is not available to me anymore

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
