### ISSUE TITLE
items in mail vanishing

### ISSUE THREAD

**Issue by Sherayin** [elysium-project/tbc-bug-tracker#938]
**Summary:** 
some items vanish in mail and mail arrives without attachment, f.e. 2 nightmare vines, superior wizard oil, (a batch of 2 arrived and 4-5 of them didnt make it), primal earth, shadoweave mask
**Steps to Reproduce:** 
Mail items from low lvl alt (lvl 1 mage in undercity in my case) to lvl 70 character in outland and vice versa
**Expected Results:** 
all items should be in the mail
**Actual Result:**
some items arrive, some dont, mail arrives but without the items attached
**Additional Information:**

**Comment by Zinsora** [comment]
Same problem here. I lost many items in the mail aswell
