### ISSUE TITLE
Quest: Items of Power bugged

### ISSUE THREAD

**Issue by hartzejs** [elysium-project/tbc-bug-tracker#941]
**Summary:** Cannot collect Bolt Charged Bramble once totems are placed at the stone. Use gives failed on 10 totems being used at the stone - Bramble is created but cannot be picked up.

**Steps to Reproduce:** 
1. Gather 10 Witherbark Totem Sticks at
2. Go to the Circle of Outer Binding
3. Kill the elementals guarding the stones
4. Go into the stone in the middle of the circle and right-click the sticks in your inventory and the bramble will be charged 

**Expected Results:** Should be able to pick up Bramble

**Actual Result:**Cannot pick it up

**Additional Information:**

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
