### ISSUE TITLE
Paladin quests...

### ISSUE THREAD

**Issue by Malik444** [elysium-project/tbc-bug-tracker#944]
The quest Tome of Divinity, which you get as a human paladin in stormwind is still sorta bugged.

It requires you to find a dead dwarf, rez him, and grab another quest from him. Previously this auest was bugged, as any time you tried to rez the dwarf it would simply say "out of reach". That was patched, but now, he stands up, says "thank ye kind sir", hangs around for like 2min, and dies again without giving you the follow up quest.

https://classicdb.ch/?quest=1786

That's the link to what the quest should do, this is in vanilla as well and seems to be working fine there.

It rewards ressurection, a handy dandy tool to have when in a party I think.

**Comment by Flinvoltx** [comment]
https://github.com/elysium-project/tbc-bug-tracker/issues/824

**Comment by Komuccap** [comment]
still not working

**Comment by OblivionEly1** [comment]
[824](https://github.com/elysium-project/tbc-bug-tracker/issues/824)   This quest is fixed as in the attached link.

Thank you!
