### ISSUE TITLE
Escort quest "Stinky's Escape" dont works

### ISSUE THREAD

**Issue by kolgarlol** [elysium-project/tbc-bug-tracker#948]
**Summary:** It is broken escort quest. Escorting mob just stays at place and do nothing

**Steps to Reproduce:** I had started this quest 

**Expected Results:** this mob must start to walk from point "A" (his place) to a point "B" - finish position to complete escort

**Actual Result:**mob just stays at his place and do nothing

**Additional Information:**the path of this mob passes through water, it is worth paying special attention to this fact

**Comment by OblivionEly1** [comment]
**Confirmed** . The mob should be escorted and it doesn't move. 

_Thank you!_
