### ISSUE TITLE
Breaking Into the Arcatraz Quest Chain Stopped

### ISSUE THREAD

**Issue by robsmiggs** [elysium-project/tbc-bug-tracker#952]
**Summary:** 
After completing the first two quests in the chain for the "Breaking Into the Arcatraz" key quest; 1. Assisting the Consortium and then 2. Consortium Crystal Collection, the third quest "A Heap of Ethereals" is not being offered from Spymaster Thalodien.

**Steps to Reproduce:** 
No way to reproduce because the NPC does not offer the quest I am looking for.

**Expected Results:** 
Spymaster Thalodien to offer the quest "A Heap of Ethereals"

**Actual Result:**
Nothing

**Additional Information:**

**Comment by Ziggy-QA** [comment]
@robsmiggs You have to be friendly with consortium,
