### ISSUE TITLE
belf paladin quest "the first trial" spawns two mobs

### ISSUE THREAD

**Issue by nbonfire** [elysium-project/tbc-bug-tracker#953]
**Summary:** 
the belf paladin quest "the first trial" spawns two attackers
**Steps to Reproduce:** 
take the lvl 12 belf pal quest "the first trial", go to the island and use the brazier.
**Expected Results:** 
one mob should spawn
**Actual Result:**
two mobs spawn
**Additional Information:**

**Comment by nbonfire** [comment]
followup: the next part of the quest the npc is missing from the silvermoon inn, so maybe the second one is spawning at the brazier instead of dead in the inn

**Comment by OblivionEly1** [comment]
Confirmed, it should only spawn 1 mob.
