### ISSUE TITLE
Tears of the moon quest

### ISSUE THREAD

**Issue by DailyCasual** [elysium-project/tbc-bug-tracker#957]
**Summary:** 
general warbraids in bael modan hits for 400 at lvl 30. makes quest impossible
**Steps to Reproduce:** 
Be attacked by general warbraids
**Expected Results:** 
the quest mob would not hit for 400
**Actual Result:**
the quest mob hits for 400
**Additional Information:**

**Comment by IvanDanshin** [comment]
??? 
https://classic.wowhead.com/search?q=general+warbraid
https://classic.wowhead.com/quest=2518/tears-of-the-moon

**Comment by DailyCasual** [comment]
The quest npc guarding the crate, General Warbraid, hits for over 400. At
level 25-30 the quest was impossible with 2 people (hunter/shaman)

**Comment by IvanDanshin** [comment]
No such creature named as "General Warbraid".
Quest "Tears of the moon" is for 5lvl

**Comment by DailyCasual** [comment]
https://classic.wowhead.com/quest=857/the-tear-of-the-moons
https://vanilla-twinhead.twinstar.cz/?npc=3414
