### ISSUE TITLE
"Zapped Giants" quest bugged

### ISSUE THREAD

**Issue by owletrowlet** [elysium-project/tbc-bug-tracker#961]
**Summary:** When you receive "Zorbin's Ultra-Shrinker", using it is supposed to shrink giants in Feralas to a manageable size. When you use it, nothing happens.

**Steps to Reproduce:** Accept quest "Zapped Giants" in Feralas. Attempt to use the ultra-shrinker on a giant

**Expected Results:** Giants shrink down and are easier to kill. Once dead, they should drop miniaturization resude

**Actual Result:** Using the item does not shrink the giants, they don't even attack you.

**Additional Information:**

**Comment by OblivionEly1** [comment]
Confirmed. The item isn't working and it doesn't shrink the Giants.
