### ISSUE TITLE
Talisman of Binding Shard

### ISSUE THREAD

**Issue by Kazgaroth9** [elysium-project/tbc-bug-tracker#963]
**Summary:** 
The item Talisman of Binding Shard isn't giving it's buff to the player.
**Steps to Reproduce:** 
Equip it.
**Expected Results:** 
The necklace should give a buff called the same name and giving the hovering lightning ball around the player. (worked on nighthaven)
**Actual Result:**
No buffs when equipping the neck. only the animation plays.
**Additional Information:**

**Comment by OblivionEly1** [comment]
"Confirmed, it does not inflict damage and it does not give the buff.
