### ISSUE TITLE
Leathers are gone via mailbox

### ISSUE THREAD

**Issue by bandini9** [elysium-project/tbc-bug-tracker#964]
**Summary:** 
So; I cannot send leathers from my alt to my main. They are just going into void. It's fine when i send em from my main to alt.

**Steps to Reproduce:** 
-Farm leather
-Send em to alt on same acc
-alt receives leather
-send em back to main

**Expected Results:** 
-Leather in mailbox

**Actual Result:**
-Leather is not in mailbox.

**Additional Information:**
screenshot of mailbox https://ibb.co/PgrF6YT
![WoWScrnShot_090519_213224](https://user-images.githubusercontent.com/40371383/64369595-5f22e300-d025-11e9-8ca8-9c6660d0d359.jpg)

**Comment by Ziggy-QA** [comment]
#508 duplicate
