### ISSUE TITLE
Rogue's Stealth

### ISSUE THREAD

**Issue by Malik444** [elysium-project/tbc-bug-tracker#970]
**Summary:** 
If you log out or get disconnected while in stealth as a rogue, your stealth cooldown will come back up to 10sec despite you having the talent which can cut it down by up to 5sec.

**Steps to Reproduce:** 
Stealth, log out, log back in, unstealth, and watch the cooldown of it. Also have the talent taken from the subletly tree.

**Expected Results:** 
Your cooldown will stay 10secs, it should be 5 secs. And this cooldown will remain throughout your gameplay.

**Actual Result:**
Pops it up to 10sec.

**Additional Information:**
If you then log out without being in stealth, it fixes it 80% of the time. I was a few times forced to move somewhere or shut down the client completely. It's not a major bug, but it gets more than annoying when pvp-ing and farming as it gets way longer and more difficult.

**Comment by IvanDanshin** [comment]
Fixed. We can close it.
