### ISSUE TITLE
Mob missing/bugged: Mo'grosh Ogre (Loch Modan).

### ISSUE THREAD

**Issue by Vantalim** [elysium-project/tbc-bug-tracker#980]
**Summary:** 
[Mo'grosh Ogres](https://classic.wowhead.com/npc=1178/mogrosh-ogre) were nowhere to be found while doing the quest [Mercenaries](https://classic.wowhead.com/quest=255/mercenaries).
We looked around everywhere and noticed we would randomly start taking damage and get stunned by [knockdown](https://classic.wowhead.com/spell=5164/knockdown). We figured it was probably an invisible Mo'grosh Ogre. They can't be targeted. 

**Steps to Reproduce:** 
Walk around by the cave entrances. You can't see them, but they are there. 

**Expected Results:** 
Finding the mobs around the area/in the caves.

**Actual Result:**
Randomly taking damage and being hit by knockdown. Can't target the mob.

**Additional Information:**
Unable to complete the quest "Mercenaries" as a result.

**Comment by IvanDanshin** [comment]
Fixed and pushed to test server. Soon will be updated on live server. :)
Thanks for report.
