### ISSUE TITLE
Warlock Epic Mount

### ISSUE THREAD

**Issue by MGK82** [elysium-project/tbc-bug-tracker#981]
**Summary:** The final quest in Dire Maul doesn't work. 

**Steps to Reproduce:** Go to Dire Maul, clean the Pylons. Kill the last Boss. Start the ritual.

**Expected Results:** Glyphs are drawn on the floor to display the ritual's progress and at some point, the Epic Mount appears.

**Actual Result:** The ritual doesn't finish/progress.

**Additional Information:** I started the quest chain on Classic and tried to finish it on TBC. The server crashed multiple times during our presents in Dire Maul. I am close to 70 and think I gonna stuck from there, because I won't be able to progress the riding skills the designated way. Which locks the most important areas.

**Comment by Seizzz** [comment]
I also killed 2 times Dreadsteed of Xoroth, here is my xp 

Expected result : when Dreadsteed of Xoroth die, you should be able to bind his soul to you as quest says, in a form of a spirit to talk with 

Actual result : Dreadsteed of Xoroth is dead, nothing to interact with, quest is flagged as "Complete", but no new spell in tabs, and can't turn the quest anywhere 

Plz tell me if i have to abandon quest, or maybe you can summon the spirit, or simply give me the spell :)
