### ISSUE TITLE
Half-Buried Bottle

### ISSUE THREAD

**Issue by rotsak** [elysium-project/tbc-bug-tracker#992]
**Summary:** The Half-Buried Bottle's in STV don't seem to have a loot table.  

**Steps to Reproduce:** Loot the bottles

**Expected Results:** A chance to loot "Carefully folded note" - which is an item that starts a quest

**Actual Result:** Nothing, have looted well over 50 bottles with nothing on them

**Comment by invwax** [comment]
Seems fixed
