### ISSUE TITLE
Quest: Warlord Krellian

### ISSUE THREAD

**Issue by ignishtbc** [elysium-project/tbc-bug-tracker#999]
**Summary:** 
When the warlord is killed, he does not drop the prismatic shell (q item) 

**Steps to Reproduce:** 
Kill him, no loot 

**Expected Results:** 
 Get the shard for the quest 

**Actual Result:**

**Additional Information:**

**Comment by PsiloHEN** [comment]
I happen to have completed this quest yesterday just fine. Maybe producing the bug is more situational?

**Comment by ignishtbc** [comment]
Thanks mate, you were right.

I am now on the second part but it’s not registering when I kill the clones. Did yours?

Sendt fra min iPhone

Den 19. sep. 2019 kl. 10.28 skrev PsiloHEN <notifications@github.com<mailto:notifications@github.com>>:


I happen to have completed this quest yesterday just fine. Maybe producing the bug is more situational?
